/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) lipm_step_constr_h_fun_jac_uxt_zt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {10, 1, 1};
static const casadi_int casadi_s1[3] = {8, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {4, 1, 1};
static const casadi_int casadi_s4[3] = {6, 1, 1};
static const casadi_int casadi_s5[79] = 
  {18, 6, 0, 12, 24, 38, 52, 61,
  70, 4, 7, 8, 9, 10, 11, 12,
  13, 14, 15, 16, 17, 4, 7, 8,
  9, 10, 11, 12, 13, 14, 15, 16,
  17, 0, 1, 4, 7, 8, 9, 10,
  11, 12, 13, 14, 15, 16, 17, 2,
  3, 4, 7, 8, 9, 10, 11, 12,
  13, 14, 15, 16, 17, 4, 5, 6,
  8, 9, 14, 15, 16, 17, 4, 5,
  6, 8, 9, 14, 15, 16, 17};
static const casadi_int casadi_s6[3] = {6, 0, 1};

/* lipm_step_constr_h_fun_jac_uxt_zt:(i0[10],i1[8],i2[0],i3[4])->(o0[6],o1[18x6,70nz],o2[6x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39, a40, a41, a42, a43, a44, a45, a46;
  a00=arg[0]? arg[0][6] : 0;
  a01=5.0809240767486585e+00;
  a02=arg[1]? arg[1][7] : 0;
  a03=(a01*a02);
  a04=cosh(a03);
  a05=arg[0]? arg[0][0] : 0;
  a06=(a04*a05);
  a03=sinh(a03);
  a07=(a03/a01);
  a08=arg[0]? arg[0][3] : 0;
  a09=(a07*a08);
  a06=(a06+a09);
  a09=1.;
  a10=(a09-a04);
  a11=arg[1]? arg[1][4] : 0;
  a12=arg[0]? arg[0][8] : 0;
  a13=(a12-a00);
  a14=(a11*a13);
  a14=(a00+a14);
  a15=(a10*a14);
  a06=(a06+a15);
  a15=arg[0]? arg[0][2] : 0;
  a16=arg[0]? arg[0][5] : 0;
  a17=(a16*a02);
  a15=(a15+a17);
  a17=cos(a15);
  a18=arg[3]? arg[3][0] : 0;
  a19=(a17*a18);
  a15=sin(a15);
  a20=arg[3]? arg[3][1] : 0;
  a21=(a15*a20);
  a19=(a19-a21);
  a19=(a06+a19);
  a00=(a00-a19);
  a21=casadi_sq(a00);
  a22=arg[0]? arg[0][7] : 0;
  a23=arg[0]? arg[0][1] : 0;
  a24=(a04*a23);
  a25=arg[0]? arg[0][4] : 0;
  a26=(a07*a25);
  a24=(a24+a26);
  a26=arg[0]? arg[0][9] : 0;
  a27=(a26-a22);
  a28=(a11*a27);
  a28=(a22+a28);
  a29=(a10*a28);
  a24=(a24+a29);
  a29=(a15*a18);
  a30=(a17*a20);
  a29=(a29+a30);
  a29=(a24+a29);
  a22=(a22-a29);
  a30=casadi_sq(a22);
  a21=(a21+a30);
  if (res[0]!=0) res[0][0]=a21;
  a21=arg[3]? arg[3][2] : 0;
  a30=(a17*a21);
  a31=arg[3]? arg[3][3] : 0;
  a32=(a15*a31);
  a30=(a30-a32);
  a06=(a06+a30);
  a12=(a12-a06);
  a30=casadi_sq(a12);
  a32=(a15*a21);
  a33=(a17*a31);
  a32=(a32+a33);
  a24=(a24+a32);
  a26=(a26-a24);
  a32=casadi_sq(a26);
  a30=(a30+a32);
  if (res[0]!=0) res[0][1]=a30;
  a30=arg[1]? arg[1][0] : 0;
  a30=(a30-a19);
  a19=casadi_sq(a30);
  a32=arg[1]? arg[1][1] : 0;
  a32=(a32-a29);
  a29=casadi_sq(a32);
  a19=(a19+a29);
  if (res[0]!=0) res[0][2]=a19;
  a19=arg[1]? arg[1][2] : 0;
  a19=(a19-a06);
  a06=casadi_sq(a19);
  a29=arg[1]? arg[1][3] : 0;
  a29=(a29-a24);
  a24=casadi_sq(a29);
  a06=(a06+a24);
  if (res[0]!=0) res[0][3]=a06;
  a06=12.;
  a24=2.5815789473684209e+01;
  a33=(a05-a14);
  a33=(a24*a33);
  a33=(a06*a33);
  a34=2.;
  a33=(a33/a34);
  a35=arg[1]? arg[1][5] : 0;
  a36=(a33+a35);
  a37=casadi_sq(a36);
  a38=(a23-a28);
  a38=(a24*a38);
  a38=(a06*a38);
  a38=(a38/a34);
  a34=arg[1]? arg[1][6] : 0;
  a39=(a38+a34);
  a40=casadi_sq(a39);
  a37=(a37+a40);
  a40=9.8100000000000005e+00;
  a41=8.0000000000000004e-01;
  a42=(a41*a11);
  a42=(a06*a42);
  a42=(a40*a42);
  a43=casadi_sq(a42);
  a37=(a37-a43);
  a43=1.0000000000000000e-03;
  a37=(a37+a43);
  if (res[0]!=0) res[0][4]=a37;
  a33=(a33-a35);
  a35=casadi_sq(a33);
  a38=(a38-a34);
  a34=casadi_sq(a38);
  a35=(a35+a34);
  a09=(a09-a11);
  a09=(a41*a09);
  a09=(a06*a09);
  a09=(a40*a09);
  a34=casadi_sq(a09);
  a35=(a35-a34);
  a35=(a35+a43);
  if (res[0]!=0) res[0][5]=a35;
  a22=(a22+a22);
  a35=(a10*a22);
  a43=(a27*a35);
  a00=(a00+a00);
  a34=(a10*a00);
  a37=(a13*a34);
  a43=(a43+a37);
  a43=(-a43);
  if (res[1]!=0) res[1][0]=a43;
  a43=(a20*a22);
  a43=(a15*a43);
  a37=(a18*a22);
  a37=(a17*a37);
  a43=(a43-a37);
  a37=(a20*a00);
  a37=(a17*a37);
  a43=(a43+a37);
  a37=(a18*a00);
  a37=(a15*a37);
  a43=(a43+a37);
  a37=(a16*a43);
  a44=1.9681459216763408e-01;
  a45=(a25*a22);
  a46=(a08*a00);
  a45=(a45+a46);
  a45=(a44*a45);
  a45=(a04*a45);
  a45=(a01*a45);
  a37=(a37-a45);
  a45=(a28*a22);
  a46=(a14*a00);
  a45=(a45+a46);
  a46=(a23*a22);
  a45=(a45-a46);
  a46=(a05*a00);
  a45=(a45-a46);
  a45=(a03*a45);
  a45=(a01*a45);
  a37=(a37+a45);
  if (res[1]!=0) res[1][1]=a37;
  a37=(a04*a00);
  a37=(-a37);
  if (res[1]!=0) res[1][2]=a37;
  a37=(a04*a22);
  a37=(-a37);
  if (res[1]!=0) res[1][3]=a37;
  if (res[1]!=0) res[1][4]=a43;
  a37=(a07*a00);
  a37=(-a37);
  if (res[1]!=0) res[1][5]=a37;
  a37=(a07*a22);
  a37=(-a37);
  if (res[1]!=0) res[1][6]=a37;
  a43=(a02*a43);
  if (res[1]!=0) res[1][7]=a43;
  a00=(a00-a34);
  a34=(a11*a34);
  a00=(a00+a34);
  if (res[1]!=0) res[1][8]=a00;
  a22=(a22-a35);
  a35=(a11*a35);
  a22=(a22+a35);
  if (res[1]!=0) res[1][9]=a22;
  a34=(-a34);
  if (res[1]!=0) res[1][10]=a34;
  a35=(-a35);
  if (res[1]!=0) res[1][11]=a35;
  a26=(a26+a26);
  a35=(a10*a26);
  a34=(a27*a35);
  a12=(a12+a12);
  a22=(a10*a12);
  a00=(a13*a22);
  a34=(a34+a00);
  a34=(-a34);
  if (res[1]!=0) res[1][12]=a34;
  a34=(a31*a26);
  a34=(a15*a34);
  a00=(a21*a26);
  a00=(a17*a00);
  a34=(a34-a00);
  a00=(a31*a12);
  a00=(a17*a00);
  a34=(a34+a00);
  a00=(a21*a12);
  a00=(a15*a00);
  a34=(a34+a00);
  a00=(a16*a34);
  a43=(a25*a26);
  a37=(a08*a12);
  a43=(a43+a37);
  a43=(a44*a43);
  a43=(a04*a43);
  a43=(a01*a43);
  a00=(a00-a43);
  a43=(a28*a26);
  a37=(a14*a12);
  a43=(a43+a37);
  a37=(a23*a26);
  a43=(a43-a37);
  a37=(a05*a12);
  a43=(a43-a37);
  a43=(a03*a43);
  a43=(a01*a43);
  a00=(a00+a43);
  if (res[1]!=0) res[1][13]=a00;
  a00=(a04*a12);
  a00=(-a00);
  if (res[1]!=0) res[1][14]=a00;
  a00=(a04*a26);
  a00=(-a00);
  if (res[1]!=0) res[1][15]=a00;
  if (res[1]!=0) res[1][16]=a34;
  a00=(a07*a12);
  a00=(-a00);
  if (res[1]!=0) res[1][17]=a00;
  a00=(a07*a26);
  a00=(-a00);
  if (res[1]!=0) res[1][18]=a00;
  a34=(a02*a34);
  if (res[1]!=0) res[1][19]=a34;
  a34=(a11*a22);
  a22=(a34-a22);
  if (res[1]!=0) res[1][20]=a22;
  a22=(a11*a35);
  a35=(a22-a35);
  if (res[1]!=0) res[1][21]=a35;
  a12=(a12-a34);
  if (res[1]!=0) res[1][22]=a12;
  a26=(a26-a22);
  if (res[1]!=0) res[1][23]=a26;
  a30=(a30+a30);
  if (res[1]!=0) res[1][24]=a30;
  a32=(a32+a32);
  if (res[1]!=0) res[1][25]=a32;
  a26=(a10*a32);
  a22=(a27*a26);
  a12=(a10*a30);
  a34=(a13*a12);
  a22=(a22+a34);
  a22=(-a22);
  if (res[1]!=0) res[1][26]=a22;
  a22=(a20*a32);
  a22=(a15*a22);
  a34=(a18*a32);
  a34=(a17*a34);
  a22=(a22-a34);
  a20=(a20*a30);
  a20=(a17*a20);
  a22=(a22+a20);
  a18=(a18*a30);
  a18=(a15*a18);
  a22=(a22+a18);
  a18=(a16*a22);
  a20=(a25*a32);
  a34=(a08*a30);
  a20=(a20+a34);
  a20=(a44*a20);
  a20=(a04*a20);
  a20=(a01*a20);
  a18=(a18-a20);
  a20=(a28*a32);
  a34=(a14*a30);
  a20=(a20+a34);
  a34=(a23*a32);
  a20=(a20-a34);
  a34=(a05*a30);
  a20=(a20-a34);
  a20=(a03*a20);
  a20=(a01*a20);
  a18=(a18+a20);
  if (res[1]!=0) res[1][27]=a18;
  a18=(a04*a30);
  a18=(-a18);
  if (res[1]!=0) res[1][28]=a18;
  a18=(a04*a32);
  a18=(-a18);
  if (res[1]!=0) res[1][29]=a18;
  if (res[1]!=0) res[1][30]=a22;
  a30=(a07*a30);
  a30=(-a30);
  if (res[1]!=0) res[1][31]=a30;
  a32=(a07*a32);
  a32=(-a32);
  if (res[1]!=0) res[1][32]=a32;
  a22=(a02*a22);
  if (res[1]!=0) res[1][33]=a22;
  a22=(a11*a12);
  a12=(a22-a12);
  if (res[1]!=0) res[1][34]=a12;
  a12=(a11*a26);
  a26=(a12-a26);
  if (res[1]!=0) res[1][35]=a26;
  a22=(-a22);
  if (res[1]!=0) res[1][36]=a22;
  a12=(-a12);
  if (res[1]!=0) res[1][37]=a12;
  a19=(a19+a19);
  if (res[1]!=0) res[1][38]=a19;
  a29=(a29+a29);
  if (res[1]!=0) res[1][39]=a29;
  a12=(a10*a29);
  a22=(a27*a12);
  a10=(a10*a19);
  a26=(a13*a10);
  a22=(a22+a26);
  a22=(-a22);
  if (res[1]!=0) res[1][40]=a22;
  a22=(a31*a29);
  a22=(a15*a22);
  a26=(a21*a29);
  a26=(a17*a26);
  a22=(a22-a26);
  a31=(a31*a19);
  a17=(a17*a31);
  a22=(a22+a17);
  a21=(a21*a19);
  a15=(a15*a21);
  a22=(a22+a15);
  a16=(a16*a22);
  a25=(a25*a29);
  a08=(a08*a19);
  a25=(a25+a08);
  a44=(a44*a25);
  a44=(a04*a44);
  a44=(a01*a44);
  a16=(a16-a44);
  a28=(a28*a29);
  a14=(a14*a19);
  a28=(a28+a14);
  a23=(a23*a29);
  a28=(a28-a23);
  a05=(a05*a19);
  a28=(a28-a05);
  a03=(a03*a28);
  a01=(a01*a03);
  a16=(a16+a01);
  if (res[1]!=0) res[1][41]=a16;
  a16=(a04*a19);
  a16=(-a16);
  if (res[1]!=0) res[1][42]=a16;
  a04=(a04*a29);
  a04=(-a04);
  if (res[1]!=0) res[1][43]=a04;
  if (res[1]!=0) res[1][44]=a22;
  a19=(a07*a19);
  a19=(-a19);
  if (res[1]!=0) res[1][45]=a19;
  a07=(a07*a29);
  a07=(-a07);
  if (res[1]!=0) res[1][46]=a07;
  a02=(a02*a22);
  if (res[1]!=0) res[1][47]=a02;
  a02=(a11*a10);
  a10=(a02-a10);
  if (res[1]!=0) res[1][48]=a10;
  a10=(a11*a12);
  a12=(a10-a12);
  if (res[1]!=0) res[1][49]=a12;
  a02=(-a02);
  if (res[1]!=0) res[1][50]=a02;
  a10=(-a10);
  if (res[1]!=0) res[1][51]=a10;
  a42=(a42+a42);
  a42=(a40*a42);
  a42=(a06*a42);
  a42=(a41*a42);
  a10=5.0000000000000000e-01;
  a39=(a39+a39);
  a02=(a10*a39);
  a02=(a06*a02);
  a02=(a24*a02);
  a12=(a27*a02);
  a42=(a42+a12);
  a36=(a36+a36);
  a12=(a10*a36);
  a12=(a06*a12);
  a12=(a24*a12);
  a22=(a13*a12);
  a42=(a42+a22);
  a42=(-a42);
  if (res[1]!=0) res[1][52]=a42;
  if (res[1]!=0) res[1][53]=a36;
  if (res[1]!=0) res[1][54]=a39;
  if (res[1]!=0) res[1][55]=a12;
  if (res[1]!=0) res[1][56]=a02;
  a39=(a11*a12);
  a12=(a39-a12);
  if (res[1]!=0) res[1][57]=a12;
  a12=(a11*a02);
  a02=(a12-a02);
  if (res[1]!=0) res[1][58]=a02;
  a39=(-a39);
  if (res[1]!=0) res[1][59]=a39;
  a12=(-a12);
  if (res[1]!=0) res[1][60]=a12;
  a09=(a09+a09);
  a40=(a40*a09);
  a40=(a06*a40);
  a41=(a41*a40);
  a38=(a38+a38);
  a40=(a10*a38);
  a40=(a06*a40);
  a40=(a24*a40);
  a27=(a27*a40);
  a41=(a41-a27);
  a33=(a33+a33);
  a10=(a10*a33);
  a06=(a06*a10);
  a24=(a24*a06);
  a13=(a13*a24);
  a41=(a41-a13);
  if (res[1]!=0) res[1][61]=a41;
  a33=(-a33);
  if (res[1]!=0) res[1][62]=a33;
  a38=(-a38);
  if (res[1]!=0) res[1][63]=a38;
  if (res[1]!=0) res[1][64]=a24;
  if (res[1]!=0) res[1][65]=a40;
  a38=(a11*a24);
  a24=(a38-a24);
  if (res[1]!=0) res[1][66]=a24;
  a11=(a11*a40);
  a40=(a11-a40);
  if (res[1]!=0) res[1][67]=a40;
  a38=(-a38);
  if (res[1]!=0) res[1][68]=a38;
  a11=(-a11);
  if (res[1]!=0) res[1][69]=a11;
  return 0;
}

CASADI_SYMBOL_EXPORT int lipm_step_constr_h_fun_jac_uxt_zt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int lipm_step_constr_h_fun_jac_uxt_zt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int lipm_step_constr_h_fun_jac_uxt_zt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void lipm_step_constr_h_fun_jac_uxt_zt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int lipm_step_constr_h_fun_jac_uxt_zt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void lipm_step_constr_h_fun_jac_uxt_zt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void lipm_step_constr_h_fun_jac_uxt_zt_incref(void) {
}

CASADI_SYMBOL_EXPORT void lipm_step_constr_h_fun_jac_uxt_zt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int lipm_step_constr_h_fun_jac_uxt_zt_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int lipm_step_constr_h_fun_jac_uxt_zt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real lipm_step_constr_h_fun_jac_uxt_zt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* lipm_step_constr_h_fun_jac_uxt_zt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* lipm_step_constr_h_fun_jac_uxt_zt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* lipm_step_constr_h_fun_jac_uxt_zt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* lipm_step_constr_h_fun_jac_uxt_zt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    case 2: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int lipm_step_constr_h_fun_jac_uxt_zt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int lipm_step_constr_h_fun_jac_uxt_zt_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
