/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) lipm_opti_pessi_dyn_disc_phi_fun_jac_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[3] = {22, 1, 1};
static const casadi_int casadi_s1[3] = {8, 1, 1};
static const casadi_int casadi_s2[113] = 
  {44, 22, 0, 6, 12, 15, 21, 27,
  38, 39, 40, 41, 42, 44, 50, 56,
  59, 65, 71, 82, 83, 84, 85, 86,
  88, 4, 7, 22, 25, 28, 30, 4,
  7, 23, 26, 29, 31, 7, 24, 27,
  4, 7, 22, 25, 28, 30, 4, 7,
  23, 26, 29, 31, 4, 5, 6, 7,
  22, 23, 27, 28, 29, 30, 31, 0,
  1, 2, 3, 7, 32, 15, 18, 33,
  36, 39, 41, 15, 18, 34, 37, 40,
  42, 18, 35, 38, 15, 18, 33, 36,
  39, 41, 15, 18, 34, 37, 40, 42,
  15, 16, 17, 18, 33, 34, 38, 39,
  40, 41, 42, 11, 12, 13, 14, 18,
  43};
static const casadi_int casadi_s3[213] = 
  {44, 44, 0, 0, 0, 0, 0, 9,
  17, 25, 38, 38, 38, 38, 38, 38,
  38, 38, 47, 55, 63, 76, 76, 76,
  76, 83, 90, 90, 91, 92, 93, 100,
  107, 114, 121, 121, 128, 135, 135, 136,
  137, 138, 145, 152, 159, 166, 166, 5,
  6, 7, 22, 23, 28, 29, 30, 31,
  4, 7, 22, 23, 28, 29, 30, 31,
  4, 7, 22, 23, 28, 29, 30, 31,
  4, 5, 6, 7, 22, 23, 25, 26,
  27, 28, 29, 30, 31, 16, 17, 18,
  33, 34, 39, 40, 41, 42, 15, 18,
  33, 34, 39, 40, 41, 42, 15, 18,
  33, 34, 39, 40, 41, 42, 15, 16,
  17, 18, 33, 34, 36, 37, 38, 39,
  40, 41, 42, 4, 5, 6, 7, 23,
  29, 31, 4, 5, 6, 7, 22, 28,
  30, 7, 7, 7, 4, 5, 6, 7,
  23, 29, 31, 4, 5, 6, 7, 22,
  28, 30, 4, 5, 6, 7, 23, 29,
  31, 4, 5, 6, 7, 22, 28, 30,
  15, 16, 17, 18, 34, 40, 42, 15,
  16, 17, 18, 33, 39, 41, 18, 18,
  18, 15, 16, 17, 18, 34, 40, 42,
  15, 16, 17, 18, 33, 39, 41, 15,
  16, 17, 18, 34, 40, 42, 15, 16,
  17, 18, 33, 39, 41};

/* lipm_opti_pessi_dyn_disc_phi_fun_jac_hess:(i0[22],i1[22],i2[22],i3[8])->(o0[22],o1[44x22,88nz],o2[44x44,166nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a000, a001, a002, a003, a004, a005, a006, a007, a008, a009, a010, a011;
  casadi_real a012, a013, a014, a015, a016, a017, a018, a019, a020, a021, a022, a023;
  casadi_real a024, a025, a026, a027, a028, a029, a030, a031, a032, a033, a034, a035;
  casadi_real a036, a037, a038, a039, a040, a041, a042, a043, a044, a045, a046, a047;
  casadi_real a048, a049, a050, a051, a052, a053, a054, a055, a056, a057, a058, a059;
  casadi_real a060, a061, a062, a063, a064, a065, a066, a067, a068, a069, a070, a071;
  casadi_real a072, a073, a074, a075, a076, a077, a078, a079, a080, a081, a082, a083;
  casadi_real a084, a085, a086, a087, a088, a089, a090, a091, a092, a093, a094, a095;
  casadi_real a096, a097, a098, a099, a100, a101, a102, a103, a104, a105, a106, a107;
  casadi_real a108, a109, a110, a111, a112, a113, a114, a115, a116, a117;
  a000=5.0809240767486585e+00;
  a001=arg[1]? arg[1][7] : 0;
  a002=(a000*a001);
  a003=cosh(a002);
  a004=arg[0]? arg[0][0] : 0;
  a005=(a003*a004);
  a002=sinh(a002);
  a006=(a002/a000);
  a007=arg[0]? arg[0][3] : 0;
  a008=(a006*a007);
  a005=(a005+a008);
  a008=1.;
  a009=(a008-a003);
  a010=arg[0]? arg[0][6] : 0;
  a011=arg[1]? arg[1][4] : 0;
  a012=arg[0]? arg[0][8] : 0;
  a013=(a012-a010);
  a014=(a011*a013);
  a014=(a010+a014);
  a015=(a009*a014);
  a005=(a005+a015);
  if (res[0]!=0) res[0][0]=a005;
  a005=arg[0]? arg[0][1] : 0;
  a015=(a003*a005);
  a016=arg[0]? arg[0][4] : 0;
  a017=(a006*a016);
  a015=(a015+a017);
  a017=arg[0]? arg[0][7] : 0;
  a018=arg[0]? arg[0][9] : 0;
  a019=(a018-a017);
  a020=(a011*a019);
  a020=(a017+a020);
  a021=(a009*a020);
  a015=(a015+a021);
  if (res[0]!=0) res[0][1]=a015;
  a015=arg[0]? arg[0][2] : 0;
  a021=arg[0]? arg[0][5] : 0;
  a022=(a021*a001);
  a015=(a015+a022);
  if (res[0]!=0) res[0][2]=a015;
  a015=(a000*a002);
  a022=(a015*a004);
  a023=(a003*a007);
  a022=(a022+a023);
  a023=(a015*a014);
  a022=(a022-a023);
  if (res[0]!=0) res[0][3]=a022;
  a022=(a015*a005);
  a023=(a003*a016);
  a022=(a022+a023);
  a023=(a015*a020);
  a022=(a022-a023);
  if (res[0]!=0) res[0][4]=a022;
  a022=1.0480000000000000e+00;
  a023=(a001/a022);
  a010=(a010-a004);
  a024=arg[1]? arg[1][6] : 0;
  a025=2.4239999999999998e+01;
  a026=2.5815789473684209e+01;
  a027=(a005-a020);
  a027=(a026*a027);
  a027=(a025*a027);
  a028=(a024*a027);
  a029=(a010*a028);
  a017=(a017-a005);
  a030=arg[1]? arg[1][5] : 0;
  a031=(a004-a014);
  a031=(a026*a031);
  a031=(a025*a031);
  a032=(a030*a031);
  a033=(a017*a032);
  a029=(a029-a033);
  a012=(a012-a004);
  a033=(a008-a024);
  a034=(a033*a027);
  a035=(a012*a034);
  a018=(a018-a005);
  a036=(a008-a030);
  a037=(a036*a031);
  a038=(a018*a037);
  a035=(a035-a038);
  a029=(a029+a035);
  a035=(a023*a029);
  a035=(a021+a035);
  if (res[0]!=0) res[0][5]=a035;
  a035=arg[1]? arg[1][0] : 0;
  if (res[0]!=0) res[0][6]=a035;
  a035=arg[1]? arg[1][1] : 0;
  if (res[0]!=0) res[0][7]=a035;
  a035=arg[1]? arg[1][2] : 0;
  if (res[0]!=0) res[0][8]=a035;
  a035=arg[1]? arg[1][3] : 0;
  if (res[0]!=0) res[0][9]=a035;
  a035=arg[0]? arg[0][10] : 0;
  a035=(a035+a001);
  if (res[0]!=0) res[0][10]=a035;
  a035=arg[1]? arg[1][18] : 0;
  a038=(a000*a035);
  a039=cosh(a038);
  a040=arg[0]? arg[0][11] : 0;
  a041=(a039*a040);
  a038=sinh(a038);
  a042=(a038/a000);
  a043=arg[0]? arg[0][14] : 0;
  a044=(a042*a043);
  a041=(a041+a044);
  a044=(a008-a039);
  a045=arg[0]? arg[0][17] : 0;
  a046=arg[1]? arg[1][15] : 0;
  a047=arg[0]? arg[0][19] : 0;
  a048=(a047-a045);
  a049=(a046*a048);
  a049=(a045+a049);
  a050=(a044*a049);
  a041=(a041+a050);
  if (res[0]!=0) res[0][11]=a041;
  a041=arg[0]? arg[0][12] : 0;
  a050=(a039*a041);
  a051=arg[0]? arg[0][15] : 0;
  a052=(a042*a051);
  a050=(a050+a052);
  a052=arg[0]? arg[0][18] : 0;
  a053=arg[0]? arg[0][20] : 0;
  a054=(a053-a052);
  a055=(a046*a054);
  a055=(a052+a055);
  a056=(a044*a055);
  a050=(a050+a056);
  if (res[0]!=0) res[0][12]=a050;
  a050=arg[0]? arg[0][13] : 0;
  a056=arg[0]? arg[0][16] : 0;
  a057=(a056*a035);
  a050=(a050+a057);
  if (res[0]!=0) res[0][13]=a050;
  a050=(a000*a038);
  a057=(a050*a040);
  a058=(a039*a043);
  a057=(a057+a058);
  a058=(a050*a049);
  a057=(a057-a058);
  if (res[0]!=0) res[0][14]=a057;
  a057=(a050*a041);
  a058=(a039*a051);
  a057=(a057+a058);
  a058=(a050*a055);
  a057=(a057-a058);
  if (res[0]!=0) res[0][15]=a057;
  a022=(a035/a022);
  a045=(a045-a040);
  a057=arg[1]? arg[1][17] : 0;
  a058=(a041-a055);
  a058=(a026*a058);
  a058=(a025*a058);
  a059=(a057*a058);
  a060=(a045*a059);
  a052=(a052-a041);
  a061=arg[1]? arg[1][16] : 0;
  a062=(a040-a049);
  a062=(a026*a062);
  a062=(a025*a062);
  a063=(a061*a062);
  a064=(a052*a063);
  a060=(a060-a064);
  a047=(a047-a040);
  a064=(a008-a057);
  a065=(a064*a058);
  a066=(a047*a065);
  a053=(a053-a041);
  a067=(a008-a061);
  a068=(a067*a062);
  a069=(a053*a068);
  a066=(a066-a069);
  a060=(a060+a066);
  a066=(a022*a060);
  a066=(a056+a066);
  if (res[0]!=0) res[0][16]=a066;
  a066=arg[1]? arg[1][11] : 0;
  if (res[0]!=0) res[0][17]=a066;
  a066=arg[1]? arg[1][12] : 0;
  if (res[0]!=0) res[0][18]=a066;
  a066=arg[1]? arg[1][13] : 0;
  if (res[0]!=0) res[0][19]=a066;
  a066=arg[1]? arg[1][14] : 0;
  if (res[0]!=0) res[0][20]=a066;
  a066=arg[0]? arg[0][21] : 0;
  a066=(a066+a035);
  if (res[0]!=0) res[0][21]=a066;
  a066=(a009*a013);
  if (res[1]!=0) res[1][0]=a066;
  a066=(a004*a015);
  a069=(a007*a003);
  a066=(a066+a069);
  a069=(a014*a015);
  a066=(a066-a069);
  if (res[1]!=0) res[1][1]=a066;
  if (res[1]!=0) res[1][2]=a003;
  if (res[1]!=0) res[1][3]=a006;
  a066=(a008-a011);
  a069=(a009*a066);
  if (res[1]!=0) res[1][4]=a069;
  a070=(a009*a011);
  if (res[1]!=0) res[1][5]=a070;
  a071=(a009*a019);
  if (res[1]!=0) res[1][6]=a071;
  a071=(a005*a015);
  a072=(a016*a003);
  a071=(a071+a072);
  a072=(a020*a015);
  a071=(a071-a072);
  if (res[1]!=0) res[1][7]=a071;
  if (res[1]!=0) res[1][8]=a003;
  if (res[1]!=0) res[1][9]=a006;
  if (res[1]!=0) res[1][10]=a069;
  if (res[1]!=0) res[1][11]=a070;
  if (res[1]!=0) res[1][12]=a021;
  if (res[1]!=0) res[1][13]=a008;
  if (res[1]!=0) res[1][14]=a001;
  a001=(a015*a013);
  a001=(-a001);
  if (res[1]!=0) res[1][15]=a001;
  a001=(a000*a003);
  a021=(a000*a001);
  a070=(a004*a021);
  a069=(a007*a015);
  a070=(a070+a069);
  a069=(a014*a021);
  a070=(a070-a069);
  if (res[1]!=0) res[1][16]=a070;
  if (res[1]!=0) res[1][17]=a015;
  if (res[1]!=0) res[1][18]=a003;
  a070=(a015*a066);
  a070=(-a070);
  if (res[1]!=0) res[1][19]=a070;
  a069=(a015*a011);
  a069=(-a069);
  if (res[1]!=0) res[1][20]=a069;
  a006=(a015*a019);
  a006=(-a006);
  if (res[1]!=0) res[1][21]=a006;
  a006=(a005*a021);
  a071=(a016*a015);
  a006=(a006+a071);
  a071=(a020*a021);
  a006=(a006-a071);
  if (res[1]!=0) res[1][22]=a006;
  if (res[1]!=0) res[1][23]=a015;
  if (res[1]!=0) res[1][24]=a003;
  if (res[1]!=0) res[1][25]=a070;
  if (res[1]!=0) res[1][26]=a069;
  a069=(a026*a013);
  a069=(a025*a069);
  a070=(a030*a069);
  a006=(a017*a070);
  a071=(a026*a019);
  a071=(a025*a071);
  a072=(a024*a071);
  a072=(a010*a072);
  a006=(a006-a072);
  a069=(a036*a069);
  a072=(a018*a069);
  a071=(a033*a071);
  a071=(a012*a071);
  a072=(a072-a071);
  a006=(a006+a072);
  a006=(a023*a006);
  if (res[1]!=0) res[1][27]=a006;
  a006=(a018*a031);
  a072=(a017*a031);
  a006=(a006-a072);
  a072=(a023*a006);
  if (res[1]!=0) res[1][28]=a072;
  a072=(a010*a027);
  a071=(a012*a027);
  a072=(a072-a071);
  a071=(a023*a072);
  if (res[1]!=0) res[1][29]=a071;
  a071=9.5419847328244267e-01;
  a029=(a071*a029);
  if (res[1]!=0) res[1][30]=a029;
  a029=6.2577473684210520e+02;
  a073=(a029*a030);
  a074=(a017*a073);
  a074=(a028+a074);
  a075=(a029*a036);
  a076=(a018*a075);
  a076=(a034+a076);
  a074=(a074+a076);
  a076=(a023*a074);
  a076=(-a076);
  if (res[1]!=0) res[1][31]=a076;
  a076=(a029*a024);
  a076=(a010*a076);
  a076=(a076+a032);
  a077=(a029*a033);
  a077=(a012*a077);
  a077=(a077+a037);
  a076=(a076+a077);
  a076=(a023*a076);
  if (res[1]!=0) res[1][32]=a076;
  if (res[1]!=0) res[1][33]=a008;
  a076=(a026*a066);
  a076=(a025*a076);
  a077=(a030*a076);
  a078=(a017*a077);
  a028=(a028+a078);
  a078=(a036*a076);
  a079=(a018*a078);
  a028=(a028+a079);
  a079=(a023*a028);
  if (res[1]!=0) res[1][34]=a079;
  a079=(a024*a076);
  a080=(a010*a079);
  a080=(a080+a032);
  a081=(a033*a076);
  a082=(a012*a081);
  a080=(a080+a082);
  a082=(a023*a080);
  a082=(-a082);
  if (res[1]!=0) res[1][35]=a082;
  a082=(a026*a011);
  a082=(a025*a082);
  a083=(a030*a082);
  a084=(a017*a083);
  a085=(a036*a082);
  a086=(a018*a085);
  a034=(a034+a086);
  a084=(a084+a034);
  a034=(a023*a084);
  if (res[1]!=0) res[1][36]=a034;
  a034=(a024*a082);
  a034=(a010*a034);
  a086=(a033*a082);
  a086=(a012*a086);
  a086=(a086+a037);
  a034=(a034+a086);
  a034=(a023*a034);
  a034=(-a034);
  if (res[1]!=0) res[1][37]=a034;
  if (res[1]!=0) res[1][38]=a008;
  if (res[1]!=0) res[1][39]=a008;
  if (res[1]!=0) res[1][40]=a008;
  if (res[1]!=0) res[1][41]=a008;
  if (res[1]!=0) res[1][42]=a008;
  if (res[1]!=0) res[1][43]=a008;
  a034=(a044*a048);
  if (res[1]!=0) res[1][44]=a034;
  a034=(a040*a050);
  a086=(a043*a039);
  a034=(a034+a086);
  a086=(a049*a050);
  a034=(a034-a086);
  if (res[1]!=0) res[1][45]=a034;
  if (res[1]!=0) res[1][46]=a039;
  if (res[1]!=0) res[1][47]=a042;
  a034=(a008-a046);
  a086=(a044*a034);
  if (res[1]!=0) res[1][48]=a086;
  a087=(a044*a046);
  if (res[1]!=0) res[1][49]=a087;
  a088=(a044*a054);
  if (res[1]!=0) res[1][50]=a088;
  a088=(a041*a050);
  a089=(a051*a039);
  a088=(a088+a089);
  a089=(a055*a050);
  a088=(a088-a089);
  if (res[1]!=0) res[1][51]=a088;
  if (res[1]!=0) res[1][52]=a039;
  if (res[1]!=0) res[1][53]=a042;
  if (res[1]!=0) res[1][54]=a086;
  if (res[1]!=0) res[1][55]=a087;
  if (res[1]!=0) res[1][56]=a056;
  if (res[1]!=0) res[1][57]=a008;
  if (res[1]!=0) res[1][58]=a035;
  a035=(a050*a048);
  a035=(-a035);
  if (res[1]!=0) res[1][59]=a035;
  a035=(a000*a039);
  a056=(a000*a035);
  a087=(a040*a056);
  a086=(a043*a050);
  a087=(a087+a086);
  a086=(a049*a056);
  a087=(a087-a086);
  if (res[1]!=0) res[1][60]=a087;
  if (res[1]!=0) res[1][61]=a050;
  if (res[1]!=0) res[1][62]=a039;
  a087=(a050*a034);
  a087=(-a087);
  if (res[1]!=0) res[1][63]=a087;
  a086=(a050*a046);
  a086=(-a086);
  if (res[1]!=0) res[1][64]=a086;
  a042=(a050*a054);
  a042=(-a042);
  if (res[1]!=0) res[1][65]=a042;
  a042=(a041*a056);
  a088=(a051*a050);
  a042=(a042+a088);
  a088=(a055*a056);
  a042=(a042-a088);
  if (res[1]!=0) res[1][66]=a042;
  if (res[1]!=0) res[1][67]=a050;
  if (res[1]!=0) res[1][68]=a039;
  if (res[1]!=0) res[1][69]=a087;
  if (res[1]!=0) res[1][70]=a086;
  a086=(a026*a048);
  a086=(a025*a086);
  a087=(a061*a086);
  a042=(a052*a087);
  a088=(a026*a054);
  a088=(a025*a088);
  a089=(a057*a088);
  a089=(a045*a089);
  a042=(a042-a089);
  a086=(a067*a086);
  a089=(a053*a086);
  a088=(a064*a088);
  a088=(a047*a088);
  a089=(a089-a088);
  a042=(a042+a089);
  a042=(a022*a042);
  if (res[1]!=0) res[1][71]=a042;
  a042=(a053*a062);
  a089=(a052*a062);
  a042=(a042-a089);
  a089=(a022*a042);
  if (res[1]!=0) res[1][72]=a089;
  a089=(a045*a058);
  a088=(a047*a058);
  a089=(a089-a088);
  a088=(a022*a089);
  if (res[1]!=0) res[1][73]=a088;
  a060=(a071*a060);
  if (res[1]!=0) res[1][74]=a060;
  a060=(a029*a061);
  a088=(a052*a060);
  a088=(a059+a088);
  a090=(a029*a067);
  a091=(a053*a090);
  a091=(a065+a091);
  a088=(a088+a091);
  a091=(a022*a088);
  a091=(-a091);
  if (res[1]!=0) res[1][75]=a091;
  a091=(a029*a057);
  a091=(a045*a091);
  a091=(a091+a063);
  a092=(a029*a064);
  a092=(a047*a092);
  a092=(a092+a068);
  a091=(a091+a092);
  a091=(a022*a091);
  if (res[1]!=0) res[1][76]=a091;
  if (res[1]!=0) res[1][77]=a008;
  a091=(a026*a034);
  a091=(a025*a091);
  a092=(a061*a091);
  a093=(a052*a092);
  a059=(a059+a093);
  a093=(a067*a091);
  a094=(a053*a093);
  a059=(a059+a094);
  a094=(a022*a059);
  if (res[1]!=0) res[1][78]=a094;
  a094=(a057*a091);
  a095=(a045*a094);
  a095=(a095+a063);
  a096=(a064*a091);
  a097=(a047*a096);
  a095=(a095+a097);
  a097=(a022*a095);
  a097=(-a097);
  if (res[1]!=0) res[1][79]=a097;
  a097=(a026*a046);
  a097=(a025*a097);
  a098=(a061*a097);
  a099=(a052*a098);
  a100=(a067*a097);
  a101=(a053*a100);
  a065=(a065+a101);
  a099=(a099+a065);
  a065=(a022*a099);
  if (res[1]!=0) res[1][80]=a065;
  a065=(a057*a097);
  a065=(a045*a065);
  a101=(a064*a097);
  a101=(a047*a101);
  a101=(a101+a068);
  a065=(a065+a101);
  a065=(a022*a065);
  a065=(-a065);
  if (res[1]!=0) res[1][81]=a065;
  if (res[1]!=0) res[1][82]=a008;
  if (res[1]!=0) res[1][83]=a008;
  if (res[1]!=0) res[1][84]=a008;
  if (res[1]!=0) res[1][85]=a008;
  if (res[1]!=0) res[1][86]=a008;
  if (res[1]!=0) res[1][87]=a008;
  a008=arg[2]? arg[2][5] : 0;
  a023=(a023*a008);
  a065=(a017*a023);
  a101=(a018*a023);
  a102=(a065-a101);
  a102=(a025*a102);
  a102=(a026*a102);
  a102=(a013*a102);
  if (res[2]!=0) res[2][0]=a102;
  a103=(a010*a023);
  a104=(a012*a023);
  a105=(a103-a104);
  a105=(a025*a105);
  a105=(a026*a105);
  a106=(a019*a105);
  a106=(-a106);
  if (res[2]!=0) res[2][1]=a106;
  a107=(a071*a008);
  a018=(a018*a107);
  a018=(a036*a018);
  a017=(a017*a107);
  a017=(a030*a017);
  a018=(a018+a017);
  a018=(a025*a018);
  a018=(a026*a018);
  a017=arg[2]? arg[2][3] : 0;
  a108=(a017*a021);
  a018=(a018-a108);
  a108=arg[2]? arg[2][0] : 0;
  a109=(a108*a015);
  a018=(a018-a109);
  a018=(a013*a018);
  a109=arg[2]? arg[2][1] : 0;
  a110=(a109*a015);
  a012=(a012*a107);
  a012=(a033*a012);
  a010=(a010*a107);
  a010=(a024*a010);
  a012=(a012+a010);
  a012=(a025*a012);
  a012=(a026*a012);
  a010=arg[2]? arg[2][4] : 0;
  a021=(a010*a021);
  a111=(a012+a021);
  a111=(a110+a111);
  a112=(a019*a111);
  a018=(a018-a112);
  if (res[2]!=0) res[2][2]=a018;
  a112=(a033*a023);
  a113=(a024*a023);
  a114=(a112+a113);
  a114=(a025*a114);
  a114=(a026*a114);
  a115=(a019*a114);
  if (res[2]!=0) res[2][3]=a115;
  a069=(a023*a069);
  a070=(a023*a070);
  a070=(a069+a070);
  a070=(-a070);
  if (res[2]!=0) res[2][4]=a070;
  a113=(a025*a113);
  a113=(a026*a113);
  a116=(a019*a113);
  a036=(a036*a101);
  a117=(a030*a065);
  a036=(a036+a117);
  a036=(a025*a036);
  a036=(a026*a036);
  a117=(a015*a017);
  a036=(a036-a117);
  a117=(a009*a108);
  a036=(a036+a117);
  a116=(a116+a036);
  a116=(-a116);
  if (res[2]!=0) res[2][5]=a116;
  a030=(a030*a023);
  a030=(a025*a030);
  a030=(a026*a030);
  a013=(a013*a030);
  a009=(a009*a109);
  a033=(a033*a104);
  a024=(a024*a103);
  a033=(a033+a024);
  a033=(a025*a033);
  a033=(a026*a033);
  a024=(a015*a010);
  a033=(a033+a024);
  a009=(a009-a033);
  a013=(a013-a009);
  if (res[2]!=0) res[2][6]=a013;
  a112=(a025*a112);
  a112=(a026*a112);
  a019=(a019*a112);
  a036=(a036-a019);
  if (res[2]!=0) res[2][7]=a036;
  a009=(a009+a069);
  if (res[2]!=0) res[2][8]=a009;
  if (res[2]!=0) res[2][9]=a102;
  a006=(a008*a006);
  a006=(a071*a006);
  if (res[2]!=0) res[2][10]=a006;
  a102=(a029*a101);
  a069=(a029*a065);
  a102=(a102-a069);
  if (res[2]!=0) res[2][11]=a102;
  a069=0.;
  if (res[2]!=0) res[2][12]=a069;
  a019=(a065*a076);
  a033=(a101*a076);
  a019=(a019-a033);
  if (res[2]!=0) res[2][13]=a019;
  a033=(a031*a023);
  a033=(-a033);
  if (res[2]!=0) res[2][14]=a033;
  a065=(a065*a082);
  a101=(a101*a082);
  a065=(a065-a101);
  if (res[2]!=0) res[2][15]=a065;
  a031=(a023*a031);
  if (res[2]!=0) res[2][16]=a031;
  if (res[2]!=0) res[2][17]=a106;
  a072=(a008*a072);
  a072=(a071*a072);
  if (res[2]!=0) res[2][18]=a072;
  if (res[2]!=0) res[2][19]=a069;
  if (res[2]!=0) res[2][20]=a105;
  a027=(a027*a023);
  if (res[2]!=0) res[2][21]=a027;
  a104=(a104*a076);
  a103=(a103*a076);
  a104=(a104-a103);
  if (res[2]!=0) res[2][22]=a104;
  a103=(-a027);
  if (res[2]!=0) res[2][23]=a103;
  a076=(a011*a105);
  a076=(-a076);
  if (res[2]!=0) res[2][24]=a076;
  if (res[2]!=0) res[2][25]=a018;
  if (res[2]!=0) res[2][26]=a006;
  if (res[2]!=0) res[2][27]=a072;
  a072=(a005*a010);
  a006=(a004*a017);
  a072=(a072+a006);
  a072=(a000*a072);
  a006=(a020*a010);
  a018=(a014*a017);
  a006=(a006+a018);
  a006=(a000*a006);
  a072=(a072-a006);
  a006=1.9681459216763408e-01;
  a018=(a016*a109);
  a106=(a007*a108);
  a018=(a018+a106);
  a018=(a006*a018);
  a072=(a072+a018);
  a072=(a072*a015);
  a072=(a000*a072);
  a016=(a016*a010);
  a007=(a007*a017);
  a016=(a016+a007);
  a005=(a005*a109);
  a016=(a016+a005);
  a020=(a020*a109);
  a014=(a014*a108);
  a020=(a020+a014);
  a016=(a016-a020);
  a004=(a004*a108);
  a016=(a016+a004);
  a016=(a016*a001);
  a016=(a000*a016);
  a072=(a072+a016);
  if (res[2]!=0) res[2][28]=a072;
  a072=(a000*a017);
  a072=(a003*a072);
  a072=(a000*a072);
  a074=(a008*a074);
  a074=(a071*a074);
  a072=(a072-a074);
  a074=(a002*a108);
  a074=(a000*a074);
  a072=(a072+a074);
  if (res[2]!=0) res[2][29]=a072;
  a037=(a037*a107);
  a032=(a032*a107);
  a032=(a037+a032);
  a032=(a032+a012);
  a032=(a032+a021);
  a032=(a032+a110);
  if (res[2]!=0) res[2][30]=a032;
  a110=(a017*a015);
  a021=(a108*a003);
  a110=(a110+a021);
  if (res[2]!=0) res[2][31]=a110;
  a015=(a010*a015);
  a021=(a109*a003);
  a015=(a015+a021);
  if (res[2]!=0) res[2][32]=a015;
  a021=arg[2]? arg[2][2] : 0;
  if (res[2]!=0) res[2][33]=a021;
  a028=(a008*a028);
  a028=(a071*a028);
  a012=(a017*a066);
  a012=(a000*a012);
  a012=(a003*a012);
  a012=(a000*a012);
  a028=(a028-a012);
  a012=(a108*a066);
  a012=(a002*a012);
  a012=(a000*a012);
  a028=(a028-a012);
  if (res[2]!=0) res[2][34]=a028;
  a080=(a008*a080);
  a080=(a071*a080);
  a010=(a010*a066);
  a010=(a000*a010);
  a010=(a003*a010);
  a010=(a000*a010);
  a080=(a080+a010);
  a109=(a109*a066);
  a109=(a002*a109);
  a109=(a000*a109);
  a080=(a080+a109);
  a080=(-a080);
  if (res[2]!=0) res[2][35]=a080;
  a008=(a008*a084);
  a008=(a071*a008);
  a017=(a017*a011);
  a017=(a000*a017);
  a003=(a003*a017);
  a003=(a000*a003);
  a008=(a008-a003);
  a108=(a108*a011);
  a002=(a002*a108);
  a002=(a000*a002);
  a008=(a008-a002);
  if (res[2]!=0) res[2][36]=a008;
  a111=(a011*a111);
  a111=(a111+a037);
  a111=(-a111);
  if (res[2]!=0) res[2][37]=a111;
  a037=arg[2]? arg[2][16] : 0;
  a022=(a022*a037);
  a002=(a052*a022);
  a108=(a053*a022);
  a003=(a002-a108);
  a003=(a025*a003);
  a003=(a026*a003);
  a003=(a048*a003);
  if (res[2]!=0) res[2][38]=a003;
  a017=(a045*a022);
  a084=(a047*a022);
  a109=(a017-a084);
  a109=(a025*a109);
  a109=(a026*a109);
  a066=(a054*a109);
  a066=(-a066);
  if (res[2]!=0) res[2][39]=a066;
  a010=(a071*a037);
  a053=(a053*a010);
  a053=(a067*a053);
  a052=(a052*a010);
  a052=(a061*a052);
  a053=(a053+a052);
  a053=(a025*a053);
  a053=(a026*a053);
  a052=arg[2]? arg[2][14] : 0;
  a012=(a052*a056);
  a053=(a053-a012);
  a012=arg[2]? arg[2][11] : 0;
  a107=(a012*a050);
  a053=(a053-a107);
  a053=(a048*a053);
  a107=arg[2]? arg[2][12] : 0;
  a074=(a107*a050);
  a047=(a047*a010);
  a047=(a064*a047);
  a045=(a045*a010);
  a045=(a057*a045);
  a047=(a047+a045);
  a047=(a025*a047);
  a047=(a026*a047);
  a045=arg[2]? arg[2][15] : 0;
  a056=(a045*a056);
  a016=(a047+a056);
  a016=(a074+a016);
  a001=(a054*a016);
  a053=(a053-a001);
  if (res[2]!=0) res[2][40]=a053;
  a001=(a064*a022);
  a004=(a057*a022);
  a020=(a001+a004);
  a020=(a025*a020);
  a020=(a026*a020);
  a014=(a054*a020);
  if (res[2]!=0) res[2][41]=a014;
  a086=(a022*a086);
  a087=(a022*a087);
  a087=(a086+a087);
  a087=(-a087);
  if (res[2]!=0) res[2][42]=a087;
  a004=(a025*a004);
  a004=(a026*a004);
  a005=(a054*a004);
  a067=(a067*a108);
  a007=(a061*a002);
  a067=(a067+a007);
  a067=(a025*a067);
  a067=(a026*a067);
  a007=(a050*a052);
  a067=(a067-a007);
  a007=(a044*a012);
  a067=(a067+a007);
  a005=(a005+a067);
  a005=(-a005);
  if (res[2]!=0) res[2][43]=a005;
  a061=(a061*a022);
  a061=(a025*a061);
  a061=(a026*a061);
  a048=(a048*a061);
  a044=(a044*a107);
  a064=(a064*a084);
  a057=(a057*a017);
  a064=(a064+a057);
  a064=(a025*a064);
  a064=(a026*a064);
  a057=(a050*a045);
  a064=(a064+a057);
  a044=(a044-a064);
  a048=(a048-a044);
  if (res[2]!=0) res[2][44]=a048;
  a025=(a025*a001);
  a026=(a026*a025);
  a054=(a054*a026);
  a067=(a067-a054);
  if (res[2]!=0) res[2][45]=a067;
  a044=(a044+a086);
  if (res[2]!=0) res[2][46]=a044;
  if (res[2]!=0) res[2][47]=a003;
  a042=(a037*a042);
  a042=(a071*a042);
  if (res[2]!=0) res[2][48]=a042;
  a003=(a029*a108);
  a029=(a029*a002);
  a003=(a003-a029);
  if (res[2]!=0) res[2][49]=a003;
  if (res[2]!=0) res[2][50]=a069;
  a029=(a002*a091);
  a086=(a108*a091);
  a029=(a029-a086);
  if (res[2]!=0) res[2][51]=a029;
  a086=(a062*a022);
  a086=(-a086);
  if (res[2]!=0) res[2][52]=a086;
  a002=(a002*a097);
  a108=(a108*a097);
  a002=(a002-a108);
  if (res[2]!=0) res[2][53]=a002;
  a062=(a022*a062);
  if (res[2]!=0) res[2][54]=a062;
  if (res[2]!=0) res[2][55]=a066;
  a089=(a037*a089);
  a089=(a071*a089);
  if (res[2]!=0) res[2][56]=a089;
  if (res[2]!=0) res[2][57]=a069;
  if (res[2]!=0) res[2][58]=a109;
  a058=(a058*a022);
  if (res[2]!=0) res[2][59]=a058;
  a084=(a084*a091);
  a017=(a017*a091);
  a084=(a084-a017);
  if (res[2]!=0) res[2][60]=a084;
  a017=(-a058);
  if (res[2]!=0) res[2][61]=a017;
  a091=(a046*a109);
  a091=(-a091);
  if (res[2]!=0) res[2][62]=a091;
  if (res[2]!=0) res[2][63]=a053;
  if (res[2]!=0) res[2][64]=a042;
  if (res[2]!=0) res[2][65]=a089;
  a089=(a041*a045);
  a042=(a040*a052);
  a089=(a089+a042);
  a089=(a000*a089);
  a042=(a055*a045);
  a053=(a049*a052);
  a042=(a042+a053);
  a042=(a000*a042);
  a089=(a089-a042);
  a042=(a051*a107);
  a053=(a043*a012);
  a042=(a042+a053);
  a006=(a006*a042);
  a089=(a089+a006);
  a089=(a089*a050);
  a089=(a000*a089);
  a051=(a051*a045);
  a043=(a043*a052);
  a051=(a051+a043);
  a041=(a041*a107);
  a051=(a051+a041);
  a055=(a055*a107);
  a049=(a049*a012);
  a055=(a055+a049);
  a051=(a051-a055);
  a040=(a040*a012);
  a051=(a051+a040);
  a051=(a051*a035);
  a051=(a000*a051);
  a089=(a089+a051);
  if (res[2]!=0) res[2][66]=a089;
  a089=(a000*a052);
  a089=(a039*a089);
  a089=(a000*a089);
  a088=(a037*a088);
  a088=(a071*a088);
  a089=(a089-a088);
  a088=(a038*a012);
  a088=(a000*a088);
  a089=(a089+a088);
  if (res[2]!=0) res[2][67]=a089;
  a068=(a068*a010);
  a063=(a063*a010);
  a063=(a068+a063);
  a063=(a063+a047);
  a063=(a063+a056);
  a063=(a063+a074);
  if (res[2]!=0) res[2][68]=a063;
  a074=(a052*a050);
  a056=(a012*a039);
  a074=(a074+a056);
  if (res[2]!=0) res[2][69]=a074;
  a050=(a045*a050);
  a056=(a107*a039);
  a050=(a050+a056);
  if (res[2]!=0) res[2][70]=a050;
  a056=arg[2]? arg[2][13] : 0;
  if (res[2]!=0) res[2][71]=a056;
  a059=(a037*a059);
  a059=(a071*a059);
  a047=(a052*a034);
  a047=(a000*a047);
  a047=(a039*a047);
  a047=(a000*a047);
  a059=(a059-a047);
  a047=(a012*a034);
  a047=(a038*a047);
  a047=(a000*a047);
  a059=(a059-a047);
  if (res[2]!=0) res[2][72]=a059;
  a095=(a037*a095);
  a095=(a071*a095);
  a045=(a045*a034);
  a045=(a000*a045);
  a045=(a039*a045);
  a045=(a000*a045);
  a095=(a095+a045);
  a107=(a107*a034);
  a107=(a038*a107);
  a107=(a000*a107);
  a095=(a095+a107);
  a095=(-a095);
  if (res[2]!=0) res[2][73]=a095;
  a037=(a037*a099);
  a071=(a071*a037);
  a052=(a052*a046);
  a052=(a000*a052);
  a039=(a039*a052);
  a039=(a000*a039);
  a071=(a071-a039);
  a012=(a012*a046);
  a038=(a038*a012);
  a000=(a000*a038);
  a071=(a071-a000);
  if (res[2]!=0) res[2][74]=a071;
  a016=(a046*a016);
  a016=(a016+a068);
  a016=(-a016);
  if (res[2]!=0) res[2][75]=a016;
  if (res[2]!=0) res[2][76]=a115;
  if (res[2]!=0) res[2][77]=a102;
  if (res[2]!=0) res[2][78]=a069;
  if (res[2]!=0) res[2][79]=a072;
  a075=(a023*a075);
  a073=(a023*a073);
  a073=(a075+a073);
  a073=(a073-a114);
  if (res[2]!=0) res[2][80]=a073;
  a081=(a023*a081);
  a081=(a030-a081);
  a079=(a023*a079);
  a081=(a081-a079);
  a081=(-a081);
  if (res[2]!=0) res[2][81]=a081;
  a114=(a011*a114);
  a114=(a114-a075);
  if (res[2]!=0) res[2][82]=a114;
  if (res[2]!=0) res[2][83]=a070;
  if (res[2]!=0) res[2][84]=a069;
  if (res[2]!=0) res[2][85]=a105;
  if (res[2]!=0) res[2][86]=a032;
  if (res[2]!=0) res[2][87]=a073;
  a078=(a023*a078);
  a077=(a023*a077);
  a077=(a078+a077);
  a077=(a113-a077);
  if (res[2]!=0) res[2][88]=a077;
  a085=(a023*a085);
  a023=(a023*a083);
  a083=(a085+a023);
  a083=(a112-a083);
  if (res[2]!=0) res[2][89]=a083;
  if (res[2]!=0) res[2][90]=a110;
  if (res[2]!=0) res[2][91]=a015;
  if (res[2]!=0) res[2][92]=a021;
  if (res[2]!=0) res[2][93]=a116;
  if (res[2]!=0) res[2][94]=a019;
  if (res[2]!=0) res[2][95]=a027;
  if (res[2]!=0) res[2][96]=a028;
  if (res[2]!=0) res[2][97]=a077;
  a079=(a030-a079);
  a030=(a011*a030);
  a079=(a079-a030);
  if (res[2]!=0) res[2][98]=a079;
  a113=(a011*a113);
  a078=(a078-a113);
  if (res[2]!=0) res[2][99]=a078;
  if (res[2]!=0) res[2][100]=a013;
  if (res[2]!=0) res[2][101]=a033;
  if (res[2]!=0) res[2][102]=a104;
  if (res[2]!=0) res[2][103]=a080;
  if (res[2]!=0) res[2][104]=a081;
  if (res[2]!=0) res[2][105]=a079;
  a023=(a023-a112);
  a011=(a011*a112);
  a023=(a023+a011);
  if (res[2]!=0) res[2][106]=a023;
  if (res[2]!=0) res[2][107]=a036;
  if (res[2]!=0) res[2][108]=a065;
  if (res[2]!=0) res[2][109]=a103;
  if (res[2]!=0) res[2][110]=a008;
  if (res[2]!=0) res[2][111]=a083;
  if (res[2]!=0) res[2][112]=a023;
  a085=(a085-a011);
  if (res[2]!=0) res[2][113]=a085;
  if (res[2]!=0) res[2][114]=a009;
  if (res[2]!=0) res[2][115]=a031;
  if (res[2]!=0) res[2][116]=a076;
  if (res[2]!=0) res[2][117]=a111;
  if (res[2]!=0) res[2][118]=a114;
  if (res[2]!=0) res[2][119]=a078;
  if (res[2]!=0) res[2][120]=a085;
  if (res[2]!=0) res[2][121]=a014;
  if (res[2]!=0) res[2][122]=a003;
  if (res[2]!=0) res[2][123]=a069;
  if (res[2]!=0) res[2][124]=a089;
  a090=(a022*a090);
  a060=(a022*a060);
  a060=(a090+a060);
  a060=(a060-a020);
  if (res[2]!=0) res[2][125]=a060;
  a096=(a022*a096);
  a096=(a061-a096);
  a094=(a022*a094);
  a096=(a096-a094);
  a096=(-a096);
  if (res[2]!=0) res[2][126]=a096;
  a020=(a046*a020);
  a020=(a020-a090);
  if (res[2]!=0) res[2][127]=a020;
  if (res[2]!=0) res[2][128]=a087;
  if (res[2]!=0) res[2][129]=a069;
  if (res[2]!=0) res[2][130]=a109;
  if (res[2]!=0) res[2][131]=a063;
  if (res[2]!=0) res[2][132]=a060;
  a093=(a022*a093);
  a092=(a022*a092);
  a092=(a093+a092);
  a092=(a004-a092);
  if (res[2]!=0) res[2][133]=a092;
  a100=(a022*a100);
  a022=(a022*a098);
  a098=(a100+a022);
  a098=(a026-a098);
  if (res[2]!=0) res[2][134]=a098;
  if (res[2]!=0) res[2][135]=a074;
  if (res[2]!=0) res[2][136]=a050;
  if (res[2]!=0) res[2][137]=a056;
  if (res[2]!=0) res[2][138]=a005;
  if (res[2]!=0) res[2][139]=a029;
  if (res[2]!=0) res[2][140]=a058;
  if (res[2]!=0) res[2][141]=a059;
  if (res[2]!=0) res[2][142]=a092;
  a094=(a061-a094);
  a061=(a046*a061);
  a094=(a094-a061);
  if (res[2]!=0) res[2][143]=a094;
  a004=(a046*a004);
  a093=(a093-a004);
  if (res[2]!=0) res[2][144]=a093;
  if (res[2]!=0) res[2][145]=a048;
  if (res[2]!=0) res[2][146]=a086;
  if (res[2]!=0) res[2][147]=a084;
  if (res[2]!=0) res[2][148]=a095;
  if (res[2]!=0) res[2][149]=a096;
  if (res[2]!=0) res[2][150]=a094;
  a022=(a022-a026);
  a046=(a046*a026);
  a022=(a022+a046);
  if (res[2]!=0) res[2][151]=a022;
  if (res[2]!=0) res[2][152]=a067;
  if (res[2]!=0) res[2][153]=a002;
  if (res[2]!=0) res[2][154]=a017;
  if (res[2]!=0) res[2][155]=a071;
  if (res[2]!=0) res[2][156]=a098;
  if (res[2]!=0) res[2][157]=a022;
  a100=(a100-a046);
  if (res[2]!=0) res[2][158]=a100;
  if (res[2]!=0) res[2][159]=a044;
  if (res[2]!=0) res[2][160]=a062;
  if (res[2]!=0) res[2][161]=a091;
  if (res[2]!=0) res[2][162]=a016;
  if (res[2]!=0) res[2][163]=a020;
  if (res[2]!=0) res[2][164]=a093;
  if (res[2]!=0) res[2][165]=a100;
  return 0;
}

CASADI_SYMBOL_EXPORT int lipm_opti_pessi_dyn_disc_phi_fun_jac_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int lipm_opti_pessi_dyn_disc_phi_fun_jac_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int lipm_opti_pessi_dyn_disc_phi_fun_jac_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void lipm_opti_pessi_dyn_disc_phi_fun_jac_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int lipm_opti_pessi_dyn_disc_phi_fun_jac_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void lipm_opti_pessi_dyn_disc_phi_fun_jac_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void lipm_opti_pessi_dyn_disc_phi_fun_jac_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void lipm_opti_pessi_dyn_disc_phi_fun_jac_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int lipm_opti_pessi_dyn_disc_phi_fun_jac_hess_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int lipm_opti_pessi_dyn_disc_phi_fun_jac_hess_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real lipm_opti_pessi_dyn_disc_phi_fun_jac_hess_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* lipm_opti_pessi_dyn_disc_phi_fun_jac_hess_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* lipm_opti_pessi_dyn_disc_phi_fun_jac_hess_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* lipm_opti_pessi_dyn_disc_phi_fun_jac_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s0;
    case 3: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* lipm_opti_pessi_dyn_disc_phi_fun_jac_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s2;
    case 2: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int lipm_opti_pessi_dyn_disc_phi_fun_jac_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int lipm_opti_pessi_dyn_disc_phi_fun_jac_hess_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
