/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) phase_lipm_one_dyn_disc_phi_fun_jac_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[3] = {11, 1, 1};
static const casadi_int casadi_s1[3] = {13, 1, 1};
static const casadi_int casadi_s2[3] = {17, 1, 1};
static const casadi_int casadi_s3[51] = 
  {24, 11, 0, 5, 10, 12, 17, 22,
  32, 33, 34, 35, 36, 37, 4, 13,
  16, 19, 21, 4, 14, 17, 20, 22,
  15, 18, 4, 13, 16, 19, 21, 4,
  14, 17, 20, 22, 4, 5, 6, 13,
  14, 18, 19, 20, 21, 22, 0, 1,
  2, 3, 23};
static const casadi_int casadi_s4[85] = 
  {24, 24, 0, 0, 0, 0, 0, 8,
  15, 22, 22, 22, 22, 22, 22, 22,
  28, 34, 34, 34, 34, 34, 40, 46,
  52, 58, 58, 5, 6, 13, 14, 19,
  20, 21, 22, 4, 13, 14, 19, 20,
  21, 22, 4, 13, 14, 19, 20, 21,
  22, 4, 5, 6, 14, 20, 22, 4,
  5, 6, 13, 19, 21, 4, 5, 6,
  14, 20, 22, 4, 5, 6, 13, 19,
  21, 4, 5, 6, 14, 20, 22, 4,
  5, 6, 13, 19, 21};

/* phase_lipm_one_dyn_disc_phi_fun_jac_hess:(i0[11],i1[13],i2[11],i3[17])->(o0[11],o1[24x11,37nz],o2[24x24,58nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39, a40, a41;
  a00=1.0324436666324333e+00;
  a01=arg[0]? arg[0][0] : 0;
  a02=(a00*a01);
  a03=5.0539567176575435e-02;
  a04=arg[0]? arg[0][3] : 0;
  a05=(a03*a04);
  a02=(a02+a05);
  a05=-3.2443666632433255e-02;
  a06=1.;
  a07=arg[1]? arg[1][4] : 0;
  a08=(a06-a07);
  a09=arg[0]? arg[0][6] : 0;
  a10=(a08*a09);
  a11=arg[0]? arg[0][8] : 0;
  a12=(a07*a11);
  a10=(a10+a12);
  a12=(a05*a10);
  a02=(a02+a12);
  if (res[0]!=0) res[0][0]=a02;
  a02=arg[0]? arg[0][1] : 0;
  a12=(a00*a02);
  a13=arg[0]? arg[0][4] : 0;
  a14=(a03*a13);
  a12=(a12+a14);
  a14=arg[0]? arg[0][7] : 0;
  a15=(a08*a14);
  a16=arg[0]? arg[0][9] : 0;
  a17=(a07*a16);
  a15=(a15+a17);
  a17=(a05*a15);
  a12=(a12+a17);
  if (res[0]!=0) res[0][1]=a12;
  a12=arg[0]? arg[0][2] : 0;
  a17=5.0000000000000003e-02;
  a18=arg[0]? arg[0][5] : 0;
  a19=(a17*a18);
  a12=(a12+a19);
  if (res[0]!=0) res[0][2]=a12;
  a12=1.3047188263215921e+00;
  a10=(a01-a10);
  a19=(a12*a10);
  a04=(a00*a04);
  a19=(a19+a04);
  if (res[0]!=0) res[0][3]=a19;
  a15=(a02-a15);
  a19=(a12*a15);
  a13=(a00*a13);
  a19=(a19+a13);
  if (res[0]!=0) res[0][4]=a19;
  a19=(a09-a01);
  a13=arg[1]? arg[1][6] : 0;
  a04=2.4239999999999998e+01;
  a20=2.5815789473684209e+01;
  a15=(a20*a15);
  a15=(a04*a15);
  a21=(a13*a15);
  a22=(a19*a21);
  a23=(a14-a02);
  a24=arg[1]? arg[1][5] : 0;
  a10=(a20*a10);
  a10=(a04*a10);
  a25=(a24*a10);
  a26=(a23*a25);
  a22=(a22-a26);
  a01=(a11-a01);
  a26=(a15-a21);
  a27=(a01*a26);
  a02=(a16-a02);
  a28=(a10-a25);
  a29=(a02*a28);
  a27=(a27-a29);
  a22=(a22+a27);
  a22=(a17*a22);
  a27=1.0480000000000000e+00;
  a22=(a22/a27);
  a18=(a18+a22);
  if (res[0]!=0) res[0][5]=a18;
  a18=arg[1]? arg[1][0] : 0;
  if (res[0]!=0) res[0][6]=a18;
  a18=arg[1]? arg[1][1] : 0;
  if (res[0]!=0) res[0][7]=a18;
  a18=arg[1]? arg[1][2] : 0;
  if (res[0]!=0) res[0][8]=a18;
  a18=arg[1]? arg[1][3] : 0;
  if (res[0]!=0) res[0][9]=a18;
  a18=arg[0]? arg[0][10] : 0;
  a18=(a18+a17);
  if (res[0]!=0) res[0][10]=a18;
  a18=(a11-a09);
  a22=(a05*a18);
  if (res[1]!=0) res[1][0]=a22;
  if (res[1]!=0) res[1][1]=a00;
  if (res[1]!=0) res[1][2]=a03;
  a22=(a05*a08);
  if (res[1]!=0) res[1][3]=a22;
  a27=(a05*a07);
  if (res[1]!=0) res[1][4]=a27;
  a29=(a16-a14);
  a30=(a05*a29);
  if (res[1]!=0) res[1][5]=a30;
  if (res[1]!=0) res[1][6]=a00;
  if (res[1]!=0) res[1][7]=a03;
  if (res[1]!=0) res[1][8]=a22;
  if (res[1]!=0) res[1][9]=a27;
  if (res[1]!=0) res[1][10]=a06;
  if (res[1]!=0) res[1][11]=a17;
  a27=(a12*a18);
  a27=(-a27);
  if (res[1]!=0) res[1][12]=a27;
  if (res[1]!=0) res[1][13]=a12;
  if (res[1]!=0) res[1][14]=a00;
  a27=(a12*a08);
  a27=(-a27);
  if (res[1]!=0) res[1][15]=a27;
  a22=(a12*a07);
  a22=(-a22);
  if (res[1]!=0) res[1][16]=a22;
  a03=(a12*a29);
  a03=(-a03);
  if (res[1]!=0) res[1][17]=a03;
  if (res[1]!=0) res[1][18]=a12;
  if (res[1]!=0) res[1][19]=a00;
  if (res[1]!=0) res[1][20]=a27;
  if (res[1]!=0) res[1][21]=a22;
  a22=9.5419847328244267e-01;
  a18=(a20*a18);
  a18=(a04*a18);
  a27=(a24*a18);
  a00=(a23*a27);
  a29=(a20*a29);
  a29=(a04*a29);
  a03=(a13*a29);
  a30=(a19*a03);
  a00=(a00-a30);
  a03=(a03-a29);
  a03=(a01*a03);
  a18=(a27-a18);
  a29=(a02*a18);
  a03=(a03-a29);
  a00=(a00+a03);
  a00=(a17*a00);
  a00=(a22*a00);
  if (res[1]!=0) res[1][22]=a00;
  a00=(a02*a10);
  a03=(a23*a10);
  a00=(a00-a03);
  a00=(a17*a00);
  a00=(a22*a00);
  if (res[1]!=0) res[1][23]=a00;
  a00=(a19*a15);
  a03=(a01*a15);
  a00=(a00-a03);
  a00=(a17*a00);
  a00=(a22*a00);
  if (res[1]!=0) res[1][24]=a00;
  a00=6.2577473684210520e+02;
  a03=(a00*a24);
  a29=(a23*a03);
  a29=(a21+a29);
  a30=(a00-a03);
  a31=(a02*a30);
  a31=(a26+a31);
  a29=(a29+a31);
  a29=(a17*a29);
  a29=(a22*a29);
  a29=(-a29);
  if (res[1]!=0) res[1][25]=a29;
  a29=(a00*a13);
  a31=(a19*a29);
  a31=(a31+a25);
  a29=(a00-a29);
  a29=(a01*a29);
  a29=(a29+a28);
  a31=(a31+a29);
  a31=(a17*a31);
  a31=(a22*a31);
  if (res[1]!=0) res[1][26]=a31;
  if (res[1]!=0) res[1][27]=a06;
  a31=(a20*a08);
  a31=(a04*a31);
  a29=(a24*a31);
  a32=(a23*a29);
  a21=(a21+a32);
  a32=(a29-a31);
  a33=(a02*a32);
  a21=(a21-a33);
  a21=(a17*a21);
  a21=(a22*a21);
  if (res[1]!=0) res[1][28]=a21;
  a21=(a13*a31);
  a33=(a21-a31);
  a34=(a01*a33);
  a35=(a19*a21);
  a35=(a35+a25);
  a34=(a34-a35);
  a34=(a17*a34);
  a34=(a22*a34);
  if (res[1]!=0) res[1][29]=a34;
  a34=(a20*a07);
  a34=(a04*a34);
  a35=(a24*a34);
  a25=(a23*a35);
  a36=(a35-a34);
  a37=(a02*a36);
  a26=(a26-a37);
  a25=(a25+a26);
  a25=(a17*a25);
  a25=(a22*a25);
  if (res[1]!=0) res[1][30]=a25;
  a25=(a13*a34);
  a26=(a25-a34);
  a26=(a01*a26);
  a26=(a26-a28);
  a25=(a19*a25);
  a26=(a26-a25);
  a26=(a17*a26);
  a26=(a22*a26);
  if (res[1]!=0) res[1][31]=a26;
  if (res[1]!=0) res[1][32]=a06;
  if (res[1]!=0) res[1][33]=a06;
  if (res[1]!=0) res[1][34]=a06;
  if (res[1]!=0) res[1][35]=a06;
  if (res[1]!=0) res[1][36]=a06;
  a06=arg[2]? arg[2][5] : 0;
  a22=(a22*a06);
  a17=(a17*a22);
  a02=(a02*a17);
  a23=(a23*a17);
  a23=(a02-a23);
  a22=(a04*a23);
  a22=(a20*a22);
  a06=(a09*a22);
  a22=(a11*a22);
  a06=(a06-a22);
  if (res[2]!=0) res[2][0]=a06;
  a19=(a19*a17);
  a01=(a01*a17);
  a19=(a19-a01);
  a22=(a04*a19);
  a22=(a20*a22);
  a26=(a14*a22);
  a25=(a16*a22);
  a26=(a26-a25);
  if (res[2]!=0) res[2][1]=a26;
  a25=(a04*a17);
  a25=(a20*a25);
  a28=(a16*a25);
  a37=(a14*a25);
  a28=(a28-a37);
  if (res[2]!=0) res[2][2]=a28;
  a18=(a17*a18);
  a27=(a17*a27);
  a27=(a18-a27);
  if (res[2]!=0) res[2][3]=a27;
  a37=(a13*a17);
  a38=(a04*a37);
  a38=(a20*a38);
  a39=(a16*a38);
  a40=arg[2]? arg[2][0] : 0;
  a40=(a05*a40);
  a41=(a24*a23);
  a41=(a41-a02);
  a41=(a04*a41);
  a41=(a20*a41);
  a02=arg[2]? arg[2][3] : 0;
  a02=(a12*a02);
  a41=(a41+a02);
  a40=(a40-a41);
  a41=(a14*a38);
  a41=(a40-a41);
  a39=(a39+a41);
  a39=(-a39);
  if (res[2]!=0) res[2][4]=a39;
  a24=(a24*a17);
  a24=(a04*a24);
  a24=(a20*a24);
  a11=(a11*a24);
  a41=arg[2]? arg[2][1] : 0;
  a05=(a05*a41);
  a13=(a13*a19);
  a01=(a01+a13);
  a01=(a04*a01);
  a01=(a20*a01);
  a13=arg[2]? arg[2][4] : 0;
  a12=(a12*a13);
  a01=(a01+a12);
  a05=(a05-a01);
  a09=(a09*a24);
  a09=(a05+a09);
  a11=(a11-a09);
  if (res[2]!=0) res[2][5]=a11;
  a37=(a17-a37);
  a04=(a04*a37);
  a20=(a20*a04);
  a16=(a16*a20);
  a40=(a40-a16);
  a14=(a14*a20);
  a40=(a40+a14);
  if (res[2]!=0) res[2][6]=a40;
  a05=(a05-a18);
  if (res[2]!=0) res[2][7]=a05;
  if (res[2]!=0) res[2][8]=a06;
  a00=(a00*a23);
  if (res[2]!=0) res[2][9]=a00;
  a06=0.;
  if (res[2]!=0) res[2][10]=a06;
  a18=(a23*a31);
  a18=(-a18);
  if (res[2]!=0) res[2][11]=a18;
  a14=(a10*a17);
  a14=(-a14);
  if (res[2]!=0) res[2][12]=a14;
  a23=(a23*a34);
  a23=(-a23);
  if (res[2]!=0) res[2][13]=a23;
  a10=(a17*a10);
  if (res[2]!=0) res[2][14]=a10;
  if (res[2]!=0) res[2][15]=a26;
  if (res[2]!=0) res[2][16]=a06;
  if (res[2]!=0) res[2][17]=a22;
  a15=(a15*a17);
  if (res[2]!=0) res[2][18]=a15;
  a19=(a19*a31);
  a19=(-a19);
  if (res[2]!=0) res[2][19]=a19;
  a31=(-a15);
  if (res[2]!=0) res[2][20]=a31;
  a26=(a07*a22);
  a26=(-a26);
  if (res[2]!=0) res[2][21]=a26;
  if (res[2]!=0) res[2][22]=a28;
  if (res[2]!=0) res[2][23]=a00;
  if (res[2]!=0) res[2][24]=a06;
  a30=(a17*a30);
  a03=(a17*a03);
  a03=(a30+a03);
  a03=(a03-a25);
  if (res[2]!=0) res[2][25]=a03;
  a21=(a17*a21);
  a33=(a17*a33);
  a33=(a24+a33);
  a33=(a21-a33);
  if (res[2]!=0) res[2][26]=a33;
  a25=(a07*a25);
  a25=(a25-a30);
  if (res[2]!=0) res[2][27]=a25;
  if (res[2]!=0) res[2][28]=a27;
  if (res[2]!=0) res[2][29]=a06;
  if (res[2]!=0) res[2][30]=a22;
  if (res[2]!=0) res[2][31]=a03;
  a32=(a17*a32);
  a29=(a17*a29);
  a29=(a32-a29);
  a29=(a29+a38);
  if (res[2]!=0) res[2][32]=a29;
  a36=(a17*a36);
  a17=(a17*a35);
  a35=(a36-a17);
  a35=(a35+a20);
  if (res[2]!=0) res[2][33]=a35;
  if (res[2]!=0) res[2][34]=a39;
  if (res[2]!=0) res[2][35]=a18;
  if (res[2]!=0) res[2][36]=a15;
  if (res[2]!=0) res[2][37]=a29;
  a24=(a08*a24);
  a24=(a24-a21);
  if (res[2]!=0) res[2][38]=a24;
  a38=(a07*a38);
  a38=(a38+a32);
  a38=(-a38);
  if (res[2]!=0) res[2][39]=a38;
  if (res[2]!=0) res[2][40]=a11;
  if (res[2]!=0) res[2][41]=a14;
  if (res[2]!=0) res[2][42]=a19;
  if (res[2]!=0) res[2][43]=a33;
  if (res[2]!=0) res[2][44]=a24;
  a08=(a08*a20);
  a17=(a17-a08);
  if (res[2]!=0) res[2][45]=a17;
  if (res[2]!=0) res[2][46]=a40;
  if (res[2]!=0) res[2][47]=a23;
  if (res[2]!=0) res[2][48]=a31;
  if (res[2]!=0) res[2][49]=a35;
  if (res[2]!=0) res[2][50]=a17;
  a07=(a07*a20);
  a07=(a07+a36);
  a07=(-a07);
  if (res[2]!=0) res[2][51]=a07;
  if (res[2]!=0) res[2][52]=a05;
  if (res[2]!=0) res[2][53]=a10;
  if (res[2]!=0) res[2][54]=a26;
  if (res[2]!=0) res[2][55]=a25;
  if (res[2]!=0) res[2][56]=a38;
  if (res[2]!=0) res[2][57]=a07;
  return 0;
}

CASADI_SYMBOL_EXPORT int phase_lipm_one_dyn_disc_phi_fun_jac_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int phase_lipm_one_dyn_disc_phi_fun_jac_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int phase_lipm_one_dyn_disc_phi_fun_jac_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void phase_lipm_one_dyn_disc_phi_fun_jac_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int phase_lipm_one_dyn_disc_phi_fun_jac_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void phase_lipm_one_dyn_disc_phi_fun_jac_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void phase_lipm_one_dyn_disc_phi_fun_jac_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void phase_lipm_one_dyn_disc_phi_fun_jac_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int phase_lipm_one_dyn_disc_phi_fun_jac_hess_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int phase_lipm_one_dyn_disc_phi_fun_jac_hess_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real phase_lipm_one_dyn_disc_phi_fun_jac_hess_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* phase_lipm_one_dyn_disc_phi_fun_jac_hess_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* phase_lipm_one_dyn_disc_phi_fun_jac_hess_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* phase_lipm_one_dyn_disc_phi_fun_jac_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s0;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* phase_lipm_one_dyn_disc_phi_fun_jac_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s3;
    case 2: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int phase_lipm_one_dyn_disc_phi_fun_jac_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int phase_lipm_one_dyn_disc_phi_fun_jac_hess_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
