/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) phase_lipm_one_dyn_disc_phi_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[3] = {11, 1, 1};
static const casadi_int casadi_s1[3] = {13, 1, 1};
static const casadi_int casadi_s2[3] = {17, 1, 1};

/* phase_lipm_one_dyn_disc_phi_fun:(i0[11],i1[13],i2[17])->(o0[11]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14;
  a00=1.0324436666324333e+00;
  a01=arg[0]? arg[0][0] : 0;
  a02=(a00*a01);
  a03=5.0539567176575435e-02;
  a04=arg[0]? arg[0][3] : 0;
  a05=(a03*a04);
  a02=(a02+a05);
  a05=-3.2443666632433255e-02;
  a06=1.;
  a07=arg[1]? arg[1][4] : 0;
  a06=(a06-a07);
  a08=arg[0]? arg[0][6] : 0;
  a09=(a06*a08);
  a10=arg[0]? arg[0][8] : 0;
  a11=(a07*a10);
  a09=(a09+a11);
  a11=(a05*a09);
  a02=(a02+a11);
  if (res[0]!=0) res[0][0]=a02;
  a02=arg[0]? arg[0][1] : 0;
  a11=(a00*a02);
  a12=arg[0]? arg[0][4] : 0;
  a03=(a03*a12);
  a11=(a11+a03);
  a03=arg[0]? arg[0][7] : 0;
  a06=(a06*a03);
  a13=arg[0]? arg[0][9] : 0;
  a07=(a07*a13);
  a06=(a06+a07);
  a05=(a05*a06);
  a11=(a11+a05);
  if (res[0]!=0) res[0][1]=a11;
  a11=arg[0]? arg[0][2] : 0;
  a05=5.0000000000000003e-02;
  a07=arg[0]? arg[0][5] : 0;
  a14=(a05*a07);
  a11=(a11+a14);
  if (res[0]!=0) res[0][2]=a11;
  a11=1.3047188263215921e+00;
  a09=(a01-a09);
  a14=(a11*a09);
  a04=(a00*a04);
  a14=(a14+a04);
  if (res[0]!=0) res[0][3]=a14;
  a06=(a02-a06);
  a11=(a11*a06);
  a00=(a00*a12);
  a11=(a11+a00);
  if (res[0]!=0) res[0][4]=a11;
  a08=(a08-a01);
  a11=arg[1]? arg[1][6] : 0;
  a00=2.4239999999999998e+01;
  a12=2.5815789473684209e+01;
  a06=(a12*a06);
  a06=(a00*a06);
  a11=(a11*a06);
  a08=(a08*a11);
  a03=(a03-a02);
  a14=arg[1]? arg[1][5] : 0;
  a12=(a12*a09);
  a00=(a00*a12);
  a14=(a14*a00);
  a03=(a03*a14);
  a08=(a08-a03);
  a10=(a10-a01);
  a06=(a06-a11);
  a10=(a10*a06);
  a13=(a13-a02);
  a00=(a00-a14);
  a13=(a13*a00);
  a10=(a10-a13);
  a08=(a08+a10);
  a08=(a05*a08);
  a10=1.0480000000000000e+00;
  a08=(a08/a10);
  a07=(a07+a08);
  if (res[0]!=0) res[0][5]=a07;
  a07=arg[1]? arg[1][0] : 0;
  if (res[0]!=0) res[0][6]=a07;
  a07=arg[1]? arg[1][1] : 0;
  if (res[0]!=0) res[0][7]=a07;
  a07=arg[1]? arg[1][2] : 0;
  if (res[0]!=0) res[0][8]=a07;
  a07=arg[1]? arg[1][3] : 0;
  if (res[0]!=0) res[0][9]=a07;
  a07=arg[0]? arg[0][10] : 0;
  a07=(a07+a05);
  if (res[0]!=0) res[0][10]=a07;
  return 0;
}

CASADI_SYMBOL_EXPORT int phase_lipm_one_dyn_disc_phi_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int phase_lipm_one_dyn_disc_phi_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int phase_lipm_one_dyn_disc_phi_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void phase_lipm_one_dyn_disc_phi_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int phase_lipm_one_dyn_disc_phi_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void phase_lipm_one_dyn_disc_phi_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void phase_lipm_one_dyn_disc_phi_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void phase_lipm_one_dyn_disc_phi_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int phase_lipm_one_dyn_disc_phi_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int phase_lipm_one_dyn_disc_phi_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real phase_lipm_one_dyn_disc_phi_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* phase_lipm_one_dyn_disc_phi_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* phase_lipm_one_dyn_disc_phi_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* phase_lipm_one_dyn_disc_phi_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* phase_lipm_one_dyn_disc_phi_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int phase_lipm_one_dyn_disc_phi_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int phase_lipm_one_dyn_disc_phi_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
