/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) lipm_step_ca_cost_y_fun_jac_ut_xt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[3] = {11, 1, 1};
static const casadi_int casadi_s1[3] = {0, 1, 1};
static const casadi_int casadi_s2[3] = {0, 0, 1};
static const casadi_int casadi_s3[3] = {8, 1, 1};
static const casadi_int casadi_s4[3] = {19, 1, 1};
static const casadi_int casadi_s5[77] = 
  {22, 19, 0, 1, 2, 3, 4, 5,
  6, 7, 9, 11, 13, 15, 24, 33,
  42, 51, 52, 53, 54, 55, 11, 12,
  13, 14, 15, 16, 21, 0, 17, 1,
  18, 2, 19, 3, 20, 0, 4, 7,
  11, 13, 14, 16, 17, 19, 1, 4,
  7, 12, 13, 15, 16, 18, 20, 2,
  4, 7, 11, 13, 14, 16, 17, 19,
  3, 4, 7, 12, 13, 15, 16, 18,
  20, 4, 5, 6, 7};
static const casadi_int casadi_s6[3] = {19, 0, 1};

/* lipm_step_ca_cost_y_fun_jac_ut_xt:(i0[11],i1[11],i2[0],i3[],i4[8])->(o0[19],o1[22x19,55nz],o2[19x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28;
  a00=arg[0]? arg[0][0] : 0;
  if (res[0]!=0) res[0][0]=a00;
  a01=arg[0]? arg[0][1] : 0;
  if (res[0]!=0) res[0][1]=a01;
  a02=arg[0]? arg[0][2] : 0;
  if (res[0]!=0) res[0][2]=a02;
  a03=arg[0]? arg[0][3] : 0;
  if (res[0]!=0) res[0][3]=a03;
  a04=arg[0]? arg[0][4] : 0;
  if (res[0]!=0) res[0][4]=a04;
  a05=arg[0]? arg[0][5] : 0;
  if (res[0]!=0) res[0][5]=a05;
  a06=arg[0]? arg[0][10] : 0;
  if (res[0]!=0) res[0][6]=a06;
  a06=arg[1]? arg[1][0] : 0;
  a07=arg[0]? arg[0][6] : 0;
  a08=(a06-a07);
  if (res[0]!=0) res[0][7]=a08;
  a08=arg[1]? arg[1][1] : 0;
  a09=arg[0]? arg[0][7] : 0;
  a10=(a08-a09);
  if (res[0]!=0) res[0][8]=a10;
  a10=arg[1]? arg[1][2] : 0;
  a11=arg[0]? arg[0][8] : 0;
  a12=(a10-a11);
  if (res[0]!=0) res[0][9]=a12;
  a12=arg[1]? arg[1][3] : 0;
  a13=arg[0]? arg[0][9] : 0;
  a14=(a12-a13);
  if (res[0]!=0) res[0][10]=a14;
  a14=5.0809240767486585e+00;
  a15=arg[1]? arg[1][7] : 0;
  a16=(a14*a15);
  a17=cosh(a16);
  a18=(a17*a00);
  a16=sinh(a16);
  a19=(a16/a14);
  a20=(a19*a03);
  a18=(a18+a20);
  a20=1.;
  a21=(a20-a17);
  a22=arg[1]? arg[1][4] : 0;
  a11=(a11-a07);
  a23=(a22*a11);
  a07=(a07+a23);
  a23=(a21*a07);
  a18=(a18+a23);
  a23=(a05*a15);
  a02=(a02+a23);
  a23=cos(a02);
  a24=arg[4]? arg[4][0] : 0;
  a25=(a23*a24);
  a02=sin(a02);
  a26=arg[4]? arg[4][1] : 0;
  a27=(a02*a26);
  a25=(a25-a27);
  a25=(a18+a25);
  a06=(a06-a25);
  if (res[0]!=0) res[0][11]=a06;
  a06=(a17*a01);
  a25=(a19*a04);
  a06=(a06+a25);
  a13=(a13-a09);
  a25=(a22*a13);
  a09=(a09+a25);
  a25=(a21*a09);
  a06=(a06+a25);
  a25=(a02*a24);
  a27=(a23*a26);
  a25=(a25+a27);
  a25=(a06+a25);
  a08=(a08-a25);
  if (res[0]!=0) res[0][12]=a08;
  a08=arg[4]? arg[4][2] : 0;
  a25=(a23*a08);
  a27=arg[4]? arg[4][3] : 0;
  a28=(a02*a27);
  a25=(a25-a28);
  a18=(a18+a25);
  a10=(a10-a18);
  if (res[0]!=0) res[0][13]=a10;
  a10=(a02*a08);
  a18=(a23*a27);
  a10=(a10+a18);
  a06=(a06+a10);
  a12=(a12-a06);
  if (res[0]!=0) res[0][14]=a12;
  a12=5.0000000000000000e-01;
  a12=(a22-a12);
  if (res[0]!=0) res[0][15]=a12;
  a12=arg[1]? arg[1][5] : 0;
  if (res[0]!=0) res[0][16]=a12;
  a12=arg[1]? arg[1][6] : 0;
  if (res[0]!=0) res[0][17]=a12;
  a12=6.8750000000000006e-02;
  a12=(a15-a12);
  if (res[0]!=0) res[0][18]=a12;
  if (res[1]!=0) res[1][0]=a20;
  if (res[1]!=0) res[1][1]=a20;
  if (res[1]!=0) res[1][2]=a20;
  if (res[1]!=0) res[1][3]=a20;
  if (res[1]!=0) res[1][4]=a20;
  if (res[1]!=0) res[1][5]=a20;
  if (res[1]!=0) res[1][6]=a20;
  if (res[1]!=0) res[1][7]=a20;
  a12=-1.;
  if (res[1]!=0) res[1][8]=a12;
  if (res[1]!=0) res[1][9]=a20;
  if (res[1]!=0) res[1][10]=a12;
  if (res[1]!=0) res[1][11]=a20;
  if (res[1]!=0) res[1][12]=a12;
  if (res[1]!=0) res[1][13]=a20;
  if (res[1]!=0) res[1][14]=a12;
  if (res[1]!=0) res[1][15]=a20;
  a11=(a21*a11);
  a11=(-a11);
  if (res[1]!=0) res[1][16]=a11;
  a14=(a14*a16);
  a00=(a00*a14);
  a03=(a03*a17);
  a00=(a00+a03);
  a07=(a07*a14);
  a00=(a00-a07);
  a07=(a02*a05);
  a03=(a24*a07);
  a05=(a23*a05);
  a16=(a26*a05);
  a03=(a03+a16);
  a03=(a00-a03);
  a03=(-a03);
  if (res[1]!=0) res[1][17]=a03;
  a03=(-a17);
  if (res[1]!=0) res[1][18]=a03;
  a16=(a24*a02);
  a12=(a26*a23);
  a16=(a16+a12);
  if (res[1]!=0) res[1][19]=a16;
  a19=(-a19);
  if (res[1]!=0) res[1][20]=a19;
  a16=(a02*a15);
  a12=(a24*a16);
  a15=(a23*a15);
  a06=(a26*a15);
  a12=(a12+a06);
  if (res[1]!=0) res[1][21]=a12;
  a12=(a20-a22);
  a12=(a21*a12);
  a12=(-a12);
  if (res[1]!=0) res[1][22]=a12;
  a22=(a21*a22);
  a22=(-a22);
  if (res[1]!=0) res[1][23]=a22;
  if (res[1]!=0) res[1][24]=a20;
  a21=(a21*a13);
  a21=(-a21);
  if (res[1]!=0) res[1][25]=a21;
  a01=(a01*a14);
  a04=(a04*a17);
  a01=(a01+a04);
  a09=(a09*a14);
  a01=(a01-a09);
  a09=(a24*a05);
  a14=(a26*a07);
  a09=(a09-a14);
  a09=(a01+a09);
  a09=(-a09);
  if (res[1]!=0) res[1][26]=a09;
  if (res[1]!=0) res[1][27]=a03;
  a09=(a24*a23);
  a14=(a26*a02);
  a09=(a09-a14);
  a09=(-a09);
  if (res[1]!=0) res[1][28]=a09;
  if (res[1]!=0) res[1][29]=a19;
  a24=(a24*a15);
  a26=(a26*a16);
  a24=(a24-a26);
  a24=(-a24);
  if (res[1]!=0) res[1][30]=a24;
  if (res[1]!=0) res[1][31]=a12;
  if (res[1]!=0) res[1][32]=a22;
  if (res[1]!=0) res[1][33]=a20;
  if (res[1]!=0) res[1][34]=a11;
  a11=(a08*a07);
  a24=(a27*a05);
  a11=(a11+a24);
  a00=(a00-a11);
  a00=(-a00);
  if (res[1]!=0) res[1][35]=a00;
  if (res[1]!=0) res[1][36]=a03;
  a00=(a08*a02);
  a11=(a27*a23);
  a00=(a00+a11);
  if (res[1]!=0) res[1][37]=a00;
  if (res[1]!=0) res[1][38]=a19;
  a00=(a08*a16);
  a11=(a27*a15);
  a00=(a00+a11);
  if (res[1]!=0) res[1][39]=a00;
  if (res[1]!=0) res[1][40]=a12;
  if (res[1]!=0) res[1][41]=a22;
  if (res[1]!=0) res[1][42]=a20;
  if (res[1]!=0) res[1][43]=a21;
  a05=(a08*a05);
  a07=(a27*a07);
  a05=(a05-a07);
  a01=(a01+a05);
  a01=(-a01);
  if (res[1]!=0) res[1][44]=a01;
  if (res[1]!=0) res[1][45]=a03;
  a23=(a08*a23);
  a02=(a27*a02);
  a23=(a23-a02);
  a23=(-a23);
  if (res[1]!=0) res[1][46]=a23;
  if (res[1]!=0) res[1][47]=a19;
  a08=(a08*a15);
  a27=(a27*a16);
  a08=(a08-a27);
  a08=(-a08);
  if (res[1]!=0) res[1][48]=a08;
  if (res[1]!=0) res[1][49]=a12;
  if (res[1]!=0) res[1][50]=a22;
  if (res[1]!=0) res[1][51]=a20;
  if (res[1]!=0) res[1][52]=a20;
  if (res[1]!=0) res[1][53]=a20;
  if (res[1]!=0) res[1][54]=a20;
  return 0;
}

CASADI_SYMBOL_EXPORT int lipm_step_ca_cost_y_fun_jac_ut_xt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int lipm_step_ca_cost_y_fun_jac_ut_xt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int lipm_step_ca_cost_y_fun_jac_ut_xt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void lipm_step_ca_cost_y_fun_jac_ut_xt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int lipm_step_ca_cost_y_fun_jac_ut_xt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void lipm_step_ca_cost_y_fun_jac_ut_xt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void lipm_step_ca_cost_y_fun_jac_ut_xt_incref(void) {
}

CASADI_SYMBOL_EXPORT void lipm_step_ca_cost_y_fun_jac_ut_xt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int lipm_step_ca_cost_y_fun_jac_ut_xt_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int lipm_step_ca_cost_y_fun_jac_ut_xt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real lipm_step_ca_cost_y_fun_jac_ut_xt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* lipm_step_ca_cost_y_fun_jac_ut_xt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* lipm_step_ca_cost_y_fun_jac_ut_xt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* lipm_step_ca_cost_y_fun_jac_ut_xt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    case 4: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* lipm_step_ca_cost_y_fun_jac_ut_xt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    case 2: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int lipm_step_ca_cost_y_fun_jac_ut_xt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int lipm_step_ca_cost_y_fun_jac_ut_xt_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
