/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) lipm_step_ca_cost_y_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[3] = {11, 1, 1};
static const casadi_int casadi_s1[3] = {0, 1, 1};
static const casadi_int casadi_s2[3] = {19, 1, 1};
static const casadi_int casadi_s3[3] = {0, 0, 1};
static const casadi_int casadi_s4[3] = {8, 1, 1};
static const casadi_int casadi_s5[60] = 
  {22, 22, 0, 0, 0, 0, 0, 5,
  5, 5, 17, 17, 17, 17, 18, 19,
  22, 23, 24, 27, 29, 31, 33, 35,
  35, 7, 17, 18, 19, 20, 4, 7,
  11, 12, 13, 14, 15, 16, 17, 18,
  19, 20, 7, 7, 7, 13, 16, 7,
  7, 7, 13, 16, 4, 7, 4, 7,
  4, 7, 4, 7};

/* lipm_step_ca_cost_y_hess:(i0[11],i1[11],i2[0],i3[19],i4[],i5[8])->(o0[22x22,35nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30;
  a00=arg[0]? arg[0][9] : 0;
  a01=arg[0]? arg[0][7] : 0;
  a00=(a00-a01);
  a02=arg[3]? arg[3][14] : 0;
  a03=arg[3]? arg[3][12] : 0;
  a04=(a02+a03);
  a05=5.0809240767486585e+00;
  a06=arg[1]? arg[1][7] : 0;
  a07=(a05*a06);
  a08=sinh(a07);
  a08=(a05*a08);
  a09=(a04*a08);
  a10=(a00*a09);
  a11=arg[0]? arg[0][8] : 0;
  a12=arg[0]? arg[0][6] : 0;
  a11=(a11-a12);
  a13=arg[3]? arg[3][13] : 0;
  a14=arg[3]? arg[3][11] : 0;
  a15=(a13+a14);
  a16=(a15*a08);
  a17=(a11*a16);
  a10=(a10+a17);
  if (res[0]!=0) res[0][0]=a10;
  a17=1.;
  a07=cosh(a07);
  a17=(a17-a07);
  a18=(a17*a15);
  if (res[0]!=0) res[0][1]=a18;
  a17=(a17*a04);
  if (res[0]!=0) res[0][2]=a17;
  a19=(-a18);
  if (res[0]!=0) res[0][3]=a19;
  a20=(-a17);
  if (res[0]!=0) res[0][4]=a20;
  if (res[0]!=0) res[0][5]=a10;
  a10=arg[0]? arg[0][5] : 0;
  a21=arg[5]? arg[5][3] : 0;
  a22=(a21*a02);
  a23=arg[5]? arg[5][1] : 0;
  a24=(a23*a03);
  a22=(a22+a24);
  a24=arg[0]? arg[0][2] : 0;
  a25=(a10*a06);
  a24=(a24+a25);
  a25=cos(a24);
  a26=(a25*a10);
  a27=(a22*a26);
  a28=arg[5]? arg[5][2] : 0;
  a02=(a28*a02);
  a29=arg[5]? arg[5][0] : 0;
  a03=(a29*a03);
  a02=(a02+a03);
  a24=sin(a24);
  a03=(a24*a10);
  a30=(a02*a03);
  a27=(a27+a30);
  a21=(a21*a13);
  a23=(a23*a14);
  a21=(a21+a23);
  a03=(a21*a03);
  a27=(a27-a03);
  a28=(a28*a13);
  a29=(a29*a14);
  a28=(a28+a29);
  a26=(a28*a26);
  a27=(a27+a26);
  a10=(a10*a27);
  a26=1.9681459216763408e-01;
  a29=arg[0]? arg[0][4] : 0;
  a29=(a29*a04);
  a14=arg[0]? arg[0][3] : 0;
  a14=(a14*a15);
  a29=(a29+a14);
  a26=(a26*a29);
  a26=(a26*a08);
  a26=(a05*a26);
  a10=(a10-a26);
  a26=arg[1]? arg[1][4] : 0;
  a00=(a26*a00);
  a01=(a01+a00);
  a01=(a01*a04);
  a11=(a26*a11);
  a12=(a12+a11);
  a12=(a12*a15);
  a01=(a01+a12);
  a12=arg[0]? arg[0][1] : 0;
  a12=(a12*a04);
  a01=(a01-a12);
  a12=arg[0]? arg[0][0] : 0;
  a12=(a12*a15);
  a01=(a01-a12);
  a12=(a05*a07);
  a01=(a01*a12);
  a05=(a05*a01);
  a10=(a10+a05);
  if (res[0]!=0) res[0][6]=a10;
  a10=(-a16);
  if (res[0]!=0) res[0][7]=a10;
  a05=(-a09);
  if (res[0]!=0) res[0][8]=a05;
  if (res[0]!=0) res[0][9]=a27;
  a15=(a15*a07);
  a15=(-a15);
  if (res[0]!=0) res[0][10]=a15;
  a04=(a04*a07);
  a04=(-a04);
  if (res[0]!=0) res[0][11]=a04;
  a07=(a24*a22);
  a01=(a25*a02);
  a07=(a07-a01);
  a01=(a25*a21);
  a07=(a07+a01);
  a01=(a24*a28);
  a07=(a07+a01);
  a01=(a06*a27);
  a07=(a07+a01);
  if (res[0]!=0) res[0][12]=a07;
  a01=(a26*a16);
  a16=(a16-a01);
  if (res[0]!=0) res[0][13]=a16;
  a26=(a26*a09);
  a09=(a09-a26);
  if (res[0]!=0) res[0][14]=a09;
  if (res[0]!=0) res[0][15]=a01;
  if (res[0]!=0) res[0][16]=a26;
  if (res[0]!=0) res[0][17]=a10;
  if (res[0]!=0) res[0][18]=a05;
  if (res[0]!=0) res[0][19]=a27;
  a27=(a22*a25);
  a05=(a02*a24);
  a27=(a27+a05);
  a05=(a21*a24);
  a27=(a27-a05);
  a05=(a28*a25);
  a27=(a27+a05);
  if (res[0]!=0) res[0][20]=a27;
  a25=(a25*a06);
  a22=(a22*a25);
  a24=(a24*a06);
  a02=(a02*a24);
  a22=(a22+a02);
  a21=(a21*a24);
  a22=(a22-a21);
  a28=(a28*a25);
  a22=(a22+a28);
  if (res[0]!=0) res[0][21]=a22;
  if (res[0]!=0) res[0][22]=a15;
  if (res[0]!=0) res[0][23]=a04;
  if (res[0]!=0) res[0][24]=a07;
  if (res[0]!=0) res[0][25]=a22;
  a06=(a06*a22);
  if (res[0]!=0) res[0][26]=a06;
  if (res[0]!=0) res[0][27]=a18;
  if (res[0]!=0) res[0][28]=a16;
  if (res[0]!=0) res[0][29]=a17;
  if (res[0]!=0) res[0][30]=a09;
  if (res[0]!=0) res[0][31]=a19;
  if (res[0]!=0) res[0][32]=a01;
  if (res[0]!=0) res[0][33]=a20;
  if (res[0]!=0) res[0][34]=a26;
  return 0;
}

CASADI_SYMBOL_EXPORT int lipm_step_ca_cost_y_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int lipm_step_ca_cost_y_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int lipm_step_ca_cost_y_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void lipm_step_ca_cost_y_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int lipm_step_ca_cost_y_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void lipm_step_ca_cost_y_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void lipm_step_ca_cost_y_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void lipm_step_ca_cost_y_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int lipm_step_ca_cost_y_hess_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int lipm_step_ca_cost_y_hess_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real lipm_step_ca_cost_y_hess_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* lipm_step_ca_cost_y_hess_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* lipm_step_ca_cost_y_hess_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* lipm_step_ca_cost_y_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    case 4: return casadi_s3;
    case 5: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* lipm_step_ca_cost_y_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int lipm_step_ca_cost_y_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int lipm_step_ca_cost_y_hess_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
