/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) lipm_step_ca_constr_h_fun_jac_uxt_zt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {11, 1, 1};
static const casadi_int casadi_s1[3] = {0, 1, 1};
static const casadi_int casadi_s2[3] = {8, 1, 1};
static const casadi_int casadi_s3[3] = {14, 1, 1};
static const casadi_int casadi_s4[164] = 
  {22, 14, 0, 12, 24, 38, 52, 61,
  70, 72, 87, 102, 117, 132, 137, 142,
  147, 4, 7, 11, 12, 13, 14, 15,
  16, 17, 18, 19, 20, 4, 7, 11,
  12, 13, 14, 15, 16, 17, 18, 19,
  20, 0, 1, 4, 7, 11, 12, 13,
  14, 15, 16, 17, 18, 19, 20, 2,
  3, 4, 7, 11, 12, 13, 14, 15,
  16, 17, 18, 19, 20, 4, 5, 6,
  11, 12, 17, 18, 19, 20, 4, 5,
  6, 11, 12, 17, 18, 19, 20, 8,
  9, 4, 7, 8, 9, 10, 11, 12,
  13, 14, 15, 16, 17, 18, 19, 20,
  4, 7, 8, 9, 10, 11, 12, 13,
  14, 15, 16, 17, 18, 19, 20, 4,
  7, 8, 9, 10, 11, 12, 13, 14,
  15, 16, 17, 18, 19, 20, 4, 7,
  8, 9, 10, 11, 12, 13, 14, 15,
  16, 17, 18, 19, 20, 0, 1, 8,
  9, 10, 2, 3, 8, 9, 10, 7,
  8, 9, 10, 21};
static const casadi_int casadi_s5[3] = {14, 0, 1};

/* lipm_step_ca_constr_h_fun_jac_uxt_zt:(i0[11],i1[11],i2[0],i3[8])->(o0[14],o1[22x14,147nz],o2[14x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39, a40, a41, a42, a43, a44, a45, a46, a47;
  casadi_real a48, a49, a50, a51, a52, a53, a54, a55, a56, a57, a58, a59;
  casadi_real a60, a61, a62, a63, a64, a65, a66, a67, a68, a69, a70, a71;
  a00=arg[0]? arg[0][6] : 0;
  a01=5.0809240767486585e+00;
  a02=arg[1]? arg[1][7] : 0;
  a03=(a01*a02);
  a04=cosh(a03);
  a05=arg[0]? arg[0][0] : 0;
  a06=(a04*a05);
  a03=sinh(a03);
  a07=(a03/a01);
  a08=arg[0]? arg[0][3] : 0;
  a09=(a07*a08);
  a06=(a06+a09);
  a09=1.;
  a10=(a09-a04);
  a11=arg[1]? arg[1][4] : 0;
  a12=arg[0]? arg[0][8] : 0;
  a13=(a12-a00);
  a14=(a11*a13);
  a14=(a00+a14);
  a15=(a10*a14);
  a06=(a06+a15);
  a15=arg[0]? arg[0][2] : 0;
  a16=arg[0]? arg[0][5] : 0;
  a17=(a16*a02);
  a15=(a15+a17);
  a17=cos(a15);
  a18=arg[3]? arg[3][0] : 0;
  a19=(a17*a18);
  a15=sin(a15);
  a20=arg[3]? arg[3][1] : 0;
  a21=(a15*a20);
  a19=(a19-a21);
  a19=(a06+a19);
  a00=(a00-a19);
  a21=casadi_sq(a00);
  a22=arg[0]? arg[0][7] : 0;
  a23=arg[0]? arg[0][1] : 0;
  a24=(a04*a23);
  a25=arg[0]? arg[0][4] : 0;
  a26=(a07*a25);
  a24=(a24+a26);
  a26=arg[0]? arg[0][9] : 0;
  a27=(a26-a22);
  a28=(a11*a27);
  a28=(a22+a28);
  a29=(a10*a28);
  a24=(a24+a29);
  a29=(a15*a18);
  a30=(a17*a20);
  a29=(a29+a30);
  a29=(a24+a29);
  a22=(a22-a29);
  a30=casadi_sq(a22);
  a21=(a21+a30);
  if (res[0]!=0) res[0][0]=a21;
  a21=arg[3]? arg[3][2] : 0;
  a30=(a17*a21);
  a31=arg[3]? arg[3][3] : 0;
  a32=(a15*a31);
  a30=(a30-a32);
  a30=(a06+a30);
  a12=(a12-a30);
  a32=casadi_sq(a12);
  a33=(a15*a21);
  a34=(a17*a31);
  a33=(a33+a34);
  a33=(a24+a33);
  a26=(a26-a33);
  a34=casadi_sq(a26);
  a32=(a32+a34);
  if (res[0]!=0) res[0][1]=a32;
  a32=arg[1]? arg[1][0] : 0;
  a19=(a32-a19);
  a34=casadi_sq(a19);
  a35=arg[1]? arg[1][1] : 0;
  a29=(a35-a29);
  a36=casadi_sq(a29);
  a34=(a34+a36);
  if (res[0]!=0) res[0][2]=a34;
  a34=arg[1]? arg[1][2] : 0;
  a30=(a34-a30);
  a36=casadi_sq(a30);
  a37=arg[1]? arg[1][3] : 0;
  a33=(a37-a33);
  a38=casadi_sq(a33);
  a36=(a36+a38);
  if (res[0]!=0) res[0][3]=a36;
  a36=12.;
  a38=2.5815789473684209e+01;
  a39=(a05-a14);
  a39=(a38*a39);
  a39=(a36*a39);
  a40=2.;
  a39=(a39/a40);
  a41=arg[1]? arg[1][5] : 0;
  a42=(a39+a41);
  a43=casadi_sq(a42);
  a44=(a23-a28);
  a44=(a38*a44);
  a44=(a36*a44);
  a44=(a44/a40);
  a40=arg[1]? arg[1][6] : 0;
  a45=(a44+a40);
  a46=casadi_sq(a45);
  a43=(a43+a46);
  a46=9.8100000000000005e+00;
  a47=8.0000000000000004e-01;
  a48=(a47*a11);
  a48=(a36*a48);
  a48=(a46*a48);
  a49=casadi_sq(a48);
  a43=(a43-a49);
  a49=1.0000000000000000e-03;
  a43=(a43+a49);
  if (res[0]!=0) res[0][4]=a43;
  a39=(a39-a41);
  a41=casadi_sq(a39);
  a44=(a44-a40);
  a40=casadi_sq(a44);
  a41=(a41+a40);
  a40=(a09-a11);
  a47=(a47*a40);
  a47=(a36*a47);
  a46=(a46*a47);
  a47=casadi_sq(a46);
  a41=(a41-a47);
  a41=(a41+a49);
  if (res[0]!=0) res[0][5]=a41;
  a41=arg[1]? arg[1][8] : 0;
  a49=casadi_sq(a41);
  a47=arg[1]? arg[1][9] : 0;
  a43=casadi_sq(a47);
  a49=(a49+a43);
  if (res[0]!=0) res[0][6]=a49;
  a49=2.0000000000000001e-01;
  a43=(a49*a17);
  a50=(a49*a15);
  a51=(a43-a50);
  a52=(a06+a51);
  a53=(a41*a52);
  a54=(a50+a43);
  a55=(a24+a54);
  a56=(a47*a55);
  a53=(a53+a56);
  a56=arg[1]? arg[1][10] : 0;
  a53=(a53+a56);
  if (res[0]!=0) res[0][7]=a53;
  a53=-2.0000000000000001e-01;
  a57=(a53*a17);
  a58=(a57-a50);
  a59=(a06+a58);
  a60=(a41*a59);
  a61=(a53*a15);
  a62=(a61+a43);
  a63=(a24+a62);
  a64=(a47*a63);
  a60=(a60+a64);
  a60=(a60+a56);
  if (res[0]!=0) res[0][8]=a60;
  a60=(a57-a61);
  a64=(a06+a60);
  a65=(a41*a64);
  a66=(a61+a57);
  a67=(a24+a66);
  a68=(a47*a67);
  a65=(a65+a68);
  a65=(a65+a56);
  if (res[0]!=0) res[0][9]=a65;
  a43=(a43-a61);
  a06=(a06+a43);
  a61=(a41*a06);
  a50=(a50+a57);
  a24=(a24+a50);
  a57=(a47*a24);
  a61=(a61+a57);
  a61=(a61+a56);
  if (res[0]!=0) res[0][10]=a61;
  a61=(a41*a32);
  a57=(a47*a35);
  a61=(a61+a57);
  a61=(a61+a56);
  if (res[0]!=0) res[0][11]=a61;
  a61=(a41*a34);
  a57=(a47*a37);
  a61=(a61+a57);
  a61=(a61+a56);
  if (res[0]!=0) res[0][12]=a61;
  a61=arg[3]? arg[3][4] : 0;
  a57=(a41*a61);
  a65=arg[3]? arg[3][5] : 0;
  a68=(a47*a65);
  a57=(a57+a68);
  a57=(a57+a56);
  a56=arg[3]? arg[3][6] : 0;
  a68=arg[3]? arg[3][7] : 0;
  a69=arg[0]? arg[0][10] : 0;
  a69=(a69+a02);
  a69=(a68*a69);
  a56=(a56+a69);
  a57=(a57-a56);
  if (res[0]!=0) res[0][13]=a57;
  a00=(a00+a00);
  a57=(a10*a13);
  a56=(a00*a57);
  a22=(a22+a22);
  a69=(a10*a27);
  a70=(a22*a69);
  a56=(a56+a70);
  a56=(-a56);
  if (res[1]!=0) res[1][0]=a56;
  a01=(a01*a03);
  a05=(a05*a01);
  a08=(a08*a04);
  a05=(a05+a08);
  a14=(a14*a01);
  a05=(a05-a14);
  a14=(a15*a16);
  a08=(a18*a14);
  a16=(a17*a16);
  a03=(a20*a16);
  a08=(a08+a03);
  a08=(a05-a08);
  a03=(a00*a08);
  a23=(a23*a01);
  a25=(a25*a04);
  a23=(a23+a25);
  a28=(a28*a01);
  a23=(a23-a28);
  a28=(a18*a16);
  a01=(a20*a14);
  a28=(a28-a01);
  a28=(a23+a28);
  a01=(a22*a28);
  a03=(a03+a01);
  a03=(-a03);
  if (res[1]!=0) res[1][1]=a03;
  a03=(a00*a04);
  a03=(-a03);
  if (res[1]!=0) res[1][2]=a03;
  a03=(a22*a04);
  a03=(-a03);
  if (res[1]!=0) res[1][3]=a03;
  a03=(a18*a15);
  a01=(a20*a17);
  a03=(a03+a01);
  a01=(a00*a03);
  a25=(a18*a17);
  a56=(a20*a15);
  a25=(a25-a56);
  a56=(a22*a25);
  a01=(a01-a56);
  if (res[1]!=0) res[1][4]=a01;
  a01=(a00*a07);
  a01=(-a01);
  if (res[1]!=0) res[1][5]=a01;
  a01=(a22*a07);
  a01=(-a01);
  if (res[1]!=0) res[1][6]=a01;
  a01=(a15*a02);
  a56=(a18*a01);
  a02=(a17*a02);
  a70=(a20*a02);
  a56=(a56+a70);
  a70=(a00*a56);
  a18=(a18*a02);
  a20=(a20*a01);
  a18=(a18-a20);
  a20=(a22*a18);
  a70=(a70-a20);
  if (res[1]!=0) res[1][7]=a70;
  a70=(a10*a40);
  a20=(a09-a70);
  a71=(a00*a20);
  if (res[1]!=0) res[1][8]=a71;
  a20=(a22*a20);
  if (res[1]!=0) res[1][9]=a20;
  a10=(a10*a11);
  a00=(a00*a10);
  a00=(-a00);
  if (res[1]!=0) res[1][10]=a00;
  a22=(a22*a10);
  a22=(-a22);
  if (res[1]!=0) res[1][11]=a22;
  a12=(a12+a12);
  a22=(a12*a57);
  a26=(a26+a26);
  a00=(a26*a69);
  a22=(a22+a00);
  a22=(-a22);
  if (res[1]!=0) res[1][12]=a22;
  a22=(a21*a14);
  a00=(a31*a16);
  a22=(a22+a00);
  a22=(a05-a22);
  a00=(a12*a22);
  a20=(a21*a16);
  a71=(a31*a14);
  a20=(a20-a71);
  a20=(a23+a20);
  a71=(a26*a20);
  a00=(a00+a71);
  a00=(-a00);
  if (res[1]!=0) res[1][13]=a00;
  a00=(a12*a04);
  a00=(-a00);
  if (res[1]!=0) res[1][14]=a00;
  a00=(a26*a04);
  a00=(-a00);
  if (res[1]!=0) res[1][15]=a00;
  a00=(a21*a15);
  a71=(a31*a17);
  a00=(a00+a71);
  a71=(a12*a00);
  a17=(a21*a17);
  a15=(a31*a15);
  a17=(a17-a15);
  a15=(a26*a17);
  a71=(a71-a15);
  if (res[1]!=0) res[1][16]=a71;
  a71=(a12*a07);
  a71=(-a71);
  if (res[1]!=0) res[1][17]=a71;
  a71=(a26*a07);
  a71=(-a71);
  if (res[1]!=0) res[1][18]=a71;
  a71=(a21*a01);
  a15=(a31*a02);
  a71=(a71+a15);
  a15=(a12*a71);
  a21=(a21*a02);
  a31=(a31*a01);
  a21=(a21-a31);
  a31=(a26*a21);
  a15=(a15-a31);
  if (res[1]!=0) res[1][19]=a15;
  a15=(a12*a70);
  a15=(-a15);
  if (res[1]!=0) res[1][20]=a15;
  a15=(a26*a70);
  a15=(-a15);
  if (res[1]!=0) res[1][21]=a15;
  a15=(a09-a10);
  a12=(a12*a15);
  if (res[1]!=0) res[1][22]=a12;
  a26=(a26*a15);
  if (res[1]!=0) res[1][23]=a26;
  a19=(a19+a19);
  if (res[1]!=0) res[1][24]=a19;
  a29=(a29+a29);
  if (res[1]!=0) res[1][25]=a29;
  a26=(a19*a57);
  a15=(a29*a69);
  a26=(a26+a15);
  a26=(-a26);
  if (res[1]!=0) res[1][26]=a26;
  a08=(a19*a08);
  a28=(a29*a28);
  a08=(a08+a28);
  a08=(-a08);
  if (res[1]!=0) res[1][27]=a08;
  a08=(a19*a04);
  a08=(-a08);
  if (res[1]!=0) res[1][28]=a08;
  a08=(a29*a04);
  a08=(-a08);
  if (res[1]!=0) res[1][29]=a08;
  a03=(a19*a03);
  a25=(a29*a25);
  a03=(a03-a25);
  if (res[1]!=0) res[1][30]=a03;
  a03=(a19*a07);
  a03=(-a03);
  if (res[1]!=0) res[1][31]=a03;
  a03=(a29*a07);
  a03=(-a03);
  if (res[1]!=0) res[1][32]=a03;
  a56=(a19*a56);
  a18=(a29*a18);
  a56=(a56-a18);
  if (res[1]!=0) res[1][33]=a56;
  a56=(a19*a70);
  a56=(-a56);
  if (res[1]!=0) res[1][34]=a56;
  a56=(a29*a70);
  a56=(-a56);
  if (res[1]!=0) res[1][35]=a56;
  a19=(a19*a10);
  a19=(-a19);
  if (res[1]!=0) res[1][36]=a19;
  a29=(a29*a10);
  a29=(-a29);
  if (res[1]!=0) res[1][37]=a29;
  a30=(a30+a30);
  if (res[1]!=0) res[1][38]=a30;
  a33=(a33+a33);
  if (res[1]!=0) res[1][39]=a33;
  a29=(a30*a57);
  a19=(a33*a69);
  a29=(a29+a19);
  a29=(-a29);
  if (res[1]!=0) res[1][40]=a29;
  a22=(a30*a22);
  a20=(a33*a20);
  a22=(a22+a20);
  a22=(-a22);
  if (res[1]!=0) res[1][41]=a22;
  a22=(a30*a04);
  a22=(-a22);
  if (res[1]!=0) res[1][42]=a22;
  a22=(a33*a04);
  a22=(-a22);
  if (res[1]!=0) res[1][43]=a22;
  a00=(a30*a00);
  a17=(a33*a17);
  a00=(a00-a17);
  if (res[1]!=0) res[1][44]=a00;
  a00=(a30*a07);
  a00=(-a00);
  if (res[1]!=0) res[1][45]=a00;
  a00=(a33*a07);
  a00=(-a00);
  if (res[1]!=0) res[1][46]=a00;
  a71=(a30*a71);
  a21=(a33*a21);
  a71=(a71-a21);
  if (res[1]!=0) res[1][47]=a71;
  a71=(a30*a70);
  a71=(-a71);
  if (res[1]!=0) res[1][48]=a71;
  a71=(a33*a70);
  a71=(-a71);
  if (res[1]!=0) res[1][49]=a71;
  a30=(a30*a10);
  a30=(-a30);
  if (res[1]!=0) res[1][50]=a30;
  a33=(a33*a10);
  a33=(-a33);
  if (res[1]!=0) res[1][51]=a33;
  a42=(a42+a42);
  a33=5.0000000000000000e-01;
  a13=(a38*a13);
  a13=(a36*a13);
  a13=(a33*a13);
  a30=(a42*a13);
  a45=(a45+a45);
  a27=(a38*a27);
  a27=(a36*a27);
  a27=(a33*a27);
  a71=(a45*a27);
  a30=(a30+a71);
  a71=9.4176000000000016e+01;
  a48=(a48+a48);
  a71=(a71*a48);
  a30=(a30+a71);
  a30=(-a30);
  if (res[1]!=0) res[1][52]=a30;
  if (res[1]!=0) res[1][53]=a42;
  if (res[1]!=0) res[1][54]=a45;
  a30=1.5489473684210526e+02;
  a71=(a30*a42);
  if (res[1]!=0) res[1][55]=a71;
  a71=(a30*a45);
  if (res[1]!=0) res[1][56]=a71;
  a40=(a38*a40);
  a40=(a36*a40);
  a40=(a33*a40);
  a71=(a42*a40);
  a71=(-a71);
  if (res[1]!=0) res[1][57]=a71;
  a71=(a45*a40);
  a71=(-a71);
  if (res[1]!=0) res[1][58]=a71;
  a38=(a38*a11);
  a36=(a36*a38);
  a33=(a33*a36);
  a42=(a42*a33);
  a42=(-a42);
  if (res[1]!=0) res[1][59]=a42;
  a45=(a45*a33);
  a45=(-a45);
  if (res[1]!=0) res[1][60]=a45;
  a39=(a39+a39);
  a13=(a39*a13);
  a44=(a44+a44);
  a27=(a44*a27);
  a13=(a13+a27);
  a27=-9.4176000000000016e+01;
  a46=(a46+a46);
  a27=(a27*a46);
  a13=(a13+a27);
  a13=(-a13);
  if (res[1]!=0) res[1][61]=a13;
  a13=(-a39);
  if (res[1]!=0) res[1][62]=a13;
  a13=(-a44);
  if (res[1]!=0) res[1][63]=a13;
  a13=(a30*a39);
  if (res[1]!=0) res[1][64]=a13;
  a30=(a30*a44);
  if (res[1]!=0) res[1][65]=a30;
  a30=(a39*a40);
  a30=(-a30);
  if (res[1]!=0) res[1][66]=a30;
  a40=(a44*a40);
  a40=(-a40);
  if (res[1]!=0) res[1][67]=a40;
  a39=(a39*a33);
  a39=(-a39);
  if (res[1]!=0) res[1][68]=a39;
  a44=(a44*a33);
  a44=(-a44);
  if (res[1]!=0) res[1][69]=a44;
  a44=(a41+a41);
  if (res[1]!=0) res[1][70]=a44;
  a44=(a47+a47);
  if (res[1]!=0) res[1][71]=a44;
  a57=(a41*a57);
  a69=(a47*a69);
  a57=(a57+a69);
  if (res[1]!=0) res[1][72]=a57;
  a69=(a49*a14);
  a44=(a49*a16);
  a33=(a69+a44);
  a33=(a05-a33);
  a33=(a41*a33);
  a39=(a44-a69);
  a39=(a23+a39);
  a39=(a47*a39);
  a33=(a33+a39);
  if (res[1]!=0) res[1][73]=a33;
  if (res[1]!=0) res[1][74]=a52;
  if (res[1]!=0) res[1][75]=a55;
  if (res[1]!=0) res[1][76]=a09;
  a55=(a41*a04);
  if (res[1]!=0) res[1][77]=a55;
  a04=(a47*a04);
  if (res[1]!=0) res[1][78]=a04;
  a51=(a47*a51);
  a54=(a41*a54);
  a51=(a51-a54);
  if (res[1]!=0) res[1][79]=a51;
  a51=(a41*a07);
  if (res[1]!=0) res[1][80]=a51;
  a07=(a47*a07);
  if (res[1]!=0) res[1][81]=a07;
  a54=(a49*a02);
  a49=(a49*a01);
  a52=(a54-a49);
  a52=(a47*a52);
  a33=(a49+a54);
  a33=(a41*a33);
  a52=(a52-a33);
  if (res[1]!=0) res[1][82]=a52;
  a52=(a41*a70);
  if (res[1]!=0) res[1][83]=a52;
  a70=(a47*a70);
  if (res[1]!=0) res[1][84]=a70;
  a33=(a41*a10);
  if (res[1]!=0) res[1][85]=a33;
  a10=(a47*a10);
  if (res[1]!=0) res[1][86]=a10;
  if (res[1]!=0) res[1][87]=a57;
  a14=(a53*a14);
  a39=(a14+a44);
  a39=(a05-a39);
  a39=(a41*a39);
  a16=(a53*a16);
  a40=(a16-a69);
  a40=(a23+a40);
  a40=(a47*a40);
  a39=(a39+a40);
  if (res[1]!=0) res[1][88]=a39;
  if (res[1]!=0) res[1][89]=a59;
  if (res[1]!=0) res[1][90]=a63;
  if (res[1]!=0) res[1][91]=a09;
  if (res[1]!=0) res[1][92]=a55;
  if (res[1]!=0) res[1][93]=a04;
  a58=(a47*a58);
  a62=(a41*a62);
  a58=(a58-a62);
  if (res[1]!=0) res[1][94]=a58;
  if (res[1]!=0) res[1][95]=a51;
  if (res[1]!=0) res[1][96]=a07;
  a02=(a53*a02);
  a58=(a02-a49);
  a58=(a47*a58);
  a53=(a53*a01);
  a01=(a53+a54);
  a01=(a41*a01);
  a58=(a58-a01);
  if (res[1]!=0) res[1][97]=a58;
  if (res[1]!=0) res[1][98]=a52;
  if (res[1]!=0) res[1][99]=a70;
  if (res[1]!=0) res[1][100]=a33;
  if (res[1]!=0) res[1][101]=a10;
  if (res[1]!=0) res[1][102]=a57;
  a58=(a14+a16);
  a58=(a05-a58);
  a58=(a41*a58);
  a01=(a16-a14);
  a01=(a23+a01);
  a01=(a47*a01);
  a58=(a58+a01);
  if (res[1]!=0) res[1][103]=a58;
  if (res[1]!=0) res[1][104]=a64;
  if (res[1]!=0) res[1][105]=a67;
  if (res[1]!=0) res[1][106]=a09;
  if (res[1]!=0) res[1][107]=a55;
  if (res[1]!=0) res[1][108]=a04;
  a60=(a47*a60);
  a66=(a41*a66);
  a60=(a60-a66);
  if (res[1]!=0) res[1][109]=a60;
  if (res[1]!=0) res[1][110]=a51;
  if (res[1]!=0) res[1][111]=a07;
  a60=(a02-a53);
  a60=(a47*a60);
  a66=(a53+a02);
  a66=(a41*a66);
  a60=(a60-a66);
  if (res[1]!=0) res[1][112]=a60;
  if (res[1]!=0) res[1][113]=a52;
  if (res[1]!=0) res[1][114]=a70;
  if (res[1]!=0) res[1][115]=a33;
  if (res[1]!=0) res[1][116]=a10;
  if (res[1]!=0) res[1][117]=a57;
  a69=(a69+a16);
  a05=(a05-a69);
  a05=(a41*a05);
  a44=(a44-a14);
  a23=(a23+a44);
  a23=(a47*a23);
  a05=(a05+a23);
  if (res[1]!=0) res[1][118]=a05;
  if (res[1]!=0) res[1][119]=a06;
  if (res[1]!=0) res[1][120]=a24;
  if (res[1]!=0) res[1][121]=a09;
  if (res[1]!=0) res[1][122]=a55;
  if (res[1]!=0) res[1][123]=a04;
  a43=(a47*a43);
  a50=(a41*a50);
  a43=(a43-a50);
  if (res[1]!=0) res[1][124]=a43;
  if (res[1]!=0) res[1][125]=a51;
  if (res[1]!=0) res[1][126]=a07;
  a54=(a54-a53);
  a54=(a47*a54);
  a49=(a49+a02);
  a49=(a41*a49);
  a54=(a54-a49);
  if (res[1]!=0) res[1][127]=a54;
  if (res[1]!=0) res[1][128]=a52;
  if (res[1]!=0) res[1][129]=a70;
  if (res[1]!=0) res[1][130]=a33;
  if (res[1]!=0) res[1][131]=a10;
  if (res[1]!=0) res[1][132]=a41;
  if (res[1]!=0) res[1][133]=a47;
  if (res[1]!=0) res[1][134]=a32;
  if (res[1]!=0) res[1][135]=a35;
  if (res[1]!=0) res[1][136]=a09;
  if (res[1]!=0) res[1][137]=a41;
  if (res[1]!=0) res[1][138]=a47;
  if (res[1]!=0) res[1][139]=a34;
  if (res[1]!=0) res[1][140]=a37;
  if (res[1]!=0) res[1][141]=a09;
  a68=(-a68);
  if (res[1]!=0) res[1][142]=a68;
  if (res[1]!=0) res[1][143]=a61;
  if (res[1]!=0) res[1][144]=a65;
  if (res[1]!=0) res[1][145]=a09;
  if (res[1]!=0) res[1][146]=a68;
  return 0;
}

CASADI_SYMBOL_EXPORT int lipm_step_ca_constr_h_fun_jac_uxt_zt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int lipm_step_ca_constr_h_fun_jac_uxt_zt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int lipm_step_ca_constr_h_fun_jac_uxt_zt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void lipm_step_ca_constr_h_fun_jac_uxt_zt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int lipm_step_ca_constr_h_fun_jac_uxt_zt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void lipm_step_ca_constr_h_fun_jac_uxt_zt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void lipm_step_ca_constr_h_fun_jac_uxt_zt_incref(void) {
}

CASADI_SYMBOL_EXPORT void lipm_step_ca_constr_h_fun_jac_uxt_zt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int lipm_step_ca_constr_h_fun_jac_uxt_zt_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int lipm_step_ca_constr_h_fun_jac_uxt_zt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real lipm_step_ca_constr_h_fun_jac_uxt_zt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* lipm_step_ca_constr_h_fun_jac_uxt_zt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* lipm_step_ca_constr_h_fun_jac_uxt_zt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* lipm_step_ca_constr_h_fun_jac_uxt_zt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* lipm_step_ca_constr_h_fun_jac_uxt_zt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s4;
    case 2: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int lipm_step_ca_constr_h_fun_jac_uxt_zt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int lipm_step_ca_constr_h_fun_jac_uxt_zt_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
