/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) lipm_opti_pessi_dyn_disc_phi_fun_jac_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[3] = {22, 1, 1};
static const casadi_int casadi_s1[3] = {8, 1, 1};
static const casadi_int casadi_s2[113] = 
  {44, 22, 0, 6, 12, 15, 21, 27,
  38, 39, 40, 41, 42, 44, 50, 56,
  59, 65, 71, 82, 83, 84, 85, 86,
  88, 4, 7, 22, 25, 28, 30, 4,
  7, 23, 26, 29, 31, 7, 24, 27,
  4, 7, 22, 25, 28, 30, 4, 7,
  23, 26, 29, 31, 4, 5, 6, 7,
  22, 23, 27, 28, 29, 30, 31, 0,
  1, 2, 3, 7, 32, 15, 18, 33,
  36, 39, 41, 15, 18, 34, 37, 40,
  42, 18, 35, 38, 15, 18, 33, 36,
  39, 41, 15, 18, 34, 37, 40, 42,
  15, 16, 17, 18, 33, 34, 38, 39,
  40, 41, 42, 11, 12, 13, 14, 18,
  43};

/* lipm_opti_pessi_dyn_disc_phi_fun_jac:(i0[22],i1[22],i2[8])->(o0[22],o1[44x22,88nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39, a40, a41, a42, a43, a44, a45, a46, a47;
  casadi_real a48, a49, a50, a51, a52, a53, a54, a55, a56, a57, a58, a59;
  casadi_real a60, a61, a62, a63, a64, a65, a66, a67, a68, a69;
  a00=5.0809240767486585e+00;
  a01=arg[1]? arg[1][7] : 0;
  a02=(a00*a01);
  a03=cosh(a02);
  a04=arg[0]? arg[0][0] : 0;
  a05=(a03*a04);
  a02=sinh(a02);
  a06=(a02/a00);
  a07=arg[0]? arg[0][3] : 0;
  a08=(a06*a07);
  a05=(a05+a08);
  a08=1.;
  a09=(a08-a03);
  a10=arg[0]? arg[0][6] : 0;
  a11=arg[1]? arg[1][4] : 0;
  a12=arg[0]? arg[0][8] : 0;
  a13=(a12-a10);
  a14=(a11*a13);
  a14=(a10+a14);
  a15=(a09*a14);
  a05=(a05+a15);
  if (res[0]!=0) res[0][0]=a05;
  a05=arg[0]? arg[0][1] : 0;
  a15=(a03*a05);
  a16=arg[0]? arg[0][4] : 0;
  a17=(a06*a16);
  a15=(a15+a17);
  a17=arg[0]? arg[0][7] : 0;
  a18=arg[0]? arg[0][9] : 0;
  a19=(a18-a17);
  a20=(a11*a19);
  a20=(a17+a20);
  a21=(a09*a20);
  a15=(a15+a21);
  if (res[0]!=0) res[0][1]=a15;
  a15=arg[0]? arg[0][2] : 0;
  a21=arg[0]? arg[0][5] : 0;
  a22=(a21*a01);
  a15=(a15+a22);
  if (res[0]!=0) res[0][2]=a15;
  a02=(a00*a02);
  a15=(a02*a04);
  a22=(a03*a07);
  a15=(a15+a22);
  a22=(a02*a14);
  a15=(a15-a22);
  if (res[0]!=0) res[0][3]=a15;
  a15=(a02*a05);
  a22=(a03*a16);
  a15=(a15+a22);
  a22=(a02*a20);
  a15=(a15-a22);
  if (res[0]!=0) res[0][4]=a15;
  a15=1.4999999999999999e-01;
  a22=(a01/a15);
  a10=(a10-a04);
  a23=arg[1]? arg[1][6] : 0;
  a24=12.;
  a25=2.5815789473684209e+01;
  a26=(a05-a20);
  a26=(a25*a26);
  a26=(a24*a26);
  a27=(a23*a26);
  a28=(a10*a27);
  a17=(a17-a05);
  a29=arg[1]? arg[1][5] : 0;
  a30=(a04-a14);
  a30=(a25*a30);
  a30=(a24*a30);
  a31=(a29*a30);
  a32=(a17*a31);
  a28=(a28-a32);
  a12=(a12-a04);
  a32=(a08-a23);
  a33=(a32*a26);
  a34=(a12*a33);
  a18=(a18-a05);
  a35=(a08-a29);
  a36=(a35*a30);
  a37=(a18*a36);
  a34=(a34-a37);
  a28=(a28+a34);
  a34=(a22*a28);
  a34=(a21+a34);
  if (res[0]!=0) res[0][5]=a34;
  a34=arg[1]? arg[1][0] : 0;
  if (res[0]!=0) res[0][6]=a34;
  a34=arg[1]? arg[1][1] : 0;
  if (res[0]!=0) res[0][7]=a34;
  a34=arg[1]? arg[1][2] : 0;
  if (res[0]!=0) res[0][8]=a34;
  a34=arg[1]? arg[1][3] : 0;
  if (res[0]!=0) res[0][9]=a34;
  a34=arg[0]? arg[0][10] : 0;
  a34=(a34+a01);
  if (res[0]!=0) res[0][10]=a34;
  a34=arg[1]? arg[1][18] : 0;
  a37=(a00*a34);
  a38=cosh(a37);
  a39=arg[0]? arg[0][11] : 0;
  a40=(a38*a39);
  a37=sinh(a37);
  a41=(a37/a00);
  a42=arg[0]? arg[0][14] : 0;
  a43=(a41*a42);
  a40=(a40+a43);
  a43=(a08-a38);
  a44=arg[0]? arg[0][17] : 0;
  a45=arg[1]? arg[1][15] : 0;
  a46=arg[0]? arg[0][19] : 0;
  a47=(a46-a44);
  a48=(a45*a47);
  a48=(a44+a48);
  a49=(a43*a48);
  a40=(a40+a49);
  if (res[0]!=0) res[0][11]=a40;
  a40=arg[0]? arg[0][12] : 0;
  a49=(a38*a40);
  a50=arg[0]? arg[0][15] : 0;
  a51=(a41*a50);
  a49=(a49+a51);
  a51=arg[0]? arg[0][18] : 0;
  a52=arg[0]? arg[0][20] : 0;
  a53=(a52-a51);
  a54=(a45*a53);
  a54=(a51+a54);
  a55=(a43*a54);
  a49=(a49+a55);
  if (res[0]!=0) res[0][12]=a49;
  a49=arg[0]? arg[0][13] : 0;
  a55=arg[0]? arg[0][16] : 0;
  a56=(a55*a34);
  a49=(a49+a56);
  if (res[0]!=0) res[0][13]=a49;
  a37=(a00*a37);
  a49=(a37*a39);
  a56=(a38*a42);
  a49=(a49+a56);
  a56=(a37*a48);
  a49=(a49-a56);
  if (res[0]!=0) res[0][14]=a49;
  a49=(a37*a40);
  a56=(a38*a50);
  a49=(a49+a56);
  a56=(a37*a54);
  a49=(a49-a56);
  if (res[0]!=0) res[0][15]=a49;
  a15=(a34/a15);
  a44=(a44-a39);
  a49=arg[1]? arg[1][17] : 0;
  a56=(a40-a54);
  a56=(a25*a56);
  a56=(a24*a56);
  a57=(a49*a56);
  a58=(a44*a57);
  a51=(a51-a40);
  a59=arg[1]? arg[1][16] : 0;
  a60=(a39-a48);
  a60=(a25*a60);
  a60=(a24*a60);
  a61=(a59*a60);
  a62=(a51*a61);
  a58=(a58-a62);
  a46=(a46-a39);
  a62=(a08-a49);
  a63=(a62*a56);
  a64=(a46*a63);
  a52=(a52-a40);
  a65=(a08-a59);
  a66=(a65*a60);
  a67=(a52*a66);
  a64=(a64-a67);
  a58=(a58+a64);
  a64=(a15*a58);
  a64=(a55+a64);
  if (res[0]!=0) res[0][16]=a64;
  a64=arg[1]? arg[1][11] : 0;
  if (res[0]!=0) res[0][17]=a64;
  a64=arg[1]? arg[1][12] : 0;
  if (res[0]!=0) res[0][18]=a64;
  a64=arg[1]? arg[1][13] : 0;
  if (res[0]!=0) res[0][19]=a64;
  a64=arg[1]? arg[1][14] : 0;
  if (res[0]!=0) res[0][20]=a64;
  a64=arg[0]? arg[0][21] : 0;
  a64=(a64+a34);
  if (res[0]!=0) res[0][21]=a64;
  a64=(a09*a13);
  if (res[1]!=0) res[1][0]=a64;
  a64=(a04*a02);
  a67=(a07*a03);
  a64=(a64+a67);
  a67=(a14*a02);
  a64=(a64-a67);
  if (res[1]!=0) res[1][1]=a64;
  if (res[1]!=0) res[1][2]=a03;
  if (res[1]!=0) res[1][3]=a06;
  a64=(a08-a11);
  a67=(a09*a64);
  if (res[1]!=0) res[1][4]=a67;
  a68=(a09*a11);
  if (res[1]!=0) res[1][5]=a68;
  a09=(a09*a19);
  if (res[1]!=0) res[1][6]=a09;
  a09=(a05*a02);
  a69=(a16*a03);
  a09=(a09+a69);
  a69=(a20*a02);
  a09=(a09-a69);
  if (res[1]!=0) res[1][7]=a09;
  if (res[1]!=0) res[1][8]=a03;
  if (res[1]!=0) res[1][9]=a06;
  if (res[1]!=0) res[1][10]=a67;
  if (res[1]!=0) res[1][11]=a68;
  if (res[1]!=0) res[1][12]=a21;
  if (res[1]!=0) res[1][13]=a08;
  if (res[1]!=0) res[1][14]=a01;
  a01=(a02*a13);
  a01=(-a01);
  if (res[1]!=0) res[1][15]=a01;
  a01=(a00*a03);
  a01=(a00*a01);
  a04=(a04*a01);
  a07=(a07*a02);
  a04=(a04+a07);
  a14=(a14*a01);
  a04=(a04-a14);
  if (res[1]!=0) res[1][16]=a04;
  if (res[1]!=0) res[1][17]=a02;
  if (res[1]!=0) res[1][18]=a03;
  a04=(a02*a64);
  a04=(-a04);
  if (res[1]!=0) res[1][19]=a04;
  a14=(a02*a11);
  a14=(-a14);
  if (res[1]!=0) res[1][20]=a14;
  a07=(a02*a19);
  a07=(-a07);
  if (res[1]!=0) res[1][21]=a07;
  a05=(a05*a01);
  a16=(a16*a02);
  a05=(a05+a16);
  a20=(a20*a01);
  a05=(a05-a20);
  if (res[1]!=0) res[1][22]=a05;
  if (res[1]!=0) res[1][23]=a02;
  if (res[1]!=0) res[1][24]=a03;
  if (res[1]!=0) res[1][25]=a04;
  if (res[1]!=0) res[1][26]=a14;
  a13=(a25*a13);
  a13=(a24*a13);
  a14=(a29*a13);
  a14=(a17*a14);
  a19=(a25*a19);
  a19=(a24*a19);
  a04=(a23*a19);
  a04=(a10*a04);
  a14=(a14-a04);
  a13=(a35*a13);
  a13=(a18*a13);
  a19=(a32*a19);
  a19=(a12*a19);
  a13=(a13-a19);
  a14=(a14+a13);
  a14=(a22*a14);
  if (res[1]!=0) res[1][27]=a14;
  a14=(a18*a30);
  a30=(a17*a30);
  a14=(a14-a30);
  a14=(a22*a14);
  if (res[1]!=0) res[1][28]=a14;
  a14=(a10*a26);
  a26=(a12*a26);
  a14=(a14-a26);
  a14=(a22*a14);
  if (res[1]!=0) res[1][29]=a14;
  a14=6.6666666666666670e+00;
  a28=(a14*a28);
  if (res[1]!=0) res[1][30]=a28;
  a28=3.0978947368421052e+02;
  a26=(a28*a29);
  a26=(a17*a26);
  a26=(a27+a26);
  a30=(a28*a35);
  a30=(a18*a30);
  a30=(a33+a30);
  a26=(a26+a30);
  a26=(a22*a26);
  a26=(-a26);
  if (res[1]!=0) res[1][31]=a26;
  a26=(a28*a23);
  a26=(a10*a26);
  a26=(a26+a31);
  a30=(a28*a32);
  a30=(a12*a30);
  a30=(a30+a36);
  a26=(a26+a30);
  a26=(a22*a26);
  if (res[1]!=0) res[1][32]=a26;
  if (res[1]!=0) res[1][33]=a08;
  a64=(a25*a64);
  a64=(a24*a64);
  a26=(a29*a64);
  a26=(a17*a26);
  a27=(a27+a26);
  a26=(a35*a64);
  a26=(a18*a26);
  a27=(a27+a26);
  a27=(a22*a27);
  if (res[1]!=0) res[1][34]=a27;
  a27=(a23*a64);
  a27=(a10*a27);
  a27=(a27+a31);
  a64=(a32*a64);
  a64=(a12*a64);
  a27=(a27+a64);
  a27=(a22*a27);
  a27=(-a27);
  if (res[1]!=0) res[1][35]=a27;
  a11=(a25*a11);
  a11=(a24*a11);
  a29=(a29*a11);
  a17=(a17*a29);
  a35=(a35*a11);
  a18=(a18*a35);
  a33=(a33+a18);
  a17=(a17+a33);
  a17=(a22*a17);
  if (res[1]!=0) res[1][36]=a17;
  a23=(a23*a11);
  a10=(a10*a23);
  a32=(a32*a11);
  a12=(a12*a32);
  a12=(a12+a36);
  a10=(a10+a12);
  a22=(a22*a10);
  a22=(-a22);
  if (res[1]!=0) res[1][37]=a22;
  if (res[1]!=0) res[1][38]=a08;
  if (res[1]!=0) res[1][39]=a08;
  if (res[1]!=0) res[1][40]=a08;
  if (res[1]!=0) res[1][41]=a08;
  if (res[1]!=0) res[1][42]=a08;
  if (res[1]!=0) res[1][43]=a08;
  a22=(a43*a47);
  if (res[1]!=0) res[1][44]=a22;
  a22=(a39*a37);
  a10=(a42*a38);
  a22=(a22+a10);
  a10=(a48*a37);
  a22=(a22-a10);
  if (res[1]!=0) res[1][45]=a22;
  if (res[1]!=0) res[1][46]=a38;
  if (res[1]!=0) res[1][47]=a41;
  a22=(a08-a45);
  a10=(a43*a22);
  if (res[1]!=0) res[1][48]=a10;
  a12=(a43*a45);
  if (res[1]!=0) res[1][49]=a12;
  a43=(a43*a53);
  if (res[1]!=0) res[1][50]=a43;
  a43=(a40*a37);
  a36=(a50*a38);
  a43=(a43+a36);
  a36=(a54*a37);
  a43=(a43-a36);
  if (res[1]!=0) res[1][51]=a43;
  if (res[1]!=0) res[1][52]=a38;
  if (res[1]!=0) res[1][53]=a41;
  if (res[1]!=0) res[1][54]=a10;
  if (res[1]!=0) res[1][55]=a12;
  if (res[1]!=0) res[1][56]=a55;
  if (res[1]!=0) res[1][57]=a08;
  if (res[1]!=0) res[1][58]=a34;
  a34=(a37*a47);
  a34=(-a34);
  if (res[1]!=0) res[1][59]=a34;
  a34=(a00*a38);
  a00=(a00*a34);
  a39=(a39*a00);
  a42=(a42*a37);
  a39=(a39+a42);
  a48=(a48*a00);
  a39=(a39-a48);
  if (res[1]!=0) res[1][60]=a39;
  if (res[1]!=0) res[1][61]=a37;
  if (res[1]!=0) res[1][62]=a38;
  a39=(a37*a22);
  a39=(-a39);
  if (res[1]!=0) res[1][63]=a39;
  a48=(a37*a45);
  a48=(-a48);
  if (res[1]!=0) res[1][64]=a48;
  a42=(a37*a53);
  a42=(-a42);
  if (res[1]!=0) res[1][65]=a42;
  a40=(a40*a00);
  a50=(a50*a37);
  a40=(a40+a50);
  a54=(a54*a00);
  a40=(a40-a54);
  if (res[1]!=0) res[1][66]=a40;
  if (res[1]!=0) res[1][67]=a37;
  if (res[1]!=0) res[1][68]=a38;
  if (res[1]!=0) res[1][69]=a39;
  if (res[1]!=0) res[1][70]=a48;
  a47=(a25*a47);
  a47=(a24*a47);
  a48=(a59*a47);
  a48=(a51*a48);
  a53=(a25*a53);
  a53=(a24*a53);
  a39=(a49*a53);
  a39=(a44*a39);
  a48=(a48-a39);
  a47=(a65*a47);
  a47=(a52*a47);
  a53=(a62*a53);
  a53=(a46*a53);
  a47=(a47-a53);
  a48=(a48+a47);
  a48=(a15*a48);
  if (res[1]!=0) res[1][71]=a48;
  a48=(a52*a60);
  a60=(a51*a60);
  a48=(a48-a60);
  a48=(a15*a48);
  if (res[1]!=0) res[1][72]=a48;
  a48=(a44*a56);
  a56=(a46*a56);
  a48=(a48-a56);
  a48=(a15*a48);
  if (res[1]!=0) res[1][73]=a48;
  a14=(a14*a58);
  if (res[1]!=0) res[1][74]=a14;
  a14=(a28*a59);
  a14=(a51*a14);
  a14=(a57+a14);
  a58=(a28*a65);
  a58=(a52*a58);
  a58=(a63+a58);
  a14=(a14+a58);
  a14=(a15*a14);
  a14=(-a14);
  if (res[1]!=0) res[1][75]=a14;
  a14=(a28*a49);
  a14=(a44*a14);
  a14=(a14+a61);
  a28=(a28*a62);
  a28=(a46*a28);
  a28=(a28+a66);
  a14=(a14+a28);
  a14=(a15*a14);
  if (res[1]!=0) res[1][76]=a14;
  if (res[1]!=0) res[1][77]=a08;
  a22=(a25*a22);
  a22=(a24*a22);
  a14=(a59*a22);
  a14=(a51*a14);
  a57=(a57+a14);
  a14=(a65*a22);
  a14=(a52*a14);
  a57=(a57+a14);
  a57=(a15*a57);
  if (res[1]!=0) res[1][78]=a57;
  a57=(a49*a22);
  a57=(a44*a57);
  a57=(a57+a61);
  a22=(a62*a22);
  a22=(a46*a22);
  a57=(a57+a22);
  a57=(a15*a57);
  a57=(-a57);
  if (res[1]!=0) res[1][79]=a57;
  a25=(a25*a45);
  a24=(a24*a25);
  a59=(a59*a24);
  a51=(a51*a59);
  a65=(a65*a24);
  a52=(a52*a65);
  a63=(a63+a52);
  a51=(a51+a63);
  a51=(a15*a51);
  if (res[1]!=0) res[1][80]=a51;
  a49=(a49*a24);
  a44=(a44*a49);
  a62=(a62*a24);
  a46=(a46*a62);
  a46=(a46+a66);
  a44=(a44+a46);
  a15=(a15*a44);
  a15=(-a15);
  if (res[1]!=0) res[1][81]=a15;
  if (res[1]!=0) res[1][82]=a08;
  if (res[1]!=0) res[1][83]=a08;
  if (res[1]!=0) res[1][84]=a08;
  if (res[1]!=0) res[1][85]=a08;
  if (res[1]!=0) res[1][86]=a08;
  if (res[1]!=0) res[1][87]=a08;
  return 0;
}

CASADI_SYMBOL_EXPORT int lipm_opti_pessi_dyn_disc_phi_fun_jac(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int lipm_opti_pessi_dyn_disc_phi_fun_jac_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int lipm_opti_pessi_dyn_disc_phi_fun_jac_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void lipm_opti_pessi_dyn_disc_phi_fun_jac_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int lipm_opti_pessi_dyn_disc_phi_fun_jac_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void lipm_opti_pessi_dyn_disc_phi_fun_jac_release(int mem) {
}

CASADI_SYMBOL_EXPORT void lipm_opti_pessi_dyn_disc_phi_fun_jac_incref(void) {
}

CASADI_SYMBOL_EXPORT void lipm_opti_pessi_dyn_disc_phi_fun_jac_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int lipm_opti_pessi_dyn_disc_phi_fun_jac_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int lipm_opti_pessi_dyn_disc_phi_fun_jac_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real lipm_opti_pessi_dyn_disc_phi_fun_jac_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* lipm_opti_pessi_dyn_disc_phi_fun_jac_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* lipm_opti_pessi_dyn_disc_phi_fun_jac_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* lipm_opti_pessi_dyn_disc_phi_fun_jac_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* lipm_opti_pessi_dyn_disc_phi_fun_jac_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int lipm_opti_pessi_dyn_disc_phi_fun_jac_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int lipm_opti_pessi_dyn_disc_phi_fun_jac_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
