/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) lipm_opti_pessi_cost_y_0_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {22, 1, 1};
static const casadi_int casadi_s1[3] = {0, 1, 1};
static const casadi_int casadi_s2[3] = {0, 0, 1};
static const casadi_int casadi_s3[3] = {8, 1, 1};
static const casadi_int casadi_s4[3] = {40, 1, 1};

/* lipm_opti_pessi_cost_y_0_fun:(i0[22],i1[22],i2[0],i3[],i4[8])->(o0[40]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27;
  a00=arg[0]? arg[0][0] : 0;
  if (res[0]!=0) res[0][0]=a00;
  a01=arg[0]? arg[0][1] : 0;
  if (res[0]!=0) res[0][1]=a01;
  a02=arg[0]? arg[0][2] : 0;
  a03=-3.1415926535897931e+00;
  a04=(a02-a03);
  a05=1.;
  a06=10.;
  a07=(a00-a06);
  a07=casadi_sq(a07);
  a08=5.;
  a09=(a01-a08);
  a09=casadi_sq(a09);
  a07=(a07+a09);
  a07=(a05+a07);
  a04=(a04/a07);
  if (res[0]!=0) res[0][2]=a04;
  a04=arg[0]? arg[0][3] : 0;
  if (res[0]!=0) res[0][3]=a04;
  a09=arg[0]? arg[0][4] : 0;
  if (res[0]!=0) res[0][4]=a09;
  a10=arg[0]? arg[0][5] : 0;
  if (res[0]!=0) res[0][5]=a10;
  a11=arg[0]? arg[0][10] : 0;
  if (res[0]!=0) res[0][6]=a11;
  a11=arg[1]? arg[1][0] : 0;
  a12=arg[0]? arg[0][6] : 0;
  a13=(a11-a12);
  if (res[0]!=0) res[0][7]=a13;
  a13=arg[1]? arg[1][1] : 0;
  a14=arg[0]? arg[0][7] : 0;
  a15=(a13-a14);
  if (res[0]!=0) res[0][8]=a15;
  a15=arg[1]? arg[1][2] : 0;
  a16=arg[0]? arg[0][8] : 0;
  a17=(a15-a16);
  if (res[0]!=0) res[0][9]=a17;
  a17=arg[1]? arg[1][3] : 0;
  a18=arg[0]? arg[0][9] : 0;
  a19=(a17-a18);
  if (res[0]!=0) res[0][10]=a19;
  a19=5.0809240767486585e+00;
  a20=arg[1]? arg[1][7] : 0;
  a21=(a19*a20);
  a22=cosh(a21);
  a00=(a22*a00);
  a21=sinh(a21);
  a21=(a21/a19);
  a23=(a21*a04);
  a00=(a00+a23);
  a23=(a05-a22);
  a24=arg[1]? arg[1][4] : 0;
  a16=(a16-a12);
  a16=(a24*a16);
  a12=(a12+a16);
  a12=(a23*a12);
  a00=(a00+a12);
  a10=(a10*a20);
  a10=(a02+a10);
  a12=cos(a10);
  a16=arg[4]? arg[4][0] : 0;
  a25=(a12*a16);
  a10=sin(a10);
  a26=arg[4]? arg[4][1] : 0;
  a27=(a10*a26);
  a25=(a25-a27);
  a25=(a00+a25);
  a11=(a11-a25);
  if (res[0]!=0) res[0][11]=a11;
  a22=(a22*a01);
  a21=(a21*a09);
  a22=(a22+a21);
  a18=(a18-a14);
  a18=(a24*a18);
  a14=(a14+a18);
  a23=(a23*a14);
  a22=(a22+a23);
  a23=(a10*a16);
  a14=(a12*a26);
  a23=(a23+a14);
  a23=(a22+a23);
  a13=(a13-a23);
  if (res[0]!=0) res[0][12]=a13;
  a13=arg[4]? arg[4][2] : 0;
  a23=(a12*a13);
  a14=arg[4]? arg[4][3] : 0;
  a18=(a10*a14);
  a23=(a23-a18);
  a00=(a00+a23);
  a15=(a15-a00);
  if (res[0]!=0) res[0][13]=a15;
  a10=(a10*a13);
  a12=(a12*a14);
  a10=(a10+a12);
  a22=(a22+a10);
  a17=(a17-a22);
  if (res[0]!=0) res[0][14]=a17;
  a17=5.0000000000000000e-01;
  a24=(a24-a17);
  if (res[0]!=0) res[0][15]=a24;
  a24=arg[1]? arg[1][5] : 0;
  if (res[0]!=0) res[0][16]=a24;
  a24=arg[1]? arg[1][6] : 0;
  if (res[0]!=0) res[0][17]=a24;
  a24=4.3749999999999997e-02;
  a20=(a20-a24);
  if (res[0]!=0) res[0][18]=a20;
  a07=(1./a07);
  a07=(a05-a07);
  a20=cos(a02);
  a09=(a09*a20);
  a02=sin(a02);
  a04=(a04*a02);
  a09=(a09-a04);
  a07=(a07*a09);
  if (res[0]!=0) res[0][19]=a07;
  a07=arg[0]? arg[0][11] : 0;
  if (res[0]!=0) res[0][20]=a07;
  a09=arg[0]? arg[0][12] : 0;
  if (res[0]!=0) res[0][21]=a09;
  a04=arg[0]? arg[0][13] : 0;
  a03=(a04-a03);
  a06=(a07-a06);
  a06=casadi_sq(a06);
  a08=(a09-a08);
  a08=casadi_sq(a08);
  a06=(a06+a08);
  a06=(a05+a06);
  a03=(a03/a06);
  if (res[0]!=0) res[0][22]=a03;
  a03=arg[0]? arg[0][14] : 0;
  if (res[0]!=0) res[0][23]=a03;
  a08=arg[0]? arg[0][15] : 0;
  if (res[0]!=0) res[0][24]=a08;
  a02=arg[0]? arg[0][16] : 0;
  if (res[0]!=0) res[0][25]=a02;
  a20=arg[0]? arg[0][21] : 0;
  if (res[0]!=0) res[0][26]=a20;
  a20=arg[1]? arg[1][11] : 0;
  a22=arg[0]? arg[0][17] : 0;
  a10=(a20-a22);
  if (res[0]!=0) res[0][27]=a10;
  a10=arg[1]? arg[1][12] : 0;
  a12=arg[0]? arg[0][18] : 0;
  a15=(a10-a12);
  if (res[0]!=0) res[0][28]=a15;
  a15=arg[1]? arg[1][13] : 0;
  a00=arg[0]? arg[0][19] : 0;
  a23=(a15-a00);
  if (res[0]!=0) res[0][29]=a23;
  a23=arg[1]? arg[1][14] : 0;
  a18=arg[0]? arg[0][20] : 0;
  a21=(a23-a18);
  if (res[0]!=0) res[0][30]=a21;
  a21=arg[1]? arg[1][18] : 0;
  a01=(a19*a21);
  a11=cosh(a01);
  a07=(a11*a07);
  a01=sinh(a01);
  a01=(a01/a19);
  a19=(a01*a03);
  a07=(a07+a19);
  a19=(a05-a11);
  a25=arg[1]? arg[1][15] : 0;
  a00=(a00-a22);
  a00=(a25*a00);
  a22=(a22+a00);
  a22=(a19*a22);
  a07=(a07+a22);
  a02=(a02*a21);
  a02=(a04+a02);
  a22=cos(a02);
  a00=(a22*a16);
  a02=sin(a02);
  a27=(a02*a26);
  a00=(a00-a27);
  a00=(a07+a00);
  a20=(a20-a00);
  if (res[0]!=0) res[0][31]=a20;
  a11=(a11*a09);
  a01=(a01*a08);
  a11=(a11+a01);
  a18=(a18-a12);
  a18=(a25*a18);
  a12=(a12+a18);
  a19=(a19*a12);
  a11=(a11+a19);
  a16=(a02*a16);
  a26=(a22*a26);
  a16=(a16+a26);
  a16=(a11+a16);
  a10=(a10-a16);
  if (res[0]!=0) res[0][32]=a10;
  a10=(a22*a13);
  a16=(a02*a14);
  a10=(a10-a16);
  a07=(a07+a10);
  a15=(a15-a07);
  if (res[0]!=0) res[0][33]=a15;
  a02=(a02*a13);
  a22=(a22*a14);
  a02=(a02+a22);
  a11=(a11+a02);
  a23=(a23-a11);
  if (res[0]!=0) res[0][34]=a23;
  a25=(a25-a17);
  if (res[0]!=0) res[0][35]=a25;
  a25=arg[1]? arg[1][16] : 0;
  if (res[0]!=0) res[0][36]=a25;
  a25=arg[1]? arg[1][17] : 0;
  if (res[0]!=0) res[0][37]=a25;
  a21=(a21-a24);
  if (res[0]!=0) res[0][38]=a21;
  a06=(1./a06);
  a05=(a05-a06);
  a06=cos(a04);
  a08=(a08*a06);
  a04=sin(a04);
  a03=(a03*a04);
  a08=(a08-a03);
  a05=(a05*a08);
  if (res[0]!=0) res[0][39]=a05;
  return 0;
}

CASADI_SYMBOL_EXPORT int lipm_opti_pessi_cost_y_0_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int lipm_opti_pessi_cost_y_0_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int lipm_opti_pessi_cost_y_0_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void lipm_opti_pessi_cost_y_0_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int lipm_opti_pessi_cost_y_0_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void lipm_opti_pessi_cost_y_0_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void lipm_opti_pessi_cost_y_0_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void lipm_opti_pessi_cost_y_0_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int lipm_opti_pessi_cost_y_0_fun_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int lipm_opti_pessi_cost_y_0_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real lipm_opti_pessi_cost_y_0_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* lipm_opti_pessi_cost_y_0_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* lipm_opti_pessi_cost_y_0_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* lipm_opti_pessi_cost_y_0_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    case 4: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* lipm_opti_pessi_cost_y_0_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int lipm_opti_pessi_cost_y_0_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int lipm_opti_pessi_cost_y_0_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
