/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) lipm_opti_pessi_cost_y_0_fun_jac_ut_xt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {22, 1, 1};
static const casadi_int casadi_s1[3] = {0, 1, 1};
static const casadi_int casadi_s2[3] = {0, 0, 1};
static const casadi_int casadi_s3[3] = {8, 1, 1};
static const casadi_int casadi_s4[3] = {40, 1, 1};
static const casadi_int casadi_s5[157] = 
  {44, 40, 0, 1, 2, 5, 6, 7,
  8, 9, 11, 13, 15, 17, 26, 35,
  44, 53, 54, 55, 56, 57, 57, 58,
  59, 62, 63, 64, 65, 66, 68, 70,
  72, 74, 83, 92, 101, 110, 111, 112,
  113, 114, 114, 22, 23, 24, 25, 26,
  25, 26, 27, 32, 0, 28, 1, 29,
  2, 30, 3, 31, 0, 4, 7, 22,
  24, 25, 27, 28, 30, 1, 4, 7,
  23, 24, 26, 27, 29, 31, 2, 4,
  7, 22, 24, 25, 27, 28, 30, 3,
  4, 7, 23, 24, 26, 27, 29, 31,
  4, 5, 6, 7, 33, 34, 35, 36,
  37, 36, 37, 38, 43, 11, 39, 12,
  40, 13, 41, 14, 42, 11, 15, 18,
  33, 35, 36, 38, 39, 41, 12, 15,
  18, 34, 35, 37, 38, 40, 42, 13,
  15, 18, 33, 35, 36, 38, 39, 41,
  14, 15, 18, 34, 35, 37, 38, 40,
  42, 15, 16, 17, 18};
static const casadi_int casadi_s6[3] = {40, 0, 1};

/* lipm_opti_pessi_cost_y_0_fun_jac_ut_xt:(i0[22],i1[22],i2[0],i3[],i4[8])->(o0[40],o1[44x40,114nz],o2[40x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39, a40, a41, a42, a43, a44, a45, a46, a47;
  casadi_real a48, a49, a50, a51, a52, a53, a54, a55, a56, a57, a58, a59;
  a00=arg[0]? arg[0][0] : 0;
  if (res[0]!=0) res[0][0]=a00;
  a01=arg[0]? arg[0][1] : 0;
  if (res[0]!=0) res[0][1]=a01;
  a02=arg[0]? arg[0][3] : 0;
  a03=casadi_sq(a02);
  a04=arg[0]? arg[0][4] : 0;
  a05=casadi_sq(a04);
  a06=(a03+a05);
  a07=arg[0]? arg[0][2] : 0;
  a08=cos(a07);
  a09=casadi_sq(a08);
  a10=(a06*a09);
  a10=(a10-a03);
  a03=sin(a07);
  a11=casadi_sq(a03);
  a12=(a06*a11);
  a12=(a12-a05);
  a10=(a10+a12);
  if (res[0]!=0) res[0][2]=a10;
  if (res[0]!=0) res[0][3]=a02;
  if (res[0]!=0) res[0][4]=a04;
  a10=arg[0]? arg[0][5] : 0;
  if (res[0]!=0) res[0][5]=a10;
  a12=arg[0]? arg[0][10] : 0;
  if (res[0]!=0) res[0][6]=a12;
  a12=arg[1]? arg[1][0] : 0;
  a05=arg[0]? arg[0][6] : 0;
  a13=(a12-a05);
  if (res[0]!=0) res[0][7]=a13;
  a13=arg[1]? arg[1][1] : 0;
  a14=arg[0]? arg[0][7] : 0;
  a15=(a13-a14);
  if (res[0]!=0) res[0][8]=a15;
  a15=arg[1]? arg[1][2] : 0;
  a16=arg[0]? arg[0][8] : 0;
  a17=(a15-a16);
  if (res[0]!=0) res[0][9]=a17;
  a17=arg[1]? arg[1][3] : 0;
  a18=arg[0]? arg[0][9] : 0;
  a19=(a17-a18);
  if (res[0]!=0) res[0][10]=a19;
  a19=5.0809240767486585e+00;
  a20=arg[1]? arg[1][7] : 0;
  a21=(a19*a20);
  a22=cosh(a21);
  a23=(a22*a00);
  a21=sinh(a21);
  a24=(a21/a19);
  a25=(a24*a02);
  a23=(a23+a25);
  a25=1.;
  a26=(a25-a22);
  a27=arg[1]? arg[1][4] : 0;
  a16=(a16-a05);
  a28=(a27*a16);
  a05=(a05+a28);
  a28=(a26*a05);
  a23=(a23+a28);
  a28=(a10*a20);
  a07=(a07+a28);
  a28=cos(a07);
  a29=arg[4]? arg[4][0] : 0;
  a30=(a28*a29);
  a07=sin(a07);
  a31=arg[4]? arg[4][1] : 0;
  a32=(a07*a31);
  a30=(a30-a32);
  a30=(a23+a30);
  a12=(a12-a30);
  if (res[0]!=0) res[0][11]=a12;
  a12=(a22*a01);
  a30=(a24*a04);
  a12=(a12+a30);
  a18=(a18-a14);
  a30=(a27*a18);
  a14=(a14+a30);
  a30=(a26*a14);
  a12=(a12+a30);
  a30=(a07*a29);
  a32=(a28*a31);
  a30=(a30+a32);
  a30=(a12+a30);
  a13=(a13-a30);
  if (res[0]!=0) res[0][12]=a13;
  a13=arg[4]? arg[4][2] : 0;
  a30=(a28*a13);
  a32=arg[4]? arg[4][3] : 0;
  a33=(a07*a32);
  a30=(a30-a33);
  a23=(a23+a30);
  a15=(a15-a23);
  if (res[0]!=0) res[0][13]=a15;
  a15=(a07*a13);
  a23=(a28*a32);
  a15=(a15+a23);
  a12=(a12+a15);
  a17=(a17-a12);
  if (res[0]!=0) res[0][14]=a17;
  a17=5.0000000000000000e-01;
  a12=(a27-a17);
  if (res[0]!=0) res[0][15]=a12;
  a12=arg[1]? arg[1][5] : 0;
  if (res[0]!=0) res[0][16]=a12;
  a12=arg[1]? arg[1][6] : 0;
  if (res[0]!=0) res[0][17]=a12;
  a12=1.8750000000000003e-02;
  a15=(a20-a12);
  if (res[0]!=0) res[0][18]=a15;
  a15=0.;
  if (res[0]!=0) res[0][19]=a15;
  a23=arg[0]? arg[0][11] : 0;
  if (res[0]!=0) res[0][20]=a23;
  a30=arg[0]? arg[0][12] : 0;
  if (res[0]!=0) res[0][21]=a30;
  a33=arg[0]? arg[0][14] : 0;
  a34=casadi_sq(a33);
  a35=arg[0]? arg[0][15] : 0;
  a36=casadi_sq(a35);
  a37=(a34+a36);
  a38=arg[0]? arg[0][13] : 0;
  a39=cos(a38);
  a40=casadi_sq(a39);
  a41=(a37*a40);
  a41=(a41-a34);
  a34=sin(a38);
  a42=casadi_sq(a34);
  a43=(a37*a42);
  a43=(a43-a36);
  a41=(a41+a43);
  if (res[0]!=0) res[0][22]=a41;
  if (res[0]!=0) res[0][23]=a33;
  if (res[0]!=0) res[0][24]=a35;
  a41=arg[0]? arg[0][16] : 0;
  if (res[0]!=0) res[0][25]=a41;
  a43=arg[0]? arg[0][21] : 0;
  if (res[0]!=0) res[0][26]=a43;
  a43=arg[1]? arg[1][11] : 0;
  a36=arg[0]? arg[0][17] : 0;
  a44=(a43-a36);
  if (res[0]!=0) res[0][27]=a44;
  a44=arg[1]? arg[1][12] : 0;
  a45=arg[0]? arg[0][18] : 0;
  a46=(a44-a45);
  if (res[0]!=0) res[0][28]=a46;
  a46=arg[1]? arg[1][13] : 0;
  a47=arg[0]? arg[0][19] : 0;
  a48=(a46-a47);
  if (res[0]!=0) res[0][29]=a48;
  a48=arg[1]? arg[1][14] : 0;
  a49=arg[0]? arg[0][20] : 0;
  a50=(a48-a49);
  if (res[0]!=0) res[0][30]=a50;
  a50=arg[1]? arg[1][18] : 0;
  a51=(a19*a50);
  a52=cosh(a51);
  a53=(a52*a23);
  a51=sinh(a51);
  a54=(a51/a19);
  a55=(a54*a33);
  a53=(a53+a55);
  a55=(a25-a52);
  a56=arg[1]? arg[1][15] : 0;
  a47=(a47-a36);
  a57=(a56*a47);
  a36=(a36+a57);
  a57=(a55*a36);
  a53=(a53+a57);
  a57=(a41*a50);
  a38=(a38+a57);
  a57=cos(a38);
  a58=(a57*a29);
  a38=sin(a38);
  a59=(a38*a31);
  a58=(a58-a59);
  a58=(a53+a58);
  a43=(a43-a58);
  if (res[0]!=0) res[0][31]=a43;
  a43=(a52*a30);
  a58=(a54*a35);
  a43=(a43+a58);
  a49=(a49-a45);
  a58=(a56*a49);
  a45=(a45+a58);
  a58=(a55*a45);
  a43=(a43+a58);
  a58=(a38*a29);
  a59=(a57*a31);
  a58=(a58+a59);
  a58=(a43+a58);
  a44=(a44-a58);
  if (res[0]!=0) res[0][32]=a44;
  a44=(a57*a13);
  a58=(a38*a32);
  a44=(a44-a58);
  a53=(a53+a44);
  a46=(a46-a53);
  if (res[0]!=0) res[0][33]=a46;
  a46=(a38*a13);
  a53=(a57*a32);
  a46=(a46+a53);
  a43=(a43+a46);
  a48=(a48-a43);
  if (res[0]!=0) res[0][34]=a48;
  a17=(a56-a17);
  if (res[0]!=0) res[0][35]=a17;
  a17=arg[1]? arg[1][16] : 0;
  if (res[0]!=0) res[0][36]=a17;
  a17=arg[1]? arg[1][17] : 0;
  if (res[0]!=0) res[0][37]=a17;
  a12=(a50-a12);
  if (res[0]!=0) res[0][38]=a12;
  if (res[0]!=0) res[0][39]=a15;
  if (res[1]!=0) res[1][0]=a25;
  if (res[1]!=0) res[1][1]=a25;
  a15=(a03+a03);
  a15=(a15*a08);
  a15=(a06*a15);
  a08=(a08+a08);
  a08=(a08*a03);
  a06=(a06*a08);
  a15=(a15-a06);
  if (res[1]!=0) res[1][2]=a15;
  a15=(a02+a02);
  a06=(a09*a15);
  a06=(a06-a15);
  a15=(a11*a15);
  a06=(a06+a15);
  if (res[1]!=0) res[1][3]=a06;
  a06=(a04+a04);
  a09=(a09*a06);
  a11=(a11*a06);
  a11=(a11-a06);
  a09=(a09+a11);
  if (res[1]!=0) res[1][4]=a09;
  if (res[1]!=0) res[1][5]=a25;
  if (res[1]!=0) res[1][6]=a25;
  if (res[1]!=0) res[1][7]=a25;
  if (res[1]!=0) res[1][8]=a25;
  if (res[1]!=0) res[1][9]=a25;
  a09=-1.;
  if (res[1]!=0) res[1][10]=a09;
  if (res[1]!=0) res[1][11]=a25;
  if (res[1]!=0) res[1][12]=a09;
  if (res[1]!=0) res[1][13]=a25;
  if (res[1]!=0) res[1][14]=a09;
  if (res[1]!=0) res[1][15]=a25;
  if (res[1]!=0) res[1][16]=a09;
  if (res[1]!=0) res[1][17]=a25;
  a16=(a26*a16);
  a16=(-a16);
  if (res[1]!=0) res[1][18]=a16;
  a21=(a19*a21);
  a00=(a00*a21);
  a02=(a02*a22);
  a00=(a00+a02);
  a05=(a05*a21);
  a00=(a00-a05);
  a05=(a07*a10);
  a02=(a29*a05);
  a10=(a28*a10);
  a11=(a31*a10);
  a02=(a02+a11);
  a02=(a00-a02);
  a02=(-a02);
  if (res[1]!=0) res[1][19]=a02;
  a02=(-a22);
  if (res[1]!=0) res[1][20]=a02;
  a11=(a29*a07);
  a06=(a31*a28);
  a11=(a11+a06);
  if (res[1]!=0) res[1][21]=a11;
  a24=(-a24);
  if (res[1]!=0) res[1][22]=a24;
  a11=(a07*a20);
  a06=(a29*a11);
  a20=(a28*a20);
  a15=(a31*a20);
  a06=(a06+a15);
  if (res[1]!=0) res[1][23]=a06;
  a06=(a25-a27);
  a06=(a26*a06);
  a06=(-a06);
  if (res[1]!=0) res[1][24]=a06;
  a27=(a26*a27);
  a27=(-a27);
  if (res[1]!=0) res[1][25]=a27;
  if (res[1]!=0) res[1][26]=a25;
  a26=(a26*a18);
  a26=(-a26);
  if (res[1]!=0) res[1][27]=a26;
  a01=(a01*a21);
  a04=(a04*a22);
  a01=(a01+a04);
  a14=(a14*a21);
  a01=(a01-a14);
  a14=(a29*a10);
  a21=(a31*a05);
  a14=(a14-a21);
  a14=(a01+a14);
  a14=(-a14);
  if (res[1]!=0) res[1][28]=a14;
  if (res[1]!=0) res[1][29]=a02;
  a14=(a29*a28);
  a21=(a31*a07);
  a14=(a14-a21);
  a14=(-a14);
  if (res[1]!=0) res[1][30]=a14;
  if (res[1]!=0) res[1][31]=a24;
  a14=(a29*a20);
  a21=(a31*a11);
  a14=(a14-a21);
  a14=(-a14);
  if (res[1]!=0) res[1][32]=a14;
  if (res[1]!=0) res[1][33]=a06;
  if (res[1]!=0) res[1][34]=a27;
  if (res[1]!=0) res[1][35]=a25;
  if (res[1]!=0) res[1][36]=a16;
  a16=(a13*a05);
  a14=(a32*a10);
  a16=(a16+a14);
  a00=(a00-a16);
  a00=(-a00);
  if (res[1]!=0) res[1][37]=a00;
  if (res[1]!=0) res[1][38]=a02;
  a00=(a13*a07);
  a16=(a32*a28);
  a00=(a00+a16);
  if (res[1]!=0) res[1][39]=a00;
  if (res[1]!=0) res[1][40]=a24;
  a00=(a13*a11);
  a16=(a32*a20);
  a00=(a00+a16);
  if (res[1]!=0) res[1][41]=a00;
  if (res[1]!=0) res[1][42]=a06;
  if (res[1]!=0) res[1][43]=a27;
  if (res[1]!=0) res[1][44]=a25;
  if (res[1]!=0) res[1][45]=a26;
  a10=(a13*a10);
  a05=(a32*a05);
  a10=(a10-a05);
  a01=(a01+a10);
  a01=(-a01);
  if (res[1]!=0) res[1][46]=a01;
  if (res[1]!=0) res[1][47]=a02;
  a28=(a13*a28);
  a07=(a32*a07);
  a28=(a28-a07);
  a28=(-a28);
  if (res[1]!=0) res[1][48]=a28;
  if (res[1]!=0) res[1][49]=a24;
  a20=(a13*a20);
  a11=(a32*a11);
  a20=(a20-a11);
  a20=(-a20);
  if (res[1]!=0) res[1][50]=a20;
  if (res[1]!=0) res[1][51]=a06;
  if (res[1]!=0) res[1][52]=a27;
  if (res[1]!=0) res[1][53]=a25;
  if (res[1]!=0) res[1][54]=a25;
  if (res[1]!=0) res[1][55]=a25;
  if (res[1]!=0) res[1][56]=a25;
  if (res[1]!=0) res[1][57]=a25;
  if (res[1]!=0) res[1][58]=a25;
  a27=(a34+a34);
  a27=(a27*a39);
  a27=(a37*a27);
  a39=(a39+a39);
  a39=(a39*a34);
  a37=(a37*a39);
  a27=(a27-a37);
  if (res[1]!=0) res[1][59]=a27;
  a27=(a33+a33);
  a37=(a40*a27);
  a37=(a37-a27);
  a27=(a42*a27);
  a37=(a37+a27);
  if (res[1]!=0) res[1][60]=a37;
  a37=(a35+a35);
  a40=(a40*a37);
  a42=(a42*a37);
  a42=(a42-a37);
  a40=(a40+a42);
  if (res[1]!=0) res[1][61]=a40;
  if (res[1]!=0) res[1][62]=a25;
  if (res[1]!=0) res[1][63]=a25;
  if (res[1]!=0) res[1][64]=a25;
  if (res[1]!=0) res[1][65]=a25;
  if (res[1]!=0) res[1][66]=a25;
  if (res[1]!=0) res[1][67]=a09;
  if (res[1]!=0) res[1][68]=a25;
  if (res[1]!=0) res[1][69]=a09;
  if (res[1]!=0) res[1][70]=a25;
  if (res[1]!=0) res[1][71]=a09;
  if (res[1]!=0) res[1][72]=a25;
  if (res[1]!=0) res[1][73]=a09;
  if (res[1]!=0) res[1][74]=a25;
  a47=(a55*a47);
  a47=(-a47);
  if (res[1]!=0) res[1][75]=a47;
  a19=(a19*a51);
  a23=(a23*a19);
  a33=(a33*a52);
  a23=(a23+a33);
  a36=(a36*a19);
  a23=(a23-a36);
  a36=(a38*a41);
  a33=(a29*a36);
  a41=(a57*a41);
  a51=(a31*a41);
  a33=(a33+a51);
  a33=(a23-a33);
  a33=(-a33);
  if (res[1]!=0) res[1][76]=a33;
  a33=(-a52);
  if (res[1]!=0) res[1][77]=a33;
  a51=(a29*a38);
  a09=(a31*a57);
  a51=(a51+a09);
  if (res[1]!=0) res[1][78]=a51;
  a54=(-a54);
  if (res[1]!=0) res[1][79]=a54;
  a51=(a38*a50);
  a09=(a29*a51);
  a50=(a57*a50);
  a40=(a31*a50);
  a09=(a09+a40);
  if (res[1]!=0) res[1][80]=a09;
  a09=(a25-a56);
  a09=(a55*a09);
  a09=(-a09);
  if (res[1]!=0) res[1][81]=a09;
  a56=(a55*a56);
  a56=(-a56);
  if (res[1]!=0) res[1][82]=a56;
  if (res[1]!=0) res[1][83]=a25;
  a55=(a55*a49);
  a55=(-a55);
  if (res[1]!=0) res[1][84]=a55;
  a30=(a30*a19);
  a35=(a35*a52);
  a30=(a30+a35);
  a45=(a45*a19);
  a30=(a30-a45);
  a45=(a29*a41);
  a19=(a31*a36);
  a45=(a45-a19);
  a45=(a30+a45);
  a45=(-a45);
  if (res[1]!=0) res[1][85]=a45;
  if (res[1]!=0) res[1][86]=a33;
  a45=(a29*a57);
  a19=(a31*a38);
  a45=(a45-a19);
  a45=(-a45);
  if (res[1]!=0) res[1][87]=a45;
  if (res[1]!=0) res[1][88]=a54;
  a29=(a29*a50);
  a31=(a31*a51);
  a29=(a29-a31);
  a29=(-a29);
  if (res[1]!=0) res[1][89]=a29;
  if (res[1]!=0) res[1][90]=a09;
  if (res[1]!=0) res[1][91]=a56;
  if (res[1]!=0) res[1][92]=a25;
  if (res[1]!=0) res[1][93]=a47;
  a47=(a13*a36);
  a29=(a32*a41);
  a47=(a47+a29);
  a23=(a23-a47);
  a23=(-a23);
  if (res[1]!=0) res[1][94]=a23;
  if (res[1]!=0) res[1][95]=a33;
  a23=(a13*a38);
  a47=(a32*a57);
  a23=(a23+a47);
  if (res[1]!=0) res[1][96]=a23;
  if (res[1]!=0) res[1][97]=a54;
  a23=(a13*a51);
  a47=(a32*a50);
  a23=(a23+a47);
  if (res[1]!=0) res[1][98]=a23;
  if (res[1]!=0) res[1][99]=a09;
  if (res[1]!=0) res[1][100]=a56;
  if (res[1]!=0) res[1][101]=a25;
  if (res[1]!=0) res[1][102]=a55;
  a41=(a13*a41);
  a36=(a32*a36);
  a41=(a41-a36);
  a30=(a30+a41);
  a30=(-a30);
  if (res[1]!=0) res[1][103]=a30;
  if (res[1]!=0) res[1][104]=a33;
  a57=(a13*a57);
  a38=(a32*a38);
  a57=(a57-a38);
  a57=(-a57);
  if (res[1]!=0) res[1][105]=a57;
  if (res[1]!=0) res[1][106]=a54;
  a13=(a13*a50);
  a32=(a32*a51);
  a13=(a13-a32);
  a13=(-a13);
  if (res[1]!=0) res[1][107]=a13;
  if (res[1]!=0) res[1][108]=a09;
  if (res[1]!=0) res[1][109]=a56;
  if (res[1]!=0) res[1][110]=a25;
  if (res[1]!=0) res[1][111]=a25;
  if (res[1]!=0) res[1][112]=a25;
  if (res[1]!=0) res[1][113]=a25;
  return 0;
}

CASADI_SYMBOL_EXPORT int lipm_opti_pessi_cost_y_0_fun_jac_ut_xt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int lipm_opti_pessi_cost_y_0_fun_jac_ut_xt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int lipm_opti_pessi_cost_y_0_fun_jac_ut_xt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void lipm_opti_pessi_cost_y_0_fun_jac_ut_xt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int lipm_opti_pessi_cost_y_0_fun_jac_ut_xt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void lipm_opti_pessi_cost_y_0_fun_jac_ut_xt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void lipm_opti_pessi_cost_y_0_fun_jac_ut_xt_incref(void) {
}

CASADI_SYMBOL_EXPORT void lipm_opti_pessi_cost_y_0_fun_jac_ut_xt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int lipm_opti_pessi_cost_y_0_fun_jac_ut_xt_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int lipm_opti_pessi_cost_y_0_fun_jac_ut_xt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real lipm_opti_pessi_cost_y_0_fun_jac_ut_xt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* lipm_opti_pessi_cost_y_0_fun_jac_ut_xt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* lipm_opti_pessi_cost_y_0_fun_jac_ut_xt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* lipm_opti_pessi_cost_y_0_fun_jac_ut_xt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    case 4: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* lipm_opti_pessi_cost_y_0_fun_jac_ut_xt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    case 2: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int lipm_opti_pessi_cost_y_0_fun_jac_ut_xt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int lipm_opti_pessi_cost_y_0_fun_jac_ut_xt_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
