/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) lipm_opti_pessi_cost_y_0_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {22, 1, 1};
static const casadi_int casadi_s1[3] = {0, 1, 1};
static const casadi_int casadi_s2[3] = {34, 1, 1};
static const casadi_int casadi_s3[3] = {0, 0, 1};
static const casadi_int casadi_s4[3] = {8, 1, 1};
static const casadi_int casadi_s5[133] = 
  {44, 44, 0, 0, 0, 0, 0, 5,
  5, 5, 17, 17, 17, 17, 17, 17,
  17, 17, 22, 22, 22, 34, 34, 34,
  34, 35, 36, 41, 45, 49, 52, 54,
  56, 58, 60, 60, 61, 62, 67, 71,
  75, 78, 80, 82, 84, 86, 86, 7,
  28, 29, 30, 31, 4, 7, 22, 23,
  24, 25, 26, 27, 28, 29, 30, 31,
  18, 39, 40, 41, 42, 15, 18, 33,
  34, 35, 36, 37, 38, 39, 40, 41,
  42, 7, 7, 7, 24, 25, 26, 27,
  7, 24, 25, 26, 7, 24, 25, 26,
  7, 24, 27, 4, 7, 4, 7, 4,
  7, 4, 7, 18, 18, 18, 35, 36,
  37, 38, 18, 35, 36, 37, 18, 35,
  36, 37, 18, 35, 38, 15, 18, 15,
  18, 15, 18, 15, 18};

/* lipm_opti_pessi_cost_y_0_hess:(i0[22],i1[22],i2[0],i3[34],i4[],i5[8])->(o0[44x44,86nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39, a40, a41, a42, a43, a44, a45, a46, a47;
  casadi_real a48, a49, a50, a51, a52, a53, a54, a55, a56, a57, a58, a59;
  casadi_real a60, a61, a62;
  a00=arg[0]? arg[0][9] : 0;
  a01=arg[0]? arg[0][7] : 0;
  a00=(a00-a01);
  a02=arg[3]? arg[3][14] : 0;
  a03=arg[3]? arg[3][12] : 0;
  a04=(a02+a03);
  a05=5.0809240767486585e+00;
  a06=arg[1]? arg[1][7] : 0;
  a07=(a05*a06);
  a08=sinh(a07);
  a08=(a05*a08);
  a09=(a04*a08);
  a10=(a00*a09);
  a11=arg[0]? arg[0][8] : 0;
  a12=arg[0]? arg[0][6] : 0;
  a11=(a11-a12);
  a13=arg[3]? arg[3][13] : 0;
  a14=arg[3]? arg[3][11] : 0;
  a15=(a13+a14);
  a16=(a15*a08);
  a17=(a11*a16);
  a10=(a10+a17);
  if (res[0]!=0) res[0][0]=a10;
  a17=1.;
  a07=cosh(a07);
  a18=(a17-a07);
  a19=(a18*a15);
  if (res[0]!=0) res[0][1]=a19;
  a18=(a18*a04);
  if (res[0]!=0) res[0][2]=a18;
  a20=(-a19);
  if (res[0]!=0) res[0][3]=a20;
  a21=(-a18);
  if (res[0]!=0) res[0][4]=a21;
  if (res[0]!=0) res[0][5]=a10;
  a10=arg[0]? arg[0][5] : 0;
  a22=arg[5]? arg[5][3] : 0;
  a23=(a22*a02);
  a24=arg[5]? arg[5][1] : 0;
  a25=(a24*a03);
  a23=(a23+a25);
  a25=arg[0]? arg[0][2] : 0;
  a26=(a10*a06);
  a26=(a25+a26);
  a27=cos(a26);
  a28=(a27*a10);
  a29=(a23*a28);
  a30=arg[5]? arg[5][2] : 0;
  a02=(a30*a02);
  a31=arg[5]? arg[5][0] : 0;
  a03=(a31*a03);
  a02=(a02+a03);
  a26=sin(a26);
  a03=(a26*a10);
  a32=(a02*a03);
  a29=(a29+a32);
  a32=(a22*a13);
  a33=(a24*a14);
  a32=(a32+a33);
  a03=(a32*a03);
  a29=(a29-a03);
  a13=(a30*a13);
  a14=(a31*a14);
  a13=(a13+a14);
  a28=(a13*a28);
  a29=(a29+a28);
  a10=(a10*a29);
  a28=1.9681459216763408e-01;
  a14=arg[0]? arg[0][4] : 0;
  a03=(a14*a04);
  a33=arg[0]? arg[0][3] : 0;
  a34=(a33*a15);
  a03=(a03+a34);
  a03=(a28*a03);
  a03=(a03*a08);
  a03=(a05*a03);
  a10=(a10-a03);
  a03=arg[1]? arg[1][4] : 0;
  a00=(a03*a00);
  a01=(a01+a00);
  a01=(a01*a04);
  a11=(a03*a11);
  a12=(a12+a11);
  a12=(a12*a15);
  a01=(a01+a12);
  a12=arg[0]? arg[0][1] : 0;
  a12=(a12*a04);
  a01=(a01-a12);
  a12=arg[0]? arg[0][0] : 0;
  a12=(a12*a15);
  a01=(a01-a12);
  a12=(a05*a07);
  a01=(a01*a12);
  a01=(a05*a01);
  a10=(a10+a01);
  if (res[0]!=0) res[0][6]=a10;
  a10=(-a16);
  if (res[0]!=0) res[0][7]=a10;
  a01=(-a09);
  if (res[0]!=0) res[0][8]=a01;
  if (res[0]!=0) res[0][9]=a29;
  a15=(a15*a07);
  a15=(-a15);
  if (res[0]!=0) res[0][10]=a15;
  a04=(a28*a04);
  a07=(a07*a04);
  a07=(a05*a07);
  a07=(-a07);
  if (res[0]!=0) res[0][11]=a07;
  a04=(a26*a23);
  a12=(a27*a02);
  a04=(a04-a12);
  a12=(a27*a32);
  a04=(a04+a12);
  a12=(a26*a13);
  a04=(a04+a12);
  a12=(a06*a29);
  a04=(a04+a12);
  if (res[0]!=0) res[0][12]=a04;
  a12=(a03*a16);
  a16=(a16-a12);
  if (res[0]!=0) res[0][13]=a16;
  a03=(a03*a09);
  a09=(a09-a03);
  if (res[0]!=0) res[0][14]=a09;
  if (res[0]!=0) res[0][15]=a12;
  if (res[0]!=0) res[0][16]=a03;
  a11=arg[0]? arg[0][20] : 0;
  a00=arg[0]? arg[0][18] : 0;
  a11=(a11-a00);
  a08=arg[3]? arg[3][31] : 0;
  a34=arg[3]? arg[3][29] : 0;
  a35=(a08+a34);
  a36=arg[1]? arg[1][18] : 0;
  a37=(a05*a36);
  a38=sinh(a37);
  a38=(a05*a38);
  a39=(a35*a38);
  a40=(a11*a39);
  a41=arg[0]? arg[0][19] : 0;
  a42=arg[0]? arg[0][17] : 0;
  a41=(a41-a42);
  a43=arg[3]? arg[3][30] : 0;
  a44=arg[3]? arg[3][28] : 0;
  a45=(a43+a44);
  a46=(a45*a38);
  a47=(a41*a46);
  a40=(a40+a47);
  if (res[0]!=0) res[0][17]=a40;
  a37=cosh(a37);
  a17=(a17-a37);
  a47=(a17*a45);
  if (res[0]!=0) res[0][18]=a47;
  a17=(a17*a35);
  if (res[0]!=0) res[0][19]=a17;
  a48=(-a47);
  if (res[0]!=0) res[0][20]=a48;
  a49=(-a17);
  if (res[0]!=0) res[0][21]=a49;
  if (res[0]!=0) res[0][22]=a40;
  a40=arg[0]? arg[0][16] : 0;
  a50=(a22*a08);
  a51=(a24*a34);
  a50=(a50+a51);
  a51=arg[0]? arg[0][13] : 0;
  a52=(a40*a36);
  a52=(a51+a52);
  a53=cos(a52);
  a54=(a53*a40);
  a55=(a50*a54);
  a08=(a30*a08);
  a34=(a31*a34);
  a08=(a08+a34);
  a52=sin(a52);
  a34=(a52*a40);
  a56=(a08*a34);
  a55=(a55+a56);
  a22=(a22*a43);
  a24=(a24*a44);
  a22=(a22+a24);
  a34=(a22*a34);
  a55=(a55-a34);
  a30=(a30*a43);
  a31=(a31*a44);
  a30=(a30+a31);
  a54=(a30*a54);
  a55=(a55+a54);
  a40=(a40*a55);
  a54=arg[0]? arg[0][15] : 0;
  a31=(a54*a35);
  a44=arg[0]? arg[0][14] : 0;
  a43=(a44*a45);
  a31=(a31+a43);
  a31=(a28*a31);
  a31=(a31*a38);
  a31=(a05*a31);
  a40=(a40-a31);
  a31=arg[1]? arg[1][15] : 0;
  a11=(a31*a11);
  a00=(a00+a11);
  a00=(a00*a35);
  a41=(a31*a41);
  a42=(a42+a41);
  a42=(a42*a45);
  a00=(a00+a42);
  a42=arg[0]? arg[0][12] : 0;
  a42=(a42*a35);
  a00=(a00-a42);
  a42=arg[0]? arg[0][11] : 0;
  a42=(a42*a45);
  a00=(a00-a42);
  a42=(a05*a37);
  a00=(a00*a42);
  a00=(a05*a00);
  a40=(a40+a00);
  if (res[0]!=0) res[0][23]=a40;
  a40=(-a46);
  if (res[0]!=0) res[0][24]=a40;
  a00=(-a39);
  if (res[0]!=0) res[0][25]=a00;
  if (res[0]!=0) res[0][26]=a55;
  a45=(a45*a37);
  a45=(-a45);
  if (res[0]!=0) res[0][27]=a45;
  a28=(a28*a35);
  a37=(a37*a28);
  a05=(a05*a37);
  a05=(-a05);
  if (res[0]!=0) res[0][28]=a05;
  a37=(a52*a50);
  a28=(a53*a08);
  a37=(a37-a28);
  a28=(a53*a22);
  a37=(a37+a28);
  a28=(a52*a30);
  a37=(a37+a28);
  a28=(a36*a55);
  a37=(a37+a28);
  if (res[0]!=0) res[0][29]=a37;
  a28=(a31*a46);
  a46=(a46-a28);
  if (res[0]!=0) res[0][30]=a46;
  a31=(a31*a39);
  a39=(a39-a31);
  if (res[0]!=0) res[0][31]=a39;
  if (res[0]!=0) res[0][32]=a28;
  if (res[0]!=0) res[0][33]=a31;
  if (res[0]!=0) res[0][34]=a10;
  if (res[0]!=0) res[0][35]=a01;
  if (res[0]!=0) res[0][36]=a29;
  a29=(a23*a27);
  a01=(a02*a26);
  a29=(a29+a01);
  a01=(a32*a26);
  a29=(a29-a01);
  a01=(a13*a27);
  a29=(a29+a01);
  a01=cos(a25);
  a10=casadi_sq(a33);
  a35=casadi_sq(a14);
  a42=(a10+a35);
  a25=sin(a25);
  a41=casadi_sq(a25);
  a11=(a42*a41);
  a11=(a11-a35);
  a11=(a11+a11);
  a35=arg[3]? arg[3][2] : 0;
  a11=(a11*a35);
  a38=(a42*a11);
  a43=(a01+a01);
  a34=(a38*a43);
  a24=(a25+a25);
  a56=(a24*a01);
  a57=(a42*a56);
  a57=(a57+a57);
  a57=(a35*a57);
  a58=(a42*a57);
  a58=(a24*a58);
  a34=(a34+a58);
  a34=(a01*a34);
  a38=(a24*a38);
  a38=(a38*a25);
  a34=(a34-a38);
  a34=(a29+a34);
  a38=casadi_sq(a01);
  a58=(a42*a38);
  a58=(a58-a10);
  a58=(a58+a58);
  a58=(a58*a35);
  a10=(a42*a58);
  a59=(a43*a10);
  a59=(a59*a01);
  a10=(a10*a24);
  a60=(a43*a25);
  a61=(a42*a60);
  a61=(a61+a61);
  a61=(a35*a61);
  a62=(a42*a61);
  a62=(a43*a62);
  a10=(a10+a62);
  a10=(a25*a10);
  a59=(a59-a10);
  a34=(a34-a59);
  if (res[0]!=0) res[0][37]=a34;
  a33=(a33+a33);
  a34=(a33*a61);
  a56=(a11*a56);
  a57=(a41*a57);
  a56=(a56+a57);
  a60=(a58*a60);
  a61=(a38*a61);
  a60=(a60+a61);
  a56=(a56-a60);
  a56=(a33*a56);
  a34=(a34+a56);
  if (res[0]!=0) res[0][38]=a34;
  a14=(a14+a14);
  a56=(a11*a14);
  a60=(a41*a14);
  a60=(a60-a14);
  a60=(a60+a60);
  a60=(a35*a60);
  a61=(a42*a60);
  a56=(a56+a61);
  a24=(a24*a56);
  a01=(a01*a24);
  a24=(a58*a14);
  a56=(a38*a14);
  a56=(a56+a56);
  a56=(a35*a56);
  a42=(a42*a56);
  a24=(a24+a42);
  a43=(a43*a24);
  a25=(a25*a43);
  a01=(a01-a25);
  if (res[0]!=0) res[0][39]=a01;
  a29=(a06*a29);
  if (res[0]!=0) res[0][40]=a29;
  if (res[0]!=0) res[0][41]=a15;
  if (res[0]!=0) res[0][42]=a34;
  a34=2.;
  a15=(a41*a11);
  a25=(a38*a58);
  a15=(a15+a25);
  a15=(a34*a15);
  a25=(a41*a33);
  a25=(a25+a25);
  a25=(a35*a25);
  a25=(a41*a25);
  a43=(a38*a33);
  a43=(a43-a33);
  a43=(a43+a43);
  a35=(a35*a43);
  a43=(a38*a35);
  a25=(a25+a43);
  a25=(a33*a25);
  a25=(a15+a25);
  a58=(a34*a58);
  a35=(a33*a35);
  a58=(a58+a35);
  a25=(a25-a58);
  if (res[0]!=0) res[0][43]=a25;
  a41=(a41*a60);
  a38=(a38*a56);
  a41=(a41+a38);
  a38=(a33*a41);
  a33=(a33*a56);
  a38=(a38-a33);
  if (res[0]!=0) res[0][44]=a38;
  if (res[0]!=0) res[0][45]=a07;
  if (res[0]!=0) res[0][46]=a01;
  if (res[0]!=0) res[0][47]=a38;
  a41=(a14*a41);
  a15=(a15+a41);
  a11=(a34*a11);
  a14=(a14*a60);
  a11=(a11+a14);
  a15=(a15-a11);
  if (res[0]!=0) res[0][48]=a15;
  if (res[0]!=0) res[0][49]=a04;
  if (res[0]!=0) res[0][50]=a29;
  a27=(a27*a06);
  a23=(a23*a27);
  a26=(a26*a06);
  a02=(a02*a26);
  a23=(a23+a02);
  a32=(a32*a26);
  a23=(a23-a32);
  a13=(a13*a27);
  a23=(a23+a13);
  a06=(a06*a23);
  if (res[0]!=0) res[0][51]=a06;
  if (res[0]!=0) res[0][52]=a19;
  if (res[0]!=0) res[0][53]=a16;
  if (res[0]!=0) res[0][54]=a18;
  if (res[0]!=0) res[0][55]=a09;
  if (res[0]!=0) res[0][56]=a20;
  if (res[0]!=0) res[0][57]=a12;
  if (res[0]!=0) res[0][58]=a21;
  if (res[0]!=0) res[0][59]=a03;
  if (res[0]!=0) res[0][60]=a40;
  if (res[0]!=0) res[0][61]=a00;
  if (res[0]!=0) res[0][62]=a55;
  a55=(a50*a53);
  a00=(a08*a52);
  a55=(a55+a00);
  a00=(a22*a52);
  a55=(a55-a00);
  a00=(a30*a53);
  a55=(a55+a00);
  a00=cos(a51);
  a40=casadi_sq(a44);
  a03=casadi_sq(a54);
  a21=(a40+a03);
  a51=sin(a51);
  a12=casadi_sq(a51);
  a20=(a21*a12);
  a20=(a20-a03);
  a20=(a20+a20);
  a03=arg[3]? arg[3][19] : 0;
  a20=(a20*a03);
  a09=(a21*a20);
  a18=(a00+a00);
  a16=(a09*a18);
  a19=(a51+a51);
  a06=(a19*a00);
  a23=(a21*a06);
  a23=(a23+a23);
  a23=(a03*a23);
  a13=(a21*a23);
  a13=(a19*a13);
  a16=(a16+a13);
  a16=(a00*a16);
  a09=(a19*a09);
  a09=(a09*a51);
  a16=(a16-a09);
  a16=(a55+a16);
  a09=casadi_sq(a00);
  a13=(a21*a09);
  a13=(a13-a40);
  a13=(a13+a13);
  a13=(a13*a03);
  a40=(a21*a13);
  a27=(a18*a40);
  a27=(a27*a00);
  a40=(a40*a19);
  a32=(a18*a51);
  a26=(a21*a32);
  a26=(a26+a26);
  a26=(a03*a26);
  a02=(a21*a26);
  a02=(a18*a02);
  a40=(a40+a02);
  a40=(a51*a40);
  a27=(a27-a40);
  a16=(a16-a27);
  if (res[0]!=0) res[0][63]=a16;
  a44=(a44+a44);
  a16=(a44*a26);
  a06=(a20*a06);
  a23=(a12*a23);
  a06=(a06+a23);
  a32=(a13*a32);
  a26=(a09*a26);
  a32=(a32+a26);
  a06=(a06-a32);
  a06=(a44*a06);
  a16=(a16+a06);
  if (res[0]!=0) res[0][64]=a16;
  a54=(a54+a54);
  a06=(a20*a54);
  a32=(a12*a54);
  a32=(a32-a54);
  a32=(a32+a32);
  a32=(a03*a32);
  a26=(a21*a32);
  a06=(a06+a26);
  a19=(a19*a06);
  a00=(a00*a19);
  a19=(a13*a54);
  a06=(a09*a54);
  a06=(a06+a06);
  a06=(a03*a06);
  a21=(a21*a06);
  a19=(a19+a21);
  a18=(a18*a19);
  a51=(a51*a18);
  a00=(a00-a51);
  if (res[0]!=0) res[0][65]=a00;
  a55=(a36*a55);
  if (res[0]!=0) res[0][66]=a55;
  if (res[0]!=0) res[0][67]=a45;
  if (res[0]!=0) res[0][68]=a16;
  a16=(a12*a20);
  a45=(a09*a13);
  a16=(a16+a45);
  a16=(a34*a16);
  a45=(a12*a44);
  a45=(a45+a45);
  a45=(a03*a45);
  a45=(a12*a45);
  a51=(a09*a44);
  a51=(a51-a44);
  a51=(a51+a51);
  a03=(a03*a51);
  a51=(a09*a03);
  a45=(a45+a51);
  a45=(a44*a45);
  a45=(a16+a45);
  a13=(a34*a13);
  a03=(a44*a03);
  a13=(a13+a03);
  a45=(a45-a13);
  if (res[0]!=0) res[0][69]=a45;
  a12=(a12*a32);
  a09=(a09*a06);
  a12=(a12+a09);
  a09=(a44*a12);
  a44=(a44*a06);
  a09=(a09-a44);
  if (res[0]!=0) res[0][70]=a09;
  if (res[0]!=0) res[0][71]=a05;
  if (res[0]!=0) res[0][72]=a00;
  if (res[0]!=0) res[0][73]=a09;
  a12=(a54*a12);
  a16=(a16+a12);
  a34=(a34*a20);
  a54=(a54*a32);
  a34=(a34+a54);
  a16=(a16-a34);
  if (res[0]!=0) res[0][74]=a16;
  if (res[0]!=0) res[0][75]=a37;
  if (res[0]!=0) res[0][76]=a55;
  a53=(a53*a36);
  a50=(a50*a53);
  a52=(a52*a36);
  a08=(a08*a52);
  a50=(a50+a08);
  a22=(a22*a52);
  a50=(a50-a22);
  a30=(a30*a53);
  a50=(a50+a30);
  a36=(a36*a50);
  if (res[0]!=0) res[0][77]=a36;
  if (res[0]!=0) res[0][78]=a47;
  if (res[0]!=0) res[0][79]=a46;
  if (res[0]!=0) res[0][80]=a17;
  if (res[0]!=0) res[0][81]=a39;
  if (res[0]!=0) res[0][82]=a48;
  if (res[0]!=0) res[0][83]=a28;
  if (res[0]!=0) res[0][84]=a49;
  if (res[0]!=0) res[0][85]=a31;
  return 0;
}

CASADI_SYMBOL_EXPORT int lipm_opti_pessi_cost_y_0_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int lipm_opti_pessi_cost_y_0_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int lipm_opti_pessi_cost_y_0_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void lipm_opti_pessi_cost_y_0_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int lipm_opti_pessi_cost_y_0_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void lipm_opti_pessi_cost_y_0_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void lipm_opti_pessi_cost_y_0_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void lipm_opti_pessi_cost_y_0_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int lipm_opti_pessi_cost_y_0_hess_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int lipm_opti_pessi_cost_y_0_hess_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real lipm_opti_pessi_cost_y_0_hess_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* lipm_opti_pessi_cost_y_0_hess_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* lipm_opti_pessi_cost_y_0_hess_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* lipm_opti_pessi_cost_y_0_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    case 4: return casadi_s3;
    case 5: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* lipm_opti_pessi_cost_y_0_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int lipm_opti_pessi_cost_y_0_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int lipm_opti_pessi_cost_y_0_hess_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
