/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) lipm_opti_pessi_cost_y_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {22, 1, 1};
static const casadi_int casadi_s1[3] = {0, 1, 1};
static const casadi_int casadi_s2[3] = {40, 1, 1};
static const casadi_int casadi_s3[3] = {0, 0, 1};
static const casadi_int casadi_s4[3] = {8, 1, 1};
static const casadi_int casadi_s5[157] = 
  {44, 44, 0, 0, 0, 0, 0, 5,
  5, 5, 17, 17, 17, 17, 17, 17,
  17, 17, 22, 22, 22, 34, 34, 34,
  34, 40, 46, 53, 57, 61, 64, 66,
  68, 70, 72, 72, 78, 84, 91, 95,
  99, 102, 104, 106, 108, 110, 110, 7,
  28, 29, 30, 31, 4, 7, 22, 23,
  24, 25, 26, 27, 28, 29, 30, 31,
  18, 39, 40, 41, 42, 15, 18, 33,
  34, 35, 36, 37, 38, 39, 40, 41,
  42, 7, 22, 23, 24, 25, 26, 7,
  22, 23, 24, 25, 26, 7, 22, 23,
  24, 25, 26, 27, 7, 22, 23, 24,
  7, 22, 23, 24, 7, 24, 27, 4,
  7, 4, 7, 4, 7, 4, 7, 18,
  33, 34, 35, 36, 37, 18, 33, 34,
  35, 36, 37, 18, 33, 34, 35, 36,
  37, 38, 18, 33, 34, 35, 18, 33,
  34, 35, 18, 35, 38, 15, 18, 15,
  18, 15, 18, 15, 18};

/* lipm_opti_pessi_cost_y_hess:(i0[22],i1[22],i2[0],i3[40],i4[],i5[8])->(o0[44x44,110nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39, a40, a41, a42, a43, a44, a45, a46, a47;
  casadi_real a48, a49, a50, a51, a52, a53, a54, a55, a56, a57, a58, a59;
  casadi_real a60, a61, a62, a63, a64, a65, a66, a67, a68;
  a00=arg[0]? arg[0][9] : 0;
  a01=arg[0]? arg[0][7] : 0;
  a00=(a00-a01);
  a02=arg[3]? arg[3][14] : 0;
  a03=arg[3]? arg[3][12] : 0;
  a04=(a02+a03);
  a05=5.0809240767486585e+00;
  a06=arg[1]? arg[1][7] : 0;
  a07=(a05*a06);
  a08=sinh(a07);
  a09=(a05*a08);
  a10=(a04*a09);
  a11=(a00*a10);
  a12=arg[0]? arg[0][8] : 0;
  a13=arg[0]? arg[0][6] : 0;
  a12=(a12-a13);
  a14=arg[3]? arg[3][13] : 0;
  a15=arg[3]? arg[3][11] : 0;
  a16=(a14+a15);
  a17=(a16*a09);
  a18=(a12*a17);
  a11=(a11+a18);
  if (res[0]!=0) res[0][0]=a11;
  a18=1.;
  a07=cosh(a07);
  a19=(a18-a07);
  a20=(a19*a16);
  if (res[0]!=0) res[0][1]=a20;
  a19=(a19*a04);
  if (res[0]!=0) res[0][2]=a19;
  a21=(-a20);
  if (res[0]!=0) res[0][3]=a21;
  a22=(-a19);
  if (res[0]!=0) res[0][4]=a22;
  if (res[0]!=0) res[0][5]=a11;
  a11=arg[0]? arg[0][5] : 0;
  a23=arg[5]? arg[5][3] : 0;
  a24=(a23*a02);
  a25=arg[5]? arg[5][1] : 0;
  a26=(a25*a03);
  a24=(a24+a26);
  a26=arg[0]? arg[0][2] : 0;
  a27=(a11*a06);
  a27=(a26+a27);
  a28=cos(a27);
  a29=(a28*a11);
  a30=(a24*a29);
  a31=arg[5]? arg[5][2] : 0;
  a02=(a31*a02);
  a32=arg[5]? arg[5][0] : 0;
  a03=(a32*a03);
  a02=(a02+a03);
  a27=sin(a27);
  a03=(a27*a11);
  a33=(a02*a03);
  a30=(a30+a33);
  a33=(a23*a14);
  a34=(a25*a15);
  a33=(a33+a34);
  a03=(a33*a03);
  a30=(a30-a03);
  a14=(a31*a14);
  a15=(a32*a15);
  a14=(a14+a15);
  a29=(a14*a29);
  a30=(a30+a29);
  a11=(a11*a30);
  a29=1.9681459216763408e-01;
  a15=arg[0]? arg[0][4] : 0;
  a03=(a15*a04);
  a34=arg[0]? arg[0][3] : 0;
  a35=(a34*a16);
  a03=(a03+a35);
  a03=(a29*a03);
  a03=(a03*a09);
  a03=(a05*a03);
  a11=(a11-a03);
  a03=arg[1]? arg[1][4] : 0;
  a00=(a03*a00);
  a01=(a01+a00);
  a01=(a01*a04);
  a12=(a03*a12);
  a13=(a13+a12);
  a13=(a13*a16);
  a01=(a01+a13);
  a13=arg[0]? arg[0][1] : 0;
  a12=(a13*a04);
  a01=(a01-a12);
  a12=arg[0]? arg[0][0] : 0;
  a00=(a12*a16);
  a01=(a01-a00);
  a00=(a05*a07);
  a01=(a01*a00);
  a01=(a05*a01);
  a11=(a11+a01);
  if (res[0]!=0) res[0][6]=a11;
  a11=(-a17);
  if (res[0]!=0) res[0][7]=a11;
  a08=(a08*a04);
  a08=(a05*a08);
  a08=(-a08);
  if (res[0]!=0) res[0][8]=a08;
  if (res[0]!=0) res[0][9]=a30;
  a16=(a16*a07);
  a16=(-a16);
  if (res[0]!=0) res[0][10]=a16;
  a04=(a04*a07);
  a04=(-a04);
  if (res[0]!=0) res[0][11]=a04;
  a07=(a27*a24);
  a01=(a28*a02);
  a07=(a07-a01);
  a01=(a28*a33);
  a07=(a07+a01);
  a01=(a27*a14);
  a07=(a07+a01);
  a01=(a06*a30);
  a07=(a07+a01);
  if (res[0]!=0) res[0][12]=a07;
  a01=(a03*a17);
  a17=(a17-a01);
  if (res[0]!=0) res[0][13]=a17;
  a03=(a03*a10);
  a10=(a10-a03);
  if (res[0]!=0) res[0][14]=a10;
  if (res[0]!=0) res[0][15]=a01;
  if (res[0]!=0) res[0][16]=a03;
  a00=arg[0]? arg[0][20] : 0;
  a09=arg[0]? arg[0][18] : 0;
  a00=(a00-a09);
  a35=arg[3]? arg[3][34] : 0;
  a36=arg[3]? arg[3][32] : 0;
  a37=(a35+a36);
  a38=arg[1]? arg[1][18] : 0;
  a39=(a05*a38);
  a40=sinh(a39);
  a41=(a05*a40);
  a42=(a37*a41);
  a43=(a00*a42);
  a44=arg[0]? arg[0][19] : 0;
  a45=arg[0]? arg[0][17] : 0;
  a44=(a44-a45);
  a46=arg[3]? arg[3][33] : 0;
  a47=arg[3]? arg[3][31] : 0;
  a48=(a46+a47);
  a49=(a48*a41);
  a50=(a44*a49);
  a43=(a43+a50);
  if (res[0]!=0) res[0][17]=a43;
  a39=cosh(a39);
  a50=(a18-a39);
  a51=(a50*a48);
  if (res[0]!=0) res[0][18]=a51;
  a50=(a50*a37);
  if (res[0]!=0) res[0][19]=a50;
  a52=(-a51);
  if (res[0]!=0) res[0][20]=a52;
  a53=(-a50);
  if (res[0]!=0) res[0][21]=a53;
  if (res[0]!=0) res[0][22]=a43;
  a43=arg[0]? arg[0][16] : 0;
  a54=(a23*a35);
  a55=(a25*a36);
  a54=(a54+a55);
  a55=arg[0]? arg[0][13] : 0;
  a56=(a43*a38);
  a56=(a55+a56);
  a57=cos(a56);
  a58=(a57*a43);
  a59=(a54*a58);
  a35=(a31*a35);
  a36=(a32*a36);
  a35=(a35+a36);
  a56=sin(a56);
  a36=(a56*a43);
  a60=(a35*a36);
  a59=(a59+a60);
  a23=(a23*a46);
  a25=(a25*a47);
  a23=(a23+a25);
  a36=(a23*a36);
  a59=(a59-a36);
  a31=(a31*a46);
  a32=(a32*a47);
  a31=(a31+a32);
  a58=(a31*a58);
  a59=(a59+a58);
  a43=(a43*a59);
  a58=arg[0]? arg[0][15] : 0;
  a32=(a58*a37);
  a47=arg[0]? arg[0][14] : 0;
  a46=(a47*a48);
  a32=(a32+a46);
  a29=(a29*a32);
  a29=(a29*a41);
  a29=(a05*a29);
  a43=(a43-a29);
  a29=arg[1]? arg[1][15] : 0;
  a00=(a29*a00);
  a09=(a09+a00);
  a09=(a09*a37);
  a44=(a29*a44);
  a45=(a45+a44);
  a45=(a45*a48);
  a09=(a09+a45);
  a45=arg[0]? arg[0][12] : 0;
  a44=(a45*a37);
  a09=(a09-a44);
  a44=arg[0]? arg[0][11] : 0;
  a00=(a44*a48);
  a09=(a09-a00);
  a00=(a05*a39);
  a09=(a09*a00);
  a09=(a05*a09);
  a43=(a43+a09);
  if (res[0]!=0) res[0][23]=a43;
  a43=(-a49);
  if (res[0]!=0) res[0][24]=a43;
  a40=(a40*a37);
  a05=(a05*a40);
  a05=(-a05);
  if (res[0]!=0) res[0][25]=a05;
  if (res[0]!=0) res[0][26]=a59;
  a48=(a48*a39);
  a48=(-a48);
  if (res[0]!=0) res[0][27]=a48;
  a37=(a37*a39);
  a37=(-a37);
  if (res[0]!=0) res[0][28]=a37;
  a39=(a56*a54);
  a40=(a57*a35);
  a39=(a39-a40);
  a40=(a57*a23);
  a39=(a39+a40);
  a40=(a56*a31);
  a39=(a39+a40);
  a40=(a38*a59);
  a39=(a39+a40);
  if (res[0]!=0) res[0][29]=a39;
  a40=(a29*a49);
  a49=(a49-a40);
  if (res[0]!=0) res[0][30]=a49;
  a29=(a29*a42);
  a42=(a42-a29);
  if (res[0]!=0) res[0][31]=a42;
  if (res[0]!=0) res[0][32]=a40;
  if (res[0]!=0) res[0][33]=a29;
  if (res[0]!=0) res[0][34]=a11;
  a11=2.;
  a12=(a12-a18);
  a09=casadi_sq(a12);
  a00=2.0000000000000001e-01;
  a13=(a13-a00);
  a41=casadi_sq(a13);
  a09=(a09+a41);
  a09=(a18+a09);
  a41=(1./a09);
  a32=(a41/a09);
  a46=cos(a26);
  a36=(a15*a46);
  a25=sin(a26);
  a60=(a34*a25);
  a36=(a36-a60);
  a60=arg[3]? arg[3][19] : 0;
  a36=(a36*a60);
  a61=(a32*a36);
  a26=(a26/a09);
  a26=(a26/a09);
  a62=arg[3]? arg[3][2] : 0;
  a63=(a26*a62);
  a61=(a61-a63);
  a61=(a11*a61);
  a12=(a12+a12);
  a63=(a26*a12);
  a63=(a63/a09);
  a64=(a26/a09);
  a65=(a64*a12);
  a63=(a63+a65);
  a63=(a62*a63);
  a65=(a32*a12);
  a66=(a65/a09);
  a67=(a32/a09);
  a68=(a67*a12);
  a66=(a66+a68);
  a66=(a36*a66);
  a63=(a63-a66);
  a63=(a12*a63);
  a63=(a61+a63);
  if (res[0]!=0) res[0][35]=a63;
  a13=(a13+a13);
  a26=(a26*a13);
  a26=(a26/a09);
  a64=(a64*a13);
  a26=(a26+a64);
  a26=(a62*a26);
  a64=(a32*a13);
  a63=(a64/a09);
  a67=(a67*a13);
  a63=(a63+a67);
  a36=(a36*a63);
  a26=(a26-a36);
  a36=(a12*a26);
  if (res[0]!=0) res[0][36]=a36;
  a63=(a15*a25);
  a67=(a34*a46);
  a63=(a63+a67);
  a63=(a60*a63);
  a32=(a32*a63);
  a63=casadi_sq(a41);
  a63=(a62*a63);
  a32=(a32+a63);
  a12=(a12*a32);
  a12=(-a12);
  if (res[0]!=0) res[0][37]=a12;
  a65=(a60*a65);
  a32=(a25*a65);
  a32=(-a32);
  if (res[0]!=0) res[0][38]=a32;
  a65=(a46*a65);
  if (res[0]!=0) res[0][39]=a65;
  if (res[0]!=0) res[0][40]=a08;
  if (res[0]!=0) res[0][41]=a36;
  a26=(a13*a26);
  a61=(a61+a26);
  if (res[0]!=0) res[0][42]=a61;
  a64=(a60*a64);
  a61=(a34*a64);
  a61=(a46*a61);
  a26=(a15*a64);
  a26=(a25*a26);
  a61=(a61+a26);
  a62=(a62/a09);
  a62=(a62/a09);
  a62=(a62*a13);
  a61=(a61+a62);
  a61=(-a61);
  if (res[0]!=0) res[0][43]=a61;
  a62=(a25*a64);
  a62=(-a62);
  if (res[0]!=0) res[0][44]=a62;
  a64=(a46*a64);
  if (res[0]!=0) res[0][45]=a64;
  if (res[0]!=0) res[0][46]=a30;
  if (res[0]!=0) res[0][47]=a12;
  if (res[0]!=0) res[0][48]=a61;
  a61=(a24*a28);
  a12=(a02*a27);
  a61=(a61+a12);
  a12=(a33*a27);
  a61=(a61-a12);
  a12=(a14*a28);
  a61=(a61+a12);
  a41=(a18-a41);
  a41=(a41*a60);
  a15=(a15*a41);
  a15=(a15*a46);
  a34=(a34*a41);
  a34=(a34*a25);
  a15=(a15-a34);
  a15=(a61-a15);
  if (res[0]!=0) res[0][49]=a15;
  a46=(a41*a46);
  a46=(-a46);
  if (res[0]!=0) res[0][50]=a46;
  a41=(a41*a25);
  a41=(-a41);
  if (res[0]!=0) res[0][51]=a41;
  a61=(a06*a61);
  if (res[0]!=0) res[0][52]=a61;
  if (res[0]!=0) res[0][53]=a16;
  if (res[0]!=0) res[0][54]=a32;
  if (res[0]!=0) res[0][55]=a62;
  if (res[0]!=0) res[0][56]=a46;
  if (res[0]!=0) res[0][57]=a04;
  if (res[0]!=0) res[0][58]=a65;
  if (res[0]!=0) res[0][59]=a64;
  if (res[0]!=0) res[0][60]=a41;
  if (res[0]!=0) res[0][61]=a07;
  if (res[0]!=0) res[0][62]=a61;
  a28=(a28*a06);
  a24=(a24*a28);
  a27=(a27*a06);
  a02=(a02*a27);
  a24=(a24+a02);
  a33=(a33*a27);
  a24=(a24-a33);
  a14=(a14*a28);
  a24=(a24+a14);
  a06=(a06*a24);
  if (res[0]!=0) res[0][63]=a06;
  if (res[0]!=0) res[0][64]=a20;
  if (res[0]!=0) res[0][65]=a17;
  if (res[0]!=0) res[0][66]=a19;
  if (res[0]!=0) res[0][67]=a10;
  if (res[0]!=0) res[0][68]=a21;
  if (res[0]!=0) res[0][69]=a01;
  if (res[0]!=0) res[0][70]=a22;
  if (res[0]!=0) res[0][71]=a03;
  if (res[0]!=0) res[0][72]=a43;
  a44=(a44-a18);
  a43=casadi_sq(a44);
  a45=(a45-a00);
  a00=casadi_sq(a45);
  a43=(a43+a00);
  a43=(a18+a43);
  a00=(1./a43);
  a03=(a00/a43);
  a22=cos(a55);
  a01=(a58*a22);
  a21=sin(a55);
  a10=(a47*a21);
  a01=(a01-a10);
  a10=arg[3]? arg[3][39] : 0;
  a01=(a01*a10);
  a19=(a03*a01);
  a55=(a55/a43);
  a55=(a55/a43);
  a17=arg[3]? arg[3][22] : 0;
  a20=(a55*a17);
  a19=(a19-a20);
  a11=(a11*a19);
  a44=(a44+a44);
  a19=(a55*a44);
  a19=(a19/a43);
  a20=(a55/a43);
  a06=(a20*a44);
  a19=(a19+a06);
  a19=(a17*a19);
  a06=(a03*a44);
  a24=(a06/a43);
  a14=(a03/a43);
  a28=(a14*a44);
  a24=(a24+a28);
  a24=(a01*a24);
  a19=(a19-a24);
  a19=(a44*a19);
  a19=(a11+a19);
  if (res[0]!=0) res[0][73]=a19;
  a45=(a45+a45);
  a55=(a55*a45);
  a55=(a55/a43);
  a20=(a20*a45);
  a55=(a55+a20);
  a55=(a17*a55);
  a20=(a03*a45);
  a19=(a20/a43);
  a14=(a14*a45);
  a19=(a19+a14);
  a01=(a01*a19);
  a55=(a55-a01);
  a01=(a44*a55);
  if (res[0]!=0) res[0][74]=a01;
  a19=(a58*a21);
  a14=(a47*a22);
  a19=(a19+a14);
  a19=(a10*a19);
  a03=(a03*a19);
  a19=casadi_sq(a00);
  a19=(a17*a19);
  a03=(a03+a19);
  a44=(a44*a03);
  a44=(-a44);
  if (res[0]!=0) res[0][75]=a44;
  a06=(a10*a06);
  a03=(a21*a06);
  a03=(-a03);
  if (res[0]!=0) res[0][76]=a03;
  a06=(a22*a06);
  if (res[0]!=0) res[0][77]=a06;
  if (res[0]!=0) res[0][78]=a05;
  if (res[0]!=0) res[0][79]=a01;
  a55=(a45*a55);
  a11=(a11+a55);
  if (res[0]!=0) res[0][80]=a11;
  a20=(a10*a20);
  a11=(a47*a20);
  a11=(a22*a11);
  a55=(a58*a20);
  a55=(a21*a55);
  a11=(a11+a55);
  a17=(a17/a43);
  a17=(a17/a43);
  a17=(a17*a45);
  a11=(a11+a17);
  a11=(-a11);
  if (res[0]!=0) res[0][81]=a11;
  a17=(a21*a20);
  a17=(-a17);
  if (res[0]!=0) res[0][82]=a17;
  a20=(a22*a20);
  if (res[0]!=0) res[0][83]=a20;
  if (res[0]!=0) res[0][84]=a59;
  if (res[0]!=0) res[0][85]=a44;
  if (res[0]!=0) res[0][86]=a11;
  a11=(a54*a57);
  a44=(a35*a56);
  a11=(a11+a44);
  a44=(a23*a56);
  a11=(a11-a44);
  a44=(a31*a57);
  a11=(a11+a44);
  a18=(a18-a00);
  a18=(a18*a10);
  a58=(a58*a18);
  a58=(a58*a22);
  a47=(a47*a18);
  a47=(a47*a21);
  a58=(a58-a47);
  a58=(a11-a58);
  if (res[0]!=0) res[0][87]=a58;
  a22=(a18*a22);
  a22=(-a22);
  if (res[0]!=0) res[0][88]=a22;
  a18=(a18*a21);
  a18=(-a18);
  if (res[0]!=0) res[0][89]=a18;
  a11=(a38*a11);
  if (res[0]!=0) res[0][90]=a11;
  if (res[0]!=0) res[0][91]=a48;
  if (res[0]!=0) res[0][92]=a03;
  if (res[0]!=0) res[0][93]=a17;
  if (res[0]!=0) res[0][94]=a22;
  if (res[0]!=0) res[0][95]=a37;
  if (res[0]!=0) res[0][96]=a06;
  if (res[0]!=0) res[0][97]=a20;
  if (res[0]!=0) res[0][98]=a18;
  if (res[0]!=0) res[0][99]=a39;
  if (res[0]!=0) res[0][100]=a11;
  a57=(a57*a38);
  a54=(a54*a57);
  a56=(a56*a38);
  a35=(a35*a56);
  a54=(a54+a35);
  a23=(a23*a56);
  a54=(a54-a23);
  a31=(a31*a57);
  a54=(a54+a31);
  a38=(a38*a54);
  if (res[0]!=0) res[0][101]=a38;
  if (res[0]!=0) res[0][102]=a51;
  if (res[0]!=0) res[0][103]=a49;
  if (res[0]!=0) res[0][104]=a50;
  if (res[0]!=0) res[0][105]=a42;
  if (res[0]!=0) res[0][106]=a52;
  if (res[0]!=0) res[0][107]=a40;
  if (res[0]!=0) res[0][108]=a53;
  if (res[0]!=0) res[0][109]=a29;
  return 0;
}

CASADI_SYMBOL_EXPORT int lipm_opti_pessi_cost_y_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int lipm_opti_pessi_cost_y_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int lipm_opti_pessi_cost_y_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void lipm_opti_pessi_cost_y_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int lipm_opti_pessi_cost_y_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void lipm_opti_pessi_cost_y_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void lipm_opti_pessi_cost_y_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void lipm_opti_pessi_cost_y_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int lipm_opti_pessi_cost_y_hess_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int lipm_opti_pessi_cost_y_hess_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real lipm_opti_pessi_cost_y_hess_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* lipm_opti_pessi_cost_y_hess_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* lipm_opti_pessi_cost_y_hess_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* lipm_opti_pessi_cost_y_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    case 4: return casadi_s3;
    case 5: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* lipm_opti_pessi_cost_y_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int lipm_opti_pessi_cost_y_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int lipm_opti_pessi_cost_y_hess_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
