/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) lipm_step_constr_h_fun_jac_uxt_zt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {10, 1, 1};
static const casadi_int casadi_s1[3] = {7, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {4, 1, 1};
static const casadi_int casadi_s4[3] = {6, 1, 1};
static const casadi_int casadi_s5[75] = 
  {17, 6, 0, 13, 26, 37, 48, 57,
  66, 0, 1, 4, 7, 8, 9, 10,
  11, 12, 13, 14, 15, 16, 2, 3,
  4, 7, 8, 9, 10, 11, 12, 13,
  14, 15, 16, 4, 7, 8, 9, 10,
  11, 12, 13, 14, 15, 16, 4, 7,
  8, 9, 10, 11, 12, 13, 14, 15,
  16, 4, 5, 6, 7, 8, 13, 14,
  15, 16, 4, 5, 6, 7, 8, 13,
  14, 15, 16};
static const casadi_int casadi_s6[3] = {6, 0, 1};

/* lipm_step_constr_h_fun_jac_uxt_zt:(i0[10],i1[7],i2[0],i3[4])->(o0[6],o1[17x6,66nz],o2[6x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39, a40;
  a00=arg[1]? arg[1][0] : 0;
  a01=1.5623039875841591e+00;
  a02=arg[0]? arg[0][0] : 0;
  a03=(a01*a02);
  a04=2.3624259392867469e-01;
  a05=arg[0]? arg[0][3] : 0;
  a05=(a04*a05);
  a03=(a03+a05);
  a05=-5.6230398758415912e-01;
  a06=arg[0]? arg[0][6] : 0;
  a07=arg[1]? arg[1][4] : 0;
  a08=arg[0]? arg[0][8] : 0;
  a09=(a08-a06);
  a10=(a07*a09);
  a10=(a06+a10);
  a11=(a05*a10);
  a03=(a03+a11);
  a11=arg[0]? arg[0][2] : 0;
  a12=2.0000000000000001e-01;
  a13=arg[0]? arg[0][5] : 0;
  a13=(a12*a13);
  a11=(a11+a13);
  a13=cos(a11);
  a14=arg[3]? arg[3][0] : 0;
  a15=(a13*a14);
  a11=sin(a11);
  a16=arg[3]? arg[3][1] : 0;
  a17=(a11*a16);
  a15=(a15-a17);
  a15=(a03+a15);
  a00=(a00-a15);
  a17=casadi_sq(a00);
  a18=arg[1]? arg[1][1] : 0;
  a19=arg[0]? arg[0][1] : 0;
  a20=(a01*a19);
  a21=arg[0]? arg[0][4] : 0;
  a21=(a04*a21);
  a20=(a20+a21);
  a21=arg[0]? arg[0][7] : 0;
  a22=arg[0]? arg[0][9] : 0;
  a23=(a22-a21);
  a24=(a07*a23);
  a24=(a21+a24);
  a25=(a05*a24);
  a20=(a20+a25);
  a25=(a11*a14);
  a26=(a13*a16);
  a25=(a25+a26);
  a25=(a20+a25);
  a18=(a18-a25);
  a26=casadi_sq(a18);
  a17=(a17+a26);
  if (res[0]!=0) res[0][0]=a17;
  a17=arg[1]? arg[1][2] : 0;
  a26=arg[3]? arg[3][2] : 0;
  a27=(a13*a26);
  a28=arg[3]? arg[3][3] : 0;
  a29=(a11*a28);
  a27=(a27-a29);
  a03=(a03+a27);
  a17=(a17-a03);
  a27=casadi_sq(a17);
  a29=arg[1]? arg[1][3] : 0;
  a30=(a11*a26);
  a31=(a13*a28);
  a30=(a30+a31);
  a20=(a20+a30);
  a29=(a29-a20);
  a30=casadi_sq(a29);
  a27=(a27+a30);
  if (res[0]!=0) res[0][1]=a27;
  a06=(a06-a15);
  a15=casadi_sq(a06);
  a21=(a21-a25);
  a25=casadi_sq(a21);
  a15=(a15+a25);
  if (res[0]!=0) res[0][2]=a15;
  a08=(a08-a03);
  a03=casadi_sq(a08);
  a22=(a22-a20);
  a20=casadi_sq(a22);
  a03=(a03+a20);
  if (res[0]!=0) res[0][3]=a03;
  a03=12.;
  a20=arg[1]? arg[1][5] : 0;
  a15=(a03*a20);
  a25=2.5815789473684209e+01;
  a02=(a02-a10);
  a02=(a25*a02);
  a10=(a15*a02);
  a27=casadi_sq(a10);
  a30=arg[1]? arg[1][6] : 0;
  a31=(a03*a30);
  a19=(a19-a24);
  a19=(a25*a19);
  a24=(a31*a19);
  a32=casadi_sq(a24);
  a27=(a27+a32);
  a32=9.8100000000000005e+00;
  a33=8.0000000000000004e-01;
  a34=(a33*a07);
  a34=(a03*a34);
  a34=(a32*a34);
  a35=casadi_sq(a34);
  a27=(a27-a35);
  a35=1.0000000000000000e-03;
  a27=(a27+a35);
  if (res[0]!=0) res[0][4]=a27;
  a27=1.;
  a20=(a27-a20);
  a20=(a03*a20);
  a36=(a20*a02);
  a37=casadi_sq(a36);
  a30=(a27-a30);
  a30=(a03*a30);
  a38=(a30*a19);
  a39=casadi_sq(a38);
  a37=(a37+a39);
  a27=(a27-a07);
  a27=(a33*a27);
  a27=(a03*a27);
  a27=(a32*a27);
  a39=casadi_sq(a27);
  a37=(a37-a39);
  a37=(a37+a35);
  if (res[0]!=0) res[0][5]=a37;
  a00=(a00+a00);
  if (res[1]!=0) res[1][0]=a00;
  a18=(a18+a18);
  if (res[1]!=0) res[1][1]=a18;
  a37=(a05*a18);
  a35=(a23*a37);
  a39=(a05*a00);
  a40=(a09*a39);
  a35=(a35+a40);
  a35=(-a35);
  if (res[1]!=0) res[1][2]=a35;
  a35=(a01*a00);
  a35=(-a35);
  if (res[1]!=0) res[1][3]=a35;
  a35=(a01*a18);
  a35=(-a35);
  if (res[1]!=0) res[1][4]=a35;
  a35=(a16*a18);
  a35=(a11*a35);
  a40=(a14*a18);
  a40=(a13*a40);
  a35=(a35-a40);
  a40=(a16*a00);
  a40=(a13*a40);
  a35=(a35+a40);
  a40=(a14*a00);
  a40=(a11*a40);
  a35=(a35+a40);
  if (res[1]!=0) res[1][5]=a35;
  a00=(a04*a00);
  a00=(-a00);
  if (res[1]!=0) res[1][6]=a00;
  a18=(a04*a18);
  a18=(-a18);
  if (res[1]!=0) res[1][7]=a18;
  a35=(a12*a35);
  if (res[1]!=0) res[1][8]=a35;
  a35=(a07*a39);
  a39=(a35-a39);
  if (res[1]!=0) res[1][9]=a39;
  a39=(a07*a37);
  a37=(a39-a37);
  if (res[1]!=0) res[1][10]=a37;
  a35=(-a35);
  if (res[1]!=0) res[1][11]=a35;
  a39=(-a39);
  if (res[1]!=0) res[1][12]=a39;
  a17=(a17+a17);
  if (res[1]!=0) res[1][13]=a17;
  a29=(a29+a29);
  if (res[1]!=0) res[1][14]=a29;
  a39=(a05*a29);
  a35=(a23*a39);
  a37=(a05*a17);
  a18=(a09*a37);
  a35=(a35+a18);
  a35=(-a35);
  if (res[1]!=0) res[1][15]=a35;
  a35=(a01*a17);
  a35=(-a35);
  if (res[1]!=0) res[1][16]=a35;
  a35=(a01*a29);
  a35=(-a35);
  if (res[1]!=0) res[1][17]=a35;
  a35=(a28*a29);
  a35=(a11*a35);
  a18=(a26*a29);
  a18=(a13*a18);
  a35=(a35-a18);
  a18=(a28*a17);
  a18=(a13*a18);
  a35=(a35+a18);
  a18=(a26*a17);
  a18=(a11*a18);
  a35=(a35+a18);
  if (res[1]!=0) res[1][18]=a35;
  a17=(a04*a17);
  a17=(-a17);
  if (res[1]!=0) res[1][19]=a17;
  a29=(a04*a29);
  a29=(-a29);
  if (res[1]!=0) res[1][20]=a29;
  a35=(a12*a35);
  if (res[1]!=0) res[1][21]=a35;
  a35=(a07*a37);
  a37=(a35-a37);
  if (res[1]!=0) res[1][22]=a37;
  a37=(a07*a39);
  a39=(a37-a39);
  if (res[1]!=0) res[1][23]=a39;
  a35=(-a35);
  if (res[1]!=0) res[1][24]=a35;
  a37=(-a37);
  if (res[1]!=0) res[1][25]=a37;
  a21=(a21+a21);
  a37=(a05*a21);
  a35=(a23*a37);
  a06=(a06+a06);
  a39=(a05*a06);
  a29=(a09*a39);
  a35=(a35+a29);
  a35=(-a35);
  if (res[1]!=0) res[1][26]=a35;
  a35=(a01*a06);
  a35=(-a35);
  if (res[1]!=0) res[1][27]=a35;
  a35=(a01*a21);
  a35=(-a35);
  if (res[1]!=0) res[1][28]=a35;
  a35=(a16*a21);
  a35=(a11*a35);
  a29=(a14*a21);
  a29=(a13*a29);
  a35=(a35-a29);
  a16=(a16*a06);
  a16=(a13*a16);
  a35=(a35+a16);
  a14=(a14*a06);
  a14=(a11*a14);
  a35=(a35+a14);
  if (res[1]!=0) res[1][29]=a35;
  a14=(a04*a06);
  a14=(-a14);
  if (res[1]!=0) res[1][30]=a14;
  a14=(a04*a21);
  a14=(-a14);
  if (res[1]!=0) res[1][31]=a14;
  a35=(a12*a35);
  if (res[1]!=0) res[1][32]=a35;
  a06=(a06-a39);
  a39=(a07*a39);
  a06=(a06+a39);
  if (res[1]!=0) res[1][33]=a06;
  a21=(a21-a37);
  a37=(a07*a37);
  a21=(a21+a37);
  if (res[1]!=0) res[1][34]=a21;
  a39=(-a39);
  if (res[1]!=0) res[1][35]=a39;
  a37=(-a37);
  if (res[1]!=0) res[1][36]=a37;
  a22=(a22+a22);
  a37=(a05*a22);
  a39=(a23*a37);
  a08=(a08+a08);
  a05=(a05*a08);
  a21=(a09*a05);
  a39=(a39+a21);
  a39=(-a39);
  if (res[1]!=0) res[1][37]=a39;
  a39=(a01*a08);
  a39=(-a39);
  if (res[1]!=0) res[1][38]=a39;
  a01=(a01*a22);
  a01=(-a01);
  if (res[1]!=0) res[1][39]=a01;
  a01=(a28*a22);
  a01=(a11*a01);
  a39=(a26*a22);
  a39=(a13*a39);
  a01=(a01-a39);
  a28=(a28*a08);
  a13=(a13*a28);
  a01=(a01+a13);
  a26=(a26*a08);
  a11=(a11*a26);
  a01=(a01+a11);
  if (res[1]!=0) res[1][40]=a01;
  a11=(a04*a08);
  a11=(-a11);
  if (res[1]!=0) res[1][41]=a11;
  a04=(a04*a22);
  a04=(-a04);
  if (res[1]!=0) res[1][42]=a04;
  a12=(a12*a01);
  if (res[1]!=0) res[1][43]=a12;
  a12=(a07*a05);
  a05=(a12-a05);
  if (res[1]!=0) res[1][44]=a05;
  a05=(a07*a37);
  a37=(a05-a37);
  if (res[1]!=0) res[1][45]=a37;
  a08=(a08-a12);
  if (res[1]!=0) res[1][46]=a08;
  a22=(a22-a05);
  if (res[1]!=0) res[1][47]=a22;
  a34=(a34+a34);
  a34=(a32*a34);
  a34=(a03*a34);
  a34=(a33*a34);
  a24=(a24+a24);
  a31=(a31*a24);
  a31=(a25*a31);
  a22=(a23*a31);
  a34=(a34+a22);
  a10=(a10+a10);
  a15=(a15*a10);
  a15=(a25*a15);
  a22=(a09*a15);
  a34=(a34+a22);
  a34=(-a34);
  if (res[1]!=0) res[1][48]=a34;
  a10=(a02*a10);
  a10=(a03*a10);
  if (res[1]!=0) res[1][49]=a10;
  a24=(a19*a24);
  a24=(a03*a24);
  if (res[1]!=0) res[1][50]=a24;
  if (res[1]!=0) res[1][51]=a15;
  if (res[1]!=0) res[1][52]=a31;
  a24=(a07*a15);
  a15=(a24-a15);
  if (res[1]!=0) res[1][53]=a15;
  a15=(a07*a31);
  a31=(a15-a31);
  if (res[1]!=0) res[1][54]=a31;
  a24=(-a24);
  if (res[1]!=0) res[1][55]=a24;
  a15=(-a15);
  if (res[1]!=0) res[1][56]=a15;
  a27=(a27+a27);
  a32=(a32*a27);
  a32=(a03*a32);
  a33=(a33*a32);
  a38=(a38+a38);
  a30=(a30*a38);
  a30=(a25*a30);
  a23=(a23*a30);
  a33=(a33-a23);
  a36=(a36+a36);
  a20=(a20*a36);
  a25=(a25*a20);
  a09=(a09*a25);
  a33=(a33-a09);
  if (res[1]!=0) res[1][57]=a33;
  a02=(a02*a36);
  a02=(a03*a02);
  a02=(-a02);
  if (res[1]!=0) res[1][58]=a02;
  a19=(a19*a38);
  a03=(a03*a19);
  a03=(-a03);
  if (res[1]!=0) res[1][59]=a03;
  if (res[1]!=0) res[1][60]=a25;
  if (res[1]!=0) res[1][61]=a30;
  a03=(a07*a25);
  a25=(a03-a25);
  if (res[1]!=0) res[1][62]=a25;
  a07=(a07*a30);
  a30=(a07-a30);
  if (res[1]!=0) res[1][63]=a30;
  a03=(-a03);
  if (res[1]!=0) res[1][64]=a03;
  a07=(-a07);
  if (res[1]!=0) res[1][65]=a07;
  return 0;
}

CASADI_SYMBOL_EXPORT int lipm_step_constr_h_fun_jac_uxt_zt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int lipm_step_constr_h_fun_jac_uxt_zt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int lipm_step_constr_h_fun_jac_uxt_zt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void lipm_step_constr_h_fun_jac_uxt_zt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int lipm_step_constr_h_fun_jac_uxt_zt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void lipm_step_constr_h_fun_jac_uxt_zt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void lipm_step_constr_h_fun_jac_uxt_zt_incref(void) {
}

CASADI_SYMBOL_EXPORT void lipm_step_constr_h_fun_jac_uxt_zt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int lipm_step_constr_h_fun_jac_uxt_zt_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int lipm_step_constr_h_fun_jac_uxt_zt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real lipm_step_constr_h_fun_jac_uxt_zt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* lipm_step_constr_h_fun_jac_uxt_zt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* lipm_step_constr_h_fun_jac_uxt_zt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* lipm_step_constr_h_fun_jac_uxt_zt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* lipm_step_constr_h_fun_jac_uxt_zt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    case 2: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int lipm_step_constr_h_fun_jac_uxt_zt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int lipm_step_constr_h_fun_jac_uxt_zt_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
