/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) lipm_opti_pessi_constr_h_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {22, 1, 1};
static const casadi_int casadi_s1[3] = {0, 1, 1};
static const casadi_int casadi_s2[3] = {8, 1, 1};
static const casadi_int casadi_s3[3] = {32, 1, 1};

/* lipm_opti_pessi_constr_h_fun:(i0[22],i1[22],i2[0],i3[8])->(o0[32]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33;
  a00=arg[0]? arg[0][6] : 0;
  a01=5.0809240767486585e+00;
  a02=arg[1]? arg[1][7] : 0;
  a03=(a01*a02);
  a04=cosh(a03);
  a05=arg[0]? arg[0][0] : 0;
  a06=(a04*a05);
  a03=sinh(a03);
  a03=(a03/a01);
  a07=arg[0]? arg[0][3] : 0;
  a08=(a03*a07);
  a06=(a06+a08);
  a08=1.;
  a09=(a08-a04);
  a10=arg[1]? arg[1][4] : 0;
  a11=arg[0]? arg[0][8] : 0;
  a12=(a11-a00);
  a12=(a10*a12);
  a12=(a00+a12);
  a13=(a09*a12);
  a06=(a06+a13);
  a13=arg[0]? arg[0][2] : 0;
  a14=arg[0]? arg[0][5] : 0;
  a14=(a14*a02);
  a14=(a13+a14);
  a02=cos(a14);
  a15=arg[3]? arg[3][0] : 0;
  a16=(a02*a15);
  a14=sin(a14);
  a17=arg[3]? arg[3][1] : 0;
  a18=(a14*a17);
  a16=(a16-a18);
  a16=(a06+a16);
  a00=(a00-a16);
  a00=casadi_sq(a00);
  a18=arg[0]? arg[0][7] : 0;
  a19=arg[0]? arg[0][1] : 0;
  a04=(a04*a19);
  a20=arg[0]? arg[0][4] : 0;
  a03=(a03*a20);
  a04=(a04+a03);
  a03=arg[0]? arg[0][9] : 0;
  a21=(a03-a18);
  a21=(a10*a21);
  a21=(a18+a21);
  a09=(a09*a21);
  a04=(a04+a09);
  a09=(a14*a15);
  a22=(a02*a17);
  a09=(a09+a22);
  a09=(a04+a09);
  a18=(a18-a09);
  a18=casadi_sq(a18);
  a00=(a00+a18);
  if (res[0]!=0) res[0][0]=a00;
  a00=arg[3]? arg[3][2] : 0;
  a18=(a02*a00);
  a22=arg[3]? arg[3][3] : 0;
  a23=(a14*a22);
  a18=(a18-a23);
  a18=(a06+a18);
  a11=(a11-a18);
  a11=casadi_sq(a11);
  a23=(a14*a00);
  a24=(a02*a22);
  a23=(a23+a24);
  a23=(a04+a23);
  a03=(a03-a23);
  a03=casadi_sq(a03);
  a11=(a11+a03);
  if (res[0]!=0) res[0][1]=a11;
  a11=arg[1]? arg[1][0] : 0;
  a16=(a11-a16);
  a16=casadi_sq(a16);
  a03=arg[1]? arg[1][1] : 0;
  a09=(a03-a09);
  a09=casadi_sq(a09);
  a16=(a16+a09);
  if (res[0]!=0) res[0][2]=a16;
  a16=arg[1]? arg[1][2] : 0;
  a18=(a16-a18);
  a18=casadi_sq(a18);
  a09=arg[1]? arg[1][3] : 0;
  a23=(a09-a23);
  a23=casadi_sq(a23);
  a18=(a18+a23);
  if (res[0]!=0) res[0][3]=a18;
  a18=arg[1]? arg[1][5] : 0;
  a23=12.;
  a24=2.5815789473684209e+01;
  a05=(a05-a12);
  a05=(a24*a05);
  a05=(a23*a05);
  a12=(a18*a05);
  a12=casadi_sq(a12);
  a25=arg[1]? arg[1][6] : 0;
  a19=(a19-a21);
  a19=(a24*a19);
  a19=(a23*a19);
  a21=(a25*a19);
  a21=casadi_sq(a21);
  a12=(a12+a21);
  a21=9.8100000000000005e+00;
  a26=8.0000000000000004e-01;
  a27=(a08-a10);
  a27=(a26*a27);
  a27=(a23*a27);
  a27=(a21*a27);
  a27=casadi_sq(a27);
  a12=(a12-a27);
  a27=1.0000000000000000e-03;
  a12=(a12+a27);
  if (res[0]!=0) res[0][4]=a12;
  a18=(a08-a18);
  a18=(a18*a05);
  a18=casadi_sq(a18);
  a25=(a08-a25);
  a25=(a25*a19);
  a25=casadi_sq(a25);
  a18=(a18+a25);
  a10=(a26*a10);
  a10=(a23*a10);
  a10=(a21*a10);
  a10=casadi_sq(a10);
  a18=(a18-a10);
  a18=(a18+a27);
  if (res[0]!=0) res[0][5]=a18;
  a18=arg[1]? arg[1][8] : 0;
  a10=casadi_sq(a18);
  a25=arg[1]? arg[1][9] : 0;
  a19=casadi_sq(a25);
  a10=(a10+a19);
  if (res[0]!=0) res[0][6]=a10;
  a10=2.0000000000000001e-01;
  a19=(a10*a02);
  a05=(a10*a14);
  a12=(a19-a05);
  a12=(a06+a12);
  a12=(a18*a12);
  a28=(a05+a19);
  a28=(a04+a28);
  a28=(a25*a28);
  a12=(a12+a28);
  a28=arg[1]? arg[1][10] : 0;
  a12=(a12+a28);
  if (res[0]!=0) res[0][7]=a12;
  a12=-2.0000000000000001e-01;
  a02=(a12*a02);
  a29=(a02-a05);
  a29=(a06+a29);
  a29=(a18*a29);
  a14=(a12*a14);
  a30=(a14+a19);
  a30=(a04+a30);
  a30=(a25*a30);
  a29=(a29+a30);
  a29=(a29+a28);
  if (res[0]!=0) res[0][8]=a29;
  a29=(a02-a14);
  a29=(a06+a29);
  a29=(a18*a29);
  a30=(a14+a02);
  a30=(a04+a30);
  a30=(a25*a30);
  a29=(a29+a30);
  a29=(a29+a28);
  if (res[0]!=0) res[0][9]=a29;
  a19=(a19-a14);
  a06=(a06+a19);
  a06=(a18*a06);
  a05=(a05+a02);
  a04=(a04+a05);
  a04=(a25*a04);
  a06=(a06+a04);
  a06=(a06+a28);
  if (res[0]!=0) res[0][10]=a06;
  a11=(a18*a11);
  a03=(a25*a03);
  a11=(a11+a03);
  a11=(a11+a28);
  if (res[0]!=0) res[0][11]=a11;
  a16=(a18*a16);
  a09=(a25*a09);
  a16=(a16+a09);
  a16=(a16+a28);
  if (res[0]!=0) res[0][12]=a16;
  a16=arg[3]? arg[3][4] : 0;
  a18=(a18*a16);
  a09=arg[3]? arg[3][5] : 0;
  a25=(a25*a09);
  a18=(a18+a25);
  a18=(a18+a28);
  a28=1.5000000000000000e+00;
  a25=arg[3]? arg[3][6] : 0;
  a11=(a28*a25);
  a18=(a18-a11);
  if (res[0]!=0) res[0][13]=a18;
  a18=cos(a13);
  a11=(a07*a18);
  a13=sin(a13);
  a03=(a20*a13);
  a11=(a11+a03);
  if (res[0]!=0) res[0][14]=a11;
  a20=(a20*a18);
  a07=(a07*a13);
  a20=(a20-a07);
  if (res[0]!=0) res[0][15]=a20;
  a20=arg[0]? arg[0][17] : 0;
  a07=arg[1]? arg[1][18] : 0;
  a13=(a01*a07);
  a18=cosh(a13);
  a11=arg[0]? arg[0][11] : 0;
  a03=(a18*a11);
  a13=sinh(a13);
  a13=(a13/a01);
  a01=arg[0]? arg[0][14] : 0;
  a06=(a13*a01);
  a03=(a03+a06);
  a06=(a08-a18);
  a04=arg[1]? arg[1][15] : 0;
  a05=arg[0]? arg[0][19] : 0;
  a02=(a05-a20);
  a02=(a04*a02);
  a02=(a20+a02);
  a19=(a06*a02);
  a03=(a03+a19);
  a19=arg[0]? arg[0][13] : 0;
  a14=arg[0]? arg[0][16] : 0;
  a14=(a14*a07);
  a14=(a19+a14);
  a07=cos(a14);
  a29=(a07*a15);
  a14=sin(a14);
  a30=(a14*a17);
  a29=(a29-a30);
  a29=(a03+a29);
  a20=(a20-a29);
  a20=casadi_sq(a20);
  a30=arg[0]? arg[0][18] : 0;
  a31=arg[0]? arg[0][12] : 0;
  a18=(a18*a31);
  a32=arg[0]? arg[0][15] : 0;
  a13=(a13*a32);
  a18=(a18+a13);
  a13=arg[0]? arg[0][20] : 0;
  a33=(a13-a30);
  a33=(a04*a33);
  a33=(a30+a33);
  a06=(a06*a33);
  a18=(a18+a06);
  a15=(a14*a15);
  a17=(a07*a17);
  a15=(a15+a17);
  a15=(a18+a15);
  a30=(a30-a15);
  a30=casadi_sq(a30);
  a20=(a20+a30);
  if (res[0]!=0) res[0][16]=a20;
  a20=(a07*a00);
  a30=(a14*a22);
  a20=(a20-a30);
  a20=(a03+a20);
  a05=(a05-a20);
  a05=casadi_sq(a05);
  a00=(a14*a00);
  a22=(a07*a22);
  a00=(a00+a22);
  a00=(a18+a00);
  a13=(a13-a00);
  a13=casadi_sq(a13);
  a05=(a05+a13);
  if (res[0]!=0) res[0][17]=a05;
  a05=arg[1]? arg[1][11] : 0;
  a29=(a05-a29);
  a29=casadi_sq(a29);
  a13=arg[1]? arg[1][12] : 0;
  a15=(a13-a15);
  a15=casadi_sq(a15);
  a29=(a29+a15);
  if (res[0]!=0) res[0][18]=a29;
  a29=arg[1]? arg[1][13] : 0;
  a20=(a29-a20);
  a20=casadi_sq(a20);
  a15=arg[1]? arg[1][14] : 0;
  a00=(a15-a00);
  a00=casadi_sq(a00);
  a20=(a20+a00);
  if (res[0]!=0) res[0][19]=a20;
  a20=arg[1]? arg[1][16] : 0;
  a11=(a11-a02);
  a11=(a24*a11);
  a11=(a23*a11);
  a02=(a20*a11);
  a02=casadi_sq(a02);
  a00=arg[1]? arg[1][17] : 0;
  a31=(a31-a33);
  a24=(a24*a31);
  a24=(a23*a24);
  a31=(a00*a24);
  a31=casadi_sq(a31);
  a02=(a02+a31);
  a31=(a08-a04);
  a31=(a26*a31);
  a31=(a23*a31);
  a31=(a21*a31);
  a31=casadi_sq(a31);
  a02=(a02-a31);
  a02=(a02+a27);
  if (res[0]!=0) res[0][20]=a02;
  a20=(a08-a20);
  a20=(a20*a11);
  a20=casadi_sq(a20);
  a08=(a08-a00);
  a08=(a08*a24);
  a08=casadi_sq(a08);
  a20=(a20+a08);
  a26=(a26*a04);
  a23=(a23*a26);
  a21=(a21*a23);
  a21=casadi_sq(a21);
  a20=(a20-a21);
  a20=(a20+a27);
  if (res[0]!=0) res[0][21]=a20;
  a20=arg[1]? arg[1][19] : 0;
  a27=casadi_sq(a20);
  a21=arg[1]? arg[1][20] : 0;
  a23=casadi_sq(a21);
  a27=(a27+a23);
  if (res[0]!=0) res[0][22]=a27;
  a27=(a10*a07);
  a10=(a10*a14);
  a23=(a27-a10);
  a23=(a03+a23);
  a23=(a20*a23);
  a26=(a10+a27);
  a26=(a18+a26);
  a26=(a21*a26);
  a23=(a23+a26);
  a26=arg[1]? arg[1][21] : 0;
  a23=(a23+a26);
  if (res[0]!=0) res[0][23]=a23;
  a07=(a12*a07);
  a23=(a07-a10);
  a23=(a03+a23);
  a23=(a20*a23);
  a12=(a12*a14);
  a14=(a12+a27);
  a14=(a18+a14);
  a14=(a21*a14);
  a23=(a23+a14);
  a23=(a23+a26);
  if (res[0]!=0) res[0][24]=a23;
  a23=(a07-a12);
  a23=(a03+a23);
  a23=(a20*a23);
  a14=(a12+a07);
  a14=(a18+a14);
  a14=(a21*a14);
  a23=(a23+a14);
  a23=(a23+a26);
  if (res[0]!=0) res[0][25]=a23;
  a27=(a27-a12);
  a03=(a03+a27);
  a03=(a20*a03);
  a10=(a10+a07);
  a18=(a18+a10);
  a18=(a21*a18);
  a03=(a03+a18);
  a03=(a03+a26);
  if (res[0]!=0) res[0][26]=a03;
  a05=(a20*a05);
  a13=(a21*a13);
  a05=(a05+a13);
  a05=(a05+a26);
  if (res[0]!=0) res[0][27]=a05;
  a29=(a20*a29);
  a15=(a21*a15);
  a29=(a29+a15);
  a29=(a29+a26);
  if (res[0]!=0) res[0][28]=a29;
  a20=(a20*a16);
  a21=(a21*a09);
  a20=(a20+a21);
  a20=(a20+a26);
  a26=arg[3]? arg[3][7] : 0;
  a21=arg[0]? arg[0][21] : 0;
  a26=(a26*a21);
  a25=(a25+a26);
  a28=(a28*a25);
  a20=(a20-a28);
  if (res[0]!=0) res[0][29]=a20;
  a20=cos(a19);
  a28=(a01*a20);
  a19=sin(a19);
  a25=(a32*a19);
  a28=(a28+a25);
  if (res[0]!=0) res[0][30]=a28;
  a32=(a32*a20);
  a01=(a01*a19);
  a32=(a32-a01);
  if (res[0]!=0) res[0][31]=a32;
  return 0;
}

CASADI_SYMBOL_EXPORT int lipm_opti_pessi_constr_h_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int lipm_opti_pessi_constr_h_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int lipm_opti_pessi_constr_h_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void lipm_opti_pessi_constr_h_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int lipm_opti_pessi_constr_h_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void lipm_opti_pessi_constr_h_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void lipm_opti_pessi_constr_h_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void lipm_opti_pessi_constr_h_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int lipm_opti_pessi_constr_h_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int lipm_opti_pessi_constr_h_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real lipm_opti_pessi_constr_h_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* lipm_opti_pessi_constr_h_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* lipm_opti_pessi_constr_h_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* lipm_opti_pessi_constr_h_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* lipm_opti_pessi_constr_h_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int lipm_opti_pessi_constr_h_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int lipm_opti_pessi_constr_h_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
