/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) lipm_step_ca_dyn_disc_phi_fun_jac_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[3] = {11, 1, 1};
static const casadi_int casadi_s1[3] = {8, 1, 1};
static const casadi_int casadi_s2[58] = 
  {22, 11, 0, 6, 12, 15, 21, 27,
  38, 39, 40, 41, 42, 44, 4, 7,
  11, 14, 17, 19, 4, 7, 12, 15,
  18, 20, 7, 13, 16, 4, 7, 11,
  14, 17, 19, 4, 7, 12, 15, 18,
  20, 4, 5, 6, 7, 11, 12, 16,
  17, 18, 19, 20, 0, 1, 2, 3,
  7, 21};

/* lipm_step_ca_dyn_disc_phi_fun_jac:(i0[11],i1[11],i2[8])->(o0[11],o1[22x11,44nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32;
  a00=5.0809240767486585e+00;
  a01=arg[1]? arg[1][7] : 0;
  a02=(a00*a01);
  a03=cosh(a02);
  a04=arg[0]? arg[0][0] : 0;
  a05=(a03*a04);
  a02=sinh(a02);
  a06=(a02/a00);
  a07=arg[0]? arg[0][3] : 0;
  a08=(a06*a07);
  a05=(a05+a08);
  a08=1.;
  a09=(a08-a03);
  a10=arg[0]? arg[0][6] : 0;
  a11=arg[1]? arg[1][4] : 0;
  a12=arg[0]? arg[0][8] : 0;
  a13=(a12-a10);
  a14=(a11*a13);
  a14=(a10+a14);
  a15=(a09*a14);
  a05=(a05+a15);
  if (res[0]!=0) res[0][0]=a05;
  a05=arg[0]? arg[0][1] : 0;
  a15=(a03*a05);
  a16=arg[0]? arg[0][4] : 0;
  a17=(a06*a16);
  a15=(a15+a17);
  a17=arg[0]? arg[0][7] : 0;
  a18=arg[0]? arg[0][9] : 0;
  a19=(a18-a17);
  a20=(a11*a19);
  a20=(a17+a20);
  a21=(a09*a20);
  a15=(a15+a21);
  if (res[0]!=0) res[0][1]=a15;
  a15=arg[0]? arg[0][2] : 0;
  a21=arg[0]? arg[0][5] : 0;
  a22=(a21*a01);
  a15=(a15+a22);
  if (res[0]!=0) res[0][2]=a15;
  a02=(a00*a02);
  a15=(a02*a04);
  a22=(a03*a07);
  a15=(a15+a22);
  a22=(a02*a14);
  a15=(a15-a22);
  if (res[0]!=0) res[0][3]=a15;
  a15=(a02*a05);
  a22=(a03*a16);
  a15=(a15+a22);
  a22=(a02*a20);
  a15=(a15-a22);
  if (res[0]!=0) res[0][4]=a15;
  a15=1.4999999999999999e-01;
  a15=(a01/a15);
  a10=(a10-a04);
  a22=12.;
  a23=2.5815789473684209e+01;
  a24=(a05-a20);
  a24=(a23*a24);
  a24=(a22*a24);
  a25=2.;
  a24=(a24/a25);
  a26=arg[1]? arg[1][6] : 0;
  a27=(a24+a26);
  a28=(a10*a27);
  a17=(a17-a05);
  a29=(a04-a14);
  a29=(a23*a29);
  a29=(a22*a29);
  a29=(a29/a25);
  a25=arg[1]? arg[1][5] : 0;
  a30=(a29+a25);
  a31=(a17*a30);
  a28=(a28-a31);
  a12=(a12-a04);
  a24=(a24-a26);
  a26=(a12*a24);
  a18=(a18-a05);
  a29=(a29-a25);
  a25=(a18*a29);
  a26=(a26-a25);
  a28=(a28+a26);
  a26=(a15*a28);
  a26=(a21+a26);
  if (res[0]!=0) res[0][5]=a26;
  a26=arg[1]? arg[1][0] : 0;
  if (res[0]!=0) res[0][6]=a26;
  a26=arg[1]? arg[1][1] : 0;
  if (res[0]!=0) res[0][7]=a26;
  a26=arg[1]? arg[1][2] : 0;
  if (res[0]!=0) res[0][8]=a26;
  a26=arg[1]? arg[1][3] : 0;
  if (res[0]!=0) res[0][9]=a26;
  a26=arg[0]? arg[0][10] : 0;
  a26=(a26+a01);
  if (res[0]!=0) res[0][10]=a26;
  a26=(a09*a13);
  if (res[1]!=0) res[1][0]=a26;
  a26=(a04*a02);
  a25=(a07*a03);
  a26=(a26+a25);
  a25=(a14*a02);
  a26=(a26-a25);
  if (res[1]!=0) res[1][1]=a26;
  if (res[1]!=0) res[1][2]=a03;
  if (res[1]!=0) res[1][3]=a06;
  a26=(a08-a11);
  a25=(a09*a26);
  if (res[1]!=0) res[1][4]=a25;
  a31=(a09*a11);
  if (res[1]!=0) res[1][5]=a31;
  a09=(a09*a19);
  if (res[1]!=0) res[1][6]=a09;
  a09=(a05*a02);
  a32=(a16*a03);
  a09=(a09+a32);
  a32=(a20*a02);
  a09=(a09-a32);
  if (res[1]!=0) res[1][7]=a09;
  if (res[1]!=0) res[1][8]=a03;
  if (res[1]!=0) res[1][9]=a06;
  if (res[1]!=0) res[1][10]=a25;
  if (res[1]!=0) res[1][11]=a31;
  if (res[1]!=0) res[1][12]=a21;
  if (res[1]!=0) res[1][13]=a08;
  if (res[1]!=0) res[1][14]=a01;
  a01=(a02*a13);
  a01=(-a01);
  if (res[1]!=0) res[1][15]=a01;
  a01=(a00*a03);
  a00=(a00*a01);
  a04=(a04*a00);
  a07=(a07*a02);
  a04=(a04+a07);
  a14=(a14*a00);
  a04=(a04-a14);
  if (res[1]!=0) res[1][16]=a04;
  if (res[1]!=0) res[1][17]=a02;
  if (res[1]!=0) res[1][18]=a03;
  a04=(a02*a26);
  a04=(-a04);
  if (res[1]!=0) res[1][19]=a04;
  a14=(a02*a11);
  a14=(-a14);
  if (res[1]!=0) res[1][20]=a14;
  a07=(a02*a19);
  a07=(-a07);
  if (res[1]!=0) res[1][21]=a07;
  a05=(a05*a00);
  a16=(a16*a02);
  a05=(a05+a16);
  a20=(a20*a00);
  a05=(a05-a20);
  if (res[1]!=0) res[1][22]=a05;
  if (res[1]!=0) res[1][23]=a02;
  if (res[1]!=0) res[1][24]=a03;
  if (res[1]!=0) res[1][25]=a04;
  if (res[1]!=0) res[1][26]=a14;
  a14=5.0000000000000000e-01;
  a13=(a23*a13);
  a13=(a22*a13);
  a13=(a14*a13);
  a04=(a17*a13);
  a19=(a23*a19);
  a19=(a22*a19);
  a19=(a14*a19);
  a03=(a10*a19);
  a04=(a04-a03);
  a13=(a18*a13);
  a19=(a12*a19);
  a13=(a13-a19);
  a04=(a04+a13);
  a04=(a15*a04);
  if (res[1]!=0) res[1][27]=a04;
  a04=(a18-a17);
  a04=(a15*a04);
  if (res[1]!=0) res[1][28]=a04;
  a04=(a10-a12);
  a04=(a15*a04);
  if (res[1]!=0) res[1][29]=a04;
  a04=6.6666666666666670e+00;
  a04=(a04*a28);
  if (res[1]!=0) res[1][30]=a04;
  a04=1.5489473684210526e+02;
  a28=(a04*a17);
  a28=(a27+a28);
  a13=(a04*a18);
  a13=(a24+a13);
  a28=(a28+a13);
  a28=(a15*a28);
  a28=(-a28);
  if (res[1]!=0) res[1][31]=a28;
  a28=(a04*a10);
  a28=(a28+a30);
  a04=(a04*a12);
  a04=(a04+a29);
  a28=(a28+a04);
  a28=(a15*a28);
  if (res[1]!=0) res[1][32]=a28;
  if (res[1]!=0) res[1][33]=a08;
  a26=(a23*a26);
  a26=(a22*a26);
  a26=(a14*a26);
  a28=(a17*a26);
  a27=(a27+a28);
  a28=(a18*a26);
  a27=(a27+a28);
  a27=(a15*a27);
  if (res[1]!=0) res[1][34]=a27;
  a27=(a10*a26);
  a27=(a27+a30);
  a26=(a12*a26);
  a27=(a27+a26);
  a27=(a15*a27);
  a27=(-a27);
  if (res[1]!=0) res[1][35]=a27;
  a23=(a23*a11);
  a22=(a22*a23);
  a14=(a14*a22);
  a17=(a17*a14);
  a18=(a18*a14);
  a24=(a24+a18);
  a17=(a17+a24);
  a17=(a15*a17);
  if (res[1]!=0) res[1][36]=a17;
  a10=(a10*a14);
  a12=(a12*a14);
  a12=(a12+a29);
  a10=(a10+a12);
  a15=(a15*a10);
  a15=(-a15);
  if (res[1]!=0) res[1][37]=a15;
  if (res[1]!=0) res[1][38]=a08;
  if (res[1]!=0) res[1][39]=a08;
  if (res[1]!=0) res[1][40]=a08;
  if (res[1]!=0) res[1][41]=a08;
  if (res[1]!=0) res[1][42]=a08;
  if (res[1]!=0) res[1][43]=a08;
  return 0;
}

CASADI_SYMBOL_EXPORT int lipm_step_ca_dyn_disc_phi_fun_jac(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int lipm_step_ca_dyn_disc_phi_fun_jac_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int lipm_step_ca_dyn_disc_phi_fun_jac_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void lipm_step_ca_dyn_disc_phi_fun_jac_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int lipm_step_ca_dyn_disc_phi_fun_jac_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void lipm_step_ca_dyn_disc_phi_fun_jac_release(int mem) {
}

CASADI_SYMBOL_EXPORT void lipm_step_ca_dyn_disc_phi_fun_jac_incref(void) {
}

CASADI_SYMBOL_EXPORT void lipm_step_ca_dyn_disc_phi_fun_jac_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int lipm_step_ca_dyn_disc_phi_fun_jac_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int lipm_step_ca_dyn_disc_phi_fun_jac_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real lipm_step_ca_dyn_disc_phi_fun_jac_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* lipm_step_ca_dyn_disc_phi_fun_jac_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* lipm_step_ca_dyn_disc_phi_fun_jac_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* lipm_step_ca_dyn_disc_phi_fun_jac_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* lipm_step_ca_dyn_disc_phi_fun_jac_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int lipm_step_ca_dyn_disc_phi_fun_jac_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int lipm_step_ca_dyn_disc_phi_fun_jac_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
