/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) lipm_opti_pessi_constr_h_0_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {22, 1, 1};
static const casadi_int casadi_s1[3] = {0, 1, 1};
static const casadi_int casadi_s2[3] = {8, 1, 1};
static const casadi_int casadi_s3[3] = {36, 1, 1};

/* lipm_opti_pessi_constr_h_0_fun:(i0[22],i1[22],i2[0],i3[8])->(o0[36]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36;
  a00=arg[1]? arg[1][0] : 0;
  a01=arg[1]? arg[1][11] : 0;
  a02=(a00-a01);
  if (res[0]!=0) res[0][0]=a02;
  a02=arg[1]? arg[1][1] : 0;
  a03=arg[1]? arg[1][12] : 0;
  a04=(a02-a03);
  if (res[0]!=0) res[0][1]=a04;
  a04=arg[1]? arg[1][2] : 0;
  a05=arg[1]? arg[1][13] : 0;
  a06=(a04-a05);
  if (res[0]!=0) res[0][2]=a06;
  a06=arg[1]? arg[1][3] : 0;
  a07=arg[1]? arg[1][14] : 0;
  a08=(a06-a07);
  if (res[0]!=0) res[0][3]=a08;
  a08=arg[1]? arg[1][4] : 0;
  a09=arg[1]? arg[1][15] : 0;
  a10=(a08-a09);
  if (res[0]!=0) res[0][4]=a10;
  a10=arg[1]? arg[1][5] : 0;
  a11=arg[1]? arg[1][16] : 0;
  a12=(a10-a11);
  if (res[0]!=0) res[0][5]=a12;
  a12=arg[1]? arg[1][6] : 0;
  a13=arg[1]? arg[1][17] : 0;
  a14=(a12-a13);
  if (res[0]!=0) res[0][6]=a14;
  a14=arg[1]? arg[1][7] : 0;
  a15=arg[1]? arg[1][18] : 0;
  a16=(a14-a15);
  if (res[0]!=0) res[0][7]=a16;
  a16=arg[0]? arg[0][6] : 0;
  a17=5.0809240767486585e+00;
  a18=(a17*a14);
  a19=cosh(a18);
  a20=arg[0]? arg[0][0] : 0;
  a21=(a19*a20);
  a18=sinh(a18);
  a18=(a18/a17);
  a22=arg[0]? arg[0][3] : 0;
  a22=(a18*a22);
  a21=(a21+a22);
  a22=1.;
  a23=(a22-a19);
  a24=arg[0]? arg[0][8] : 0;
  a25=(a24-a16);
  a25=(a08*a25);
  a25=(a16+a25);
  a26=(a23*a25);
  a21=(a21+a26);
  a26=arg[0]? arg[0][2] : 0;
  a27=arg[0]? arg[0][5] : 0;
  a27=(a27*a14);
  a26=(a26+a27);
  a27=cos(a26);
  a14=arg[3]? arg[3][0] : 0;
  a28=(a27*a14);
  a26=sin(a26);
  a29=arg[3]? arg[3][1] : 0;
  a30=(a26*a29);
  a28=(a28-a30);
  a28=(a21+a28);
  a16=(a16-a28);
  a16=casadi_sq(a16);
  a30=arg[0]? arg[0][7] : 0;
  a31=arg[0]? arg[0][1] : 0;
  a19=(a19*a31);
  a32=arg[0]? arg[0][4] : 0;
  a18=(a18*a32);
  a19=(a19+a18);
  a18=arg[0]? arg[0][9] : 0;
  a32=(a18-a30);
  a32=(a08*a32);
  a32=(a30+a32);
  a23=(a23*a32);
  a19=(a19+a23);
  a23=(a26*a14);
  a33=(a27*a29);
  a23=(a23+a33);
  a23=(a19+a23);
  a30=(a30-a23);
  a30=casadi_sq(a30);
  a16=(a16+a30);
  if (res[0]!=0) res[0][8]=a16;
  a16=arg[3]? arg[3][2] : 0;
  a30=(a27*a16);
  a33=arg[3]? arg[3][3] : 0;
  a34=(a26*a33);
  a30=(a30-a34);
  a30=(a21+a30);
  a24=(a24-a30);
  a24=casadi_sq(a24);
  a34=(a26*a16);
  a35=(a27*a33);
  a34=(a34+a35);
  a34=(a19+a34);
  a18=(a18-a34);
  a18=casadi_sq(a18);
  a24=(a24+a18);
  if (res[0]!=0) res[0][9]=a24;
  a28=(a00-a28);
  a28=casadi_sq(a28);
  a23=(a02-a23);
  a23=casadi_sq(a23);
  a28=(a28+a23);
  if (res[0]!=0) res[0][10]=a28;
  a30=(a04-a30);
  a30=casadi_sq(a30);
  a34=(a06-a34);
  a34=casadi_sq(a34);
  a30=(a30+a34);
  if (res[0]!=0) res[0][11]=a30;
  a30=12.;
  a34=2.5815789473684209e+01;
  a20=(a20-a25);
  a20=(a34*a20);
  a20=(a30*a20);
  a25=2.;
  a20=(a20/a25);
  a28=(a20+a10);
  a28=casadi_sq(a28);
  a31=(a31-a32);
  a31=(a34*a31);
  a31=(a30*a31);
  a31=(a31/a25);
  a32=(a31+a12);
  a32=casadi_sq(a32);
  a28=(a28+a32);
  a32=9.8100000000000005e+00;
  a23=8.0000000000000004e-01;
  a24=(a22-a08);
  a24=(a23*a24);
  a24=(a30*a24);
  a24=(a32*a24);
  a24=casadi_sq(a24);
  a28=(a28-a24);
  a24=1.0000000000000000e-03;
  a28=(a28+a24);
  if (res[0]!=0) res[0][12]=a28;
  a20=(a20-a10);
  a20=casadi_sq(a20);
  a31=(a31-a12);
  a31=casadi_sq(a31);
  a20=(a20+a31);
  a08=(a23*a08);
  a08=(a30*a08);
  a08=(a32*a08);
  a08=casadi_sq(a08);
  a20=(a20-a08);
  a20=(a20+a24);
  if (res[0]!=0) res[0][13]=a20;
  a20=arg[1]? arg[1][8] : 0;
  a08=casadi_sq(a20);
  a31=arg[1]? arg[1][9] : 0;
  a12=casadi_sq(a31);
  a08=(a08+a12);
  if (res[0]!=0) res[0][14]=a08;
  a08=2.0000000000000001e-01;
  a12=(a08*a27);
  a10=(a08*a26);
  a28=(a12-a10);
  a28=(a21+a28);
  a28=(a20*a28);
  a18=(a10+a12);
  a18=(a19+a18);
  a18=(a31*a18);
  a28=(a28+a18);
  a18=arg[1]? arg[1][10] : 0;
  a28=(a28+a18);
  if (res[0]!=0) res[0][15]=a28;
  a28=-2.0000000000000001e-01;
  a27=(a28*a27);
  a35=(a27-a10);
  a35=(a21+a35);
  a35=(a20*a35);
  a26=(a28*a26);
  a36=(a26+a12);
  a36=(a19+a36);
  a36=(a31*a36);
  a35=(a35+a36);
  a35=(a35+a18);
  if (res[0]!=0) res[0][16]=a35;
  a35=(a27-a26);
  a35=(a21+a35);
  a35=(a20*a35);
  a36=(a26+a27);
  a36=(a19+a36);
  a36=(a31*a36);
  a35=(a35+a36);
  a35=(a35+a18);
  if (res[0]!=0) res[0][17]=a35;
  a12=(a12-a26);
  a21=(a21+a12);
  a21=(a20*a21);
  a10=(a10+a27);
  a19=(a19+a10);
  a19=(a31*a19);
  a21=(a21+a19);
  a21=(a21+a18);
  if (res[0]!=0) res[0][18]=a21;
  a00=(a20*a00);
  a02=(a31*a02);
  a00=(a00+a02);
  a00=(a00+a18);
  if (res[0]!=0) res[0][19]=a00;
  a04=(a20*a04);
  a06=(a31*a06);
  a04=(a04+a06);
  a04=(a04+a18);
  if (res[0]!=0) res[0][20]=a04;
  a04=arg[3]? arg[3][4] : 0;
  a20=(a20*a04);
  a06=arg[3]? arg[3][5] : 0;
  a31=(a31*a06);
  a20=(a20+a31);
  a20=(a20+a18);
  a18=arg[3]? arg[3][6] : 0;
  a20=(a20-a18);
  if (res[0]!=0) res[0][21]=a20;
  a20=arg[0]? arg[0][17] : 0;
  a31=(a17*a15);
  a00=cosh(a31);
  a02=arg[0]? arg[0][11] : 0;
  a21=(a00*a02);
  a31=sinh(a31);
  a31=(a31/a17);
  a17=arg[0]? arg[0][14] : 0;
  a17=(a31*a17);
  a21=(a21+a17);
  a17=(a22-a00);
  a19=arg[0]? arg[0][19] : 0;
  a10=(a19-a20);
  a10=(a09*a10);
  a10=(a20+a10);
  a27=(a17*a10);
  a21=(a21+a27);
  a27=arg[0]? arg[0][13] : 0;
  a12=arg[0]? arg[0][16] : 0;
  a12=(a12*a15);
  a27=(a27+a12);
  a12=cos(a27);
  a15=(a12*a14);
  a27=sin(a27);
  a26=(a27*a29);
  a15=(a15-a26);
  a15=(a21+a15);
  a20=(a20-a15);
  a20=casadi_sq(a20);
  a26=arg[0]? arg[0][18] : 0;
  a35=arg[0]? arg[0][12] : 0;
  a00=(a00*a35);
  a36=arg[0]? arg[0][15] : 0;
  a31=(a31*a36);
  a00=(a00+a31);
  a31=arg[0]? arg[0][20] : 0;
  a36=(a31-a26);
  a36=(a09*a36);
  a36=(a26+a36);
  a17=(a17*a36);
  a00=(a00+a17);
  a14=(a27*a14);
  a29=(a12*a29);
  a14=(a14+a29);
  a14=(a00+a14);
  a26=(a26-a14);
  a26=casadi_sq(a26);
  a20=(a20+a26);
  if (res[0]!=0) res[0][22]=a20;
  a20=(a12*a16);
  a26=(a27*a33);
  a20=(a20-a26);
  a20=(a21+a20);
  a19=(a19-a20);
  a19=casadi_sq(a19);
  a16=(a27*a16);
  a33=(a12*a33);
  a16=(a16+a33);
  a16=(a00+a16);
  a31=(a31-a16);
  a31=casadi_sq(a31);
  a19=(a19+a31);
  if (res[0]!=0) res[0][23]=a19;
  a15=(a01-a15);
  a15=casadi_sq(a15);
  a14=(a03-a14);
  a14=casadi_sq(a14);
  a15=(a15+a14);
  if (res[0]!=0) res[0][24]=a15;
  a20=(a05-a20);
  a20=casadi_sq(a20);
  a16=(a07-a16);
  a16=casadi_sq(a16);
  a20=(a20+a16);
  if (res[0]!=0) res[0][25]=a20;
  a02=(a02-a10);
  a02=(a34*a02);
  a02=(a30*a02);
  a02=(a02/a25);
  a10=(a02+a11);
  a10=casadi_sq(a10);
  a35=(a35-a36);
  a34=(a34*a35);
  a34=(a30*a34);
  a34=(a34/a25);
  a25=(a34+a13);
  a25=casadi_sq(a25);
  a10=(a10+a25);
  a22=(a22-a09);
  a22=(a23*a22);
  a22=(a30*a22);
  a22=(a32*a22);
  a22=casadi_sq(a22);
  a10=(a10-a22);
  a10=(a10+a24);
  if (res[0]!=0) res[0][26]=a10;
  a02=(a02-a11);
  a02=casadi_sq(a02);
  a34=(a34-a13);
  a34=casadi_sq(a34);
  a02=(a02+a34);
  a23=(a23*a09);
  a30=(a30*a23);
  a32=(a32*a30);
  a32=casadi_sq(a32);
  a02=(a02-a32);
  a02=(a02+a24);
  if (res[0]!=0) res[0][27]=a02;
  a02=arg[1]? arg[1][19] : 0;
  a24=casadi_sq(a02);
  a32=arg[1]? arg[1][20] : 0;
  a30=casadi_sq(a32);
  a24=(a24+a30);
  if (res[0]!=0) res[0][28]=a24;
  a24=(a08*a12);
  a08=(a08*a27);
  a30=(a24-a08);
  a30=(a21+a30);
  a30=(a02*a30);
  a23=(a08+a24);
  a23=(a00+a23);
  a23=(a32*a23);
  a30=(a30+a23);
  a23=arg[1]? arg[1][21] : 0;
  a30=(a30+a23);
  if (res[0]!=0) res[0][29]=a30;
  a12=(a28*a12);
  a30=(a12-a08);
  a30=(a21+a30);
  a30=(a02*a30);
  a28=(a28*a27);
  a27=(a28+a24);
  a27=(a00+a27);
  a27=(a32*a27);
  a30=(a30+a27);
  a30=(a30+a23);
  if (res[0]!=0) res[0][30]=a30;
  a30=(a12-a28);
  a30=(a21+a30);
  a30=(a02*a30);
  a27=(a28+a12);
  a27=(a00+a27);
  a27=(a32*a27);
  a30=(a30+a27);
  a30=(a30+a23);
  if (res[0]!=0) res[0][31]=a30;
  a24=(a24-a28);
  a21=(a21+a24);
  a21=(a02*a21);
  a08=(a08+a12);
  a00=(a00+a08);
  a00=(a32*a00);
  a21=(a21+a00);
  a21=(a21+a23);
  if (res[0]!=0) res[0][32]=a21;
  a01=(a02*a01);
  a03=(a32*a03);
  a01=(a01+a03);
  a01=(a01+a23);
  if (res[0]!=0) res[0][33]=a01;
  a05=(a02*a05);
  a07=(a32*a07);
  a05=(a05+a07);
  a05=(a05+a23);
  if (res[0]!=0) res[0][34]=a05;
  a02=(a02*a04);
  a32=(a32*a06);
  a02=(a02+a32);
  a02=(a02+a23);
  a23=arg[3]? arg[3][7] : 0;
  a32=arg[0]? arg[0][21] : 0;
  a23=(a23*a32);
  a18=(a18+a23);
  a02=(a02-a18);
  if (res[0]!=0) res[0][35]=a02;
  return 0;
}

CASADI_SYMBOL_EXPORT int lipm_opti_pessi_constr_h_0_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int lipm_opti_pessi_constr_h_0_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int lipm_opti_pessi_constr_h_0_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void lipm_opti_pessi_constr_h_0_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int lipm_opti_pessi_constr_h_0_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void lipm_opti_pessi_constr_h_0_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void lipm_opti_pessi_constr_h_0_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void lipm_opti_pessi_constr_h_0_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int lipm_opti_pessi_constr_h_0_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int lipm_opti_pessi_constr_h_0_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real lipm_opti_pessi_constr_h_0_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* lipm_opti_pessi_constr_h_0_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* lipm_opti_pessi_constr_h_0_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* lipm_opti_pessi_constr_h_0_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* lipm_opti_pessi_constr_h_0_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int lipm_opti_pessi_constr_h_0_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int lipm_opti_pessi_constr_h_0_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
