/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) lipm_opti_pessi_constr_h_0_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {22, 1, 1};
static const casadi_int casadi_s1[3] = {0, 1, 1};
static const casadi_int casadi_s2[3] = {8, 1, 1};
static const casadi_int casadi_s3[3] = {40, 1, 1};

/* lipm_opti_pessi_constr_h_0_fun:(i0[22],i1[22],i2[0],i3[8])->(o0[40]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39, a40;
  a00=arg[1]? arg[1][0] : 0;
  a01=arg[1]? arg[1][11] : 0;
  a02=(a00-a01);
  if (res[0]!=0) res[0][0]=a02;
  a02=arg[1]? arg[1][1] : 0;
  a03=arg[1]? arg[1][12] : 0;
  a04=(a02-a03);
  if (res[0]!=0) res[0][1]=a04;
  a04=arg[1]? arg[1][2] : 0;
  a05=arg[1]? arg[1][13] : 0;
  a06=(a04-a05);
  if (res[0]!=0) res[0][2]=a06;
  a06=arg[1]? arg[1][3] : 0;
  a07=arg[1]? arg[1][14] : 0;
  a08=(a06-a07);
  if (res[0]!=0) res[0][3]=a08;
  a08=arg[1]? arg[1][4] : 0;
  a09=arg[1]? arg[1][15] : 0;
  a10=(a08-a09);
  if (res[0]!=0) res[0][4]=a10;
  a10=arg[1]? arg[1][5] : 0;
  a11=arg[1]? arg[1][16] : 0;
  a12=(a10-a11);
  if (res[0]!=0) res[0][5]=a12;
  a12=arg[1]? arg[1][6] : 0;
  a13=arg[1]? arg[1][17] : 0;
  a14=(a12-a13);
  if (res[0]!=0) res[0][6]=a14;
  a14=arg[1]? arg[1][7] : 0;
  a15=arg[1]? arg[1][18] : 0;
  a16=(a14-a15);
  if (res[0]!=0) res[0][7]=a16;
  a16=arg[0]? arg[0][6] : 0;
  a17=5.0809240767486585e+00;
  a18=(a17*a14);
  a19=cosh(a18);
  a20=arg[0]? arg[0][0] : 0;
  a21=(a19*a20);
  a18=sinh(a18);
  a18=(a18/a17);
  a22=arg[0]? arg[0][3] : 0;
  a23=(a18*a22);
  a21=(a21+a23);
  a23=1.;
  a24=(a23-a19);
  a25=arg[0]? arg[0][8] : 0;
  a26=(a25-a16);
  a26=(a08*a26);
  a26=(a16+a26);
  a27=(a24*a26);
  a21=(a21+a27);
  a27=arg[0]? arg[0][2] : 0;
  a28=arg[0]? arg[0][5] : 0;
  a28=(a28*a14);
  a28=(a27+a28);
  a14=cos(a28);
  a29=arg[3]? arg[3][0] : 0;
  a30=(a14*a29);
  a28=sin(a28);
  a31=arg[3]? arg[3][1] : 0;
  a32=(a28*a31);
  a30=(a30-a32);
  a30=(a21+a30);
  a16=(a16-a30);
  a16=casadi_sq(a16);
  a32=arg[0]? arg[0][7] : 0;
  a33=arg[0]? arg[0][1] : 0;
  a19=(a19*a33);
  a34=arg[0]? arg[0][4] : 0;
  a18=(a18*a34);
  a19=(a19+a18);
  a18=arg[0]? arg[0][9] : 0;
  a35=(a18-a32);
  a35=(a08*a35);
  a35=(a32+a35);
  a24=(a24*a35);
  a19=(a19+a24);
  a24=(a28*a29);
  a36=(a14*a31);
  a24=(a24+a36);
  a24=(a19+a24);
  a32=(a32-a24);
  a32=casadi_sq(a32);
  a16=(a16+a32);
  if (res[0]!=0) res[0][8]=a16;
  a16=arg[3]? arg[3][2] : 0;
  a32=(a14*a16);
  a36=arg[3]? arg[3][3] : 0;
  a37=(a28*a36);
  a32=(a32-a37);
  a32=(a21+a32);
  a25=(a25-a32);
  a25=casadi_sq(a25);
  a37=(a28*a16);
  a38=(a14*a36);
  a37=(a37+a38);
  a37=(a19+a37);
  a18=(a18-a37);
  a18=casadi_sq(a18);
  a25=(a25+a18);
  if (res[0]!=0) res[0][9]=a25;
  a30=(a00-a30);
  a30=casadi_sq(a30);
  a24=(a02-a24);
  a24=casadi_sq(a24);
  a30=(a30+a24);
  if (res[0]!=0) res[0][10]=a30;
  a32=(a04-a32);
  a32=casadi_sq(a32);
  a37=(a06-a37);
  a37=casadi_sq(a37);
  a32=(a32+a37);
  if (res[0]!=0) res[0][11]=a32;
  a32=12.;
  a37=2.5815789473684209e+01;
  a20=(a20-a26);
  a20=(a37*a20);
  a20=(a32*a20);
  a26=2.;
  a20=(a20/a26);
  a30=(a20+a10);
  a30=casadi_sq(a30);
  a33=(a33-a35);
  a33=(a37*a33);
  a33=(a32*a33);
  a33=(a33/a26);
  a35=(a33+a12);
  a35=casadi_sq(a35);
  a30=(a30+a35);
  a35=9.8100000000000005e+00;
  a24=8.0000000000000004e-01;
  a25=(a23-a08);
  a25=(a24*a25);
  a25=(a32*a25);
  a25=(a35*a25);
  a25=casadi_sq(a25);
  a30=(a30-a25);
  a25=1.0000000000000000e-03;
  a30=(a30+a25);
  if (res[0]!=0) res[0][12]=a30;
  a20=(a20-a10);
  a20=casadi_sq(a20);
  a33=(a33-a12);
  a33=casadi_sq(a33);
  a20=(a20+a33);
  a08=(a24*a08);
  a08=(a32*a08);
  a08=(a35*a08);
  a08=casadi_sq(a08);
  a20=(a20-a08);
  a20=(a20+a25);
  if (res[0]!=0) res[0][13]=a20;
  a20=arg[1]? arg[1][8] : 0;
  a08=casadi_sq(a20);
  a33=arg[1]? arg[1][9] : 0;
  a12=casadi_sq(a33);
  a08=(a08+a12);
  if (res[0]!=0) res[0][14]=a08;
  a08=2.0000000000000001e-01;
  a12=(a08*a14);
  a10=(a08*a28);
  a30=(a12-a10);
  a30=(a21+a30);
  a30=(a20*a30);
  a18=(a10+a12);
  a18=(a19+a18);
  a18=(a33*a18);
  a30=(a30+a18);
  a18=arg[1]? arg[1][10] : 0;
  a30=(a30+a18);
  if (res[0]!=0) res[0][15]=a30;
  a30=-2.0000000000000001e-01;
  a14=(a30*a14);
  a38=(a14-a10);
  a38=(a21+a38);
  a38=(a20*a38);
  a28=(a30*a28);
  a39=(a28+a12);
  a39=(a19+a39);
  a39=(a33*a39);
  a38=(a38+a39);
  a38=(a38+a18);
  if (res[0]!=0) res[0][16]=a38;
  a38=(a14-a28);
  a38=(a21+a38);
  a38=(a20*a38);
  a39=(a28+a14);
  a39=(a19+a39);
  a39=(a33*a39);
  a38=(a38+a39);
  a38=(a38+a18);
  if (res[0]!=0) res[0][17]=a38;
  a12=(a12-a28);
  a21=(a21+a12);
  a21=(a20*a21);
  a10=(a10+a14);
  a19=(a19+a10);
  a19=(a33*a19);
  a21=(a21+a19);
  a21=(a21+a18);
  if (res[0]!=0) res[0][18]=a21;
  a00=(a20*a00);
  a02=(a33*a02);
  a00=(a00+a02);
  a00=(a00+a18);
  if (res[0]!=0) res[0][19]=a00;
  a04=(a20*a04);
  a06=(a33*a06);
  a04=(a04+a06);
  a04=(a04+a18);
  if (res[0]!=0) res[0][20]=a04;
  a04=arg[3]? arg[3][4] : 0;
  a20=(a20*a04);
  a06=arg[3]? arg[3][5] : 0;
  a33=(a33*a06);
  a20=(a20+a33);
  a20=(a20+a18);
  a18=1.5000000000000000e+00;
  a33=arg[3]? arg[3][6] : 0;
  a00=(a18*a33);
  a20=(a20-a00);
  if (res[0]!=0) res[0][21]=a20;
  a20=cos(a27);
  a00=(a22*a20);
  a27=sin(a27);
  a02=(a34*a27);
  a00=(a00+a02);
  if (res[0]!=0) res[0][22]=a00;
  a34=(a34*a20);
  a22=(a22*a27);
  a34=(a34-a22);
  if (res[0]!=0) res[0][23]=a34;
  a34=arg[0]? arg[0][17] : 0;
  a22=(a17*a15);
  a27=cosh(a22);
  a20=arg[0]? arg[0][11] : 0;
  a00=(a27*a20);
  a22=sinh(a22);
  a22=(a22/a17);
  a17=arg[0]? arg[0][14] : 0;
  a02=(a22*a17);
  a00=(a00+a02);
  a02=(a23-a27);
  a21=arg[0]? arg[0][19] : 0;
  a19=(a21-a34);
  a19=(a09*a19);
  a19=(a34+a19);
  a10=(a02*a19);
  a00=(a00+a10);
  a10=arg[0]? arg[0][13] : 0;
  a14=arg[0]? arg[0][16] : 0;
  a14=(a14*a15);
  a14=(a10+a14);
  a15=cos(a14);
  a12=(a15*a29);
  a14=sin(a14);
  a28=(a14*a31);
  a12=(a12-a28);
  a12=(a00+a12);
  a34=(a34-a12);
  a34=casadi_sq(a34);
  a28=arg[0]? arg[0][18] : 0;
  a38=arg[0]? arg[0][12] : 0;
  a27=(a27*a38);
  a39=arg[0]? arg[0][15] : 0;
  a22=(a22*a39);
  a27=(a27+a22);
  a22=arg[0]? arg[0][20] : 0;
  a40=(a22-a28);
  a40=(a09*a40);
  a40=(a28+a40);
  a02=(a02*a40);
  a27=(a27+a02);
  a29=(a14*a29);
  a31=(a15*a31);
  a29=(a29+a31);
  a29=(a27+a29);
  a28=(a28-a29);
  a28=casadi_sq(a28);
  a34=(a34+a28);
  if (res[0]!=0) res[0][24]=a34;
  a34=(a15*a16);
  a28=(a14*a36);
  a34=(a34-a28);
  a34=(a00+a34);
  a21=(a21-a34);
  a21=casadi_sq(a21);
  a16=(a14*a16);
  a36=(a15*a36);
  a16=(a16+a36);
  a16=(a27+a16);
  a22=(a22-a16);
  a22=casadi_sq(a22);
  a21=(a21+a22);
  if (res[0]!=0) res[0][25]=a21;
  a12=(a01-a12);
  a12=casadi_sq(a12);
  a29=(a03-a29);
  a29=casadi_sq(a29);
  a12=(a12+a29);
  if (res[0]!=0) res[0][26]=a12;
  a34=(a05-a34);
  a34=casadi_sq(a34);
  a16=(a07-a16);
  a16=casadi_sq(a16);
  a34=(a34+a16);
  if (res[0]!=0) res[0][27]=a34;
  a20=(a20-a19);
  a20=(a37*a20);
  a20=(a32*a20);
  a20=(a20/a26);
  a19=(a20+a11);
  a19=casadi_sq(a19);
  a38=(a38-a40);
  a37=(a37*a38);
  a37=(a32*a37);
  a37=(a37/a26);
  a26=(a37+a13);
  a26=casadi_sq(a26);
  a19=(a19+a26);
  a23=(a23-a09);
  a23=(a24*a23);
  a23=(a32*a23);
  a23=(a35*a23);
  a23=casadi_sq(a23);
  a19=(a19-a23);
  a19=(a19+a25);
  if (res[0]!=0) res[0][28]=a19;
  a20=(a20-a11);
  a20=casadi_sq(a20);
  a37=(a37-a13);
  a37=casadi_sq(a37);
  a20=(a20+a37);
  a24=(a24*a09);
  a32=(a32*a24);
  a35=(a35*a32);
  a35=casadi_sq(a35);
  a20=(a20-a35);
  a20=(a20+a25);
  if (res[0]!=0) res[0][29]=a20;
  a20=arg[1]? arg[1][19] : 0;
  a25=casadi_sq(a20);
  a35=arg[1]? arg[1][20] : 0;
  a32=casadi_sq(a35);
  a25=(a25+a32);
  if (res[0]!=0) res[0][30]=a25;
  a25=(a08*a15);
  a08=(a08*a14);
  a32=(a25-a08);
  a32=(a00+a32);
  a32=(a20*a32);
  a24=(a08+a25);
  a24=(a27+a24);
  a24=(a35*a24);
  a32=(a32+a24);
  a24=arg[1]? arg[1][21] : 0;
  a32=(a32+a24);
  if (res[0]!=0) res[0][31]=a32;
  a15=(a30*a15);
  a32=(a15-a08);
  a32=(a00+a32);
  a32=(a20*a32);
  a30=(a30*a14);
  a14=(a30+a25);
  a14=(a27+a14);
  a14=(a35*a14);
  a32=(a32+a14);
  a32=(a32+a24);
  if (res[0]!=0) res[0][32]=a32;
  a32=(a15-a30);
  a32=(a00+a32);
  a32=(a20*a32);
  a14=(a30+a15);
  a14=(a27+a14);
  a14=(a35*a14);
  a32=(a32+a14);
  a32=(a32+a24);
  if (res[0]!=0) res[0][33]=a32;
  a25=(a25-a30);
  a00=(a00+a25);
  a00=(a20*a00);
  a08=(a08+a15);
  a27=(a27+a08);
  a27=(a35*a27);
  a00=(a00+a27);
  a00=(a00+a24);
  if (res[0]!=0) res[0][34]=a00;
  a01=(a20*a01);
  a03=(a35*a03);
  a01=(a01+a03);
  a01=(a01+a24);
  if (res[0]!=0) res[0][35]=a01;
  a05=(a20*a05);
  a07=(a35*a07);
  a05=(a05+a07);
  a05=(a05+a24);
  if (res[0]!=0) res[0][36]=a05;
  a20=(a20*a04);
  a35=(a35*a06);
  a20=(a20+a35);
  a20=(a20+a24);
  a24=arg[3]? arg[3][7] : 0;
  a35=arg[0]? arg[0][21] : 0;
  a24=(a24*a35);
  a33=(a33+a24);
  a18=(a18*a33);
  a20=(a20-a18);
  if (res[0]!=0) res[0][37]=a20;
  a20=cos(a10);
  a18=(a17*a20);
  a10=sin(a10);
  a33=(a39*a10);
  a18=(a18+a33);
  if (res[0]!=0) res[0][38]=a18;
  a39=(a39*a20);
  a17=(a17*a10);
  a39=(a39-a17);
  if (res[0]!=0) res[0][39]=a39;
  return 0;
}

CASADI_SYMBOL_EXPORT int lipm_opti_pessi_constr_h_0_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int lipm_opti_pessi_constr_h_0_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int lipm_opti_pessi_constr_h_0_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void lipm_opti_pessi_constr_h_0_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int lipm_opti_pessi_constr_h_0_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void lipm_opti_pessi_constr_h_0_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void lipm_opti_pessi_constr_h_0_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void lipm_opti_pessi_constr_h_0_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int lipm_opti_pessi_constr_h_0_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int lipm_opti_pessi_constr_h_0_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real lipm_opti_pessi_constr_h_0_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* lipm_opti_pessi_constr_h_0_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* lipm_opti_pessi_constr_h_0_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* lipm_opti_pessi_constr_h_0_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* lipm_opti_pessi_constr_h_0_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int lipm_opti_pessi_constr_h_0_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int lipm_opti_pessi_constr_h_0_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
