/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) lipm_step_dyn_disc_phi_fun_jac_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[3] = {8, 1, 1};
static const casadi_int casadi_s1[3] = {5, 1, 1};
static const casadi_int casadi_s2[3] = {4, 1, 1};
static const casadi_int casadi_s3[35] = 
  {13, 8, 0, 5, 10, 15, 20, 21,
  22, 23, 24, 4, 5, 7, 9, 11,
  4, 6, 8, 10, 12, 4, 5, 7,
  9, 11, 4, 6, 8, 10, 12, 0,
  1, 2, 3};

/* lipm_step_dyn_disc_phi_fun_jac:(i0[8],i1[5],i2[4])->(o0[8],o1[13x8,24nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13;
  a00=1.5623039875841591e+00;
  a01=arg[0]? arg[0][0] : 0;
  a02=(a00*a01);
  a03=2.3624259392867469e-01;
  a04=arg[0]? arg[0][2] : 0;
  a05=(a03*a04);
  a02=(a02+a05);
  a05=-5.6230398758415912e-01;
  a06=arg[0]? arg[0][4] : 0;
  a07=arg[1]? arg[1][4] : 0;
  a08=arg[0]? arg[0][6] : 0;
  a08=(a08-a06);
  a09=(a07*a08);
  a06=(a06+a09);
  a09=(a05*a06);
  a02=(a02+a09);
  if (res[0]!=0) res[0][0]=a02;
  a02=arg[0]? arg[0][1] : 0;
  a09=(a00*a02);
  a10=arg[0]? arg[0][3] : 0;
  a11=(a03*a10);
  a09=(a09+a11);
  a11=arg[0]? arg[0][5] : 0;
  a12=arg[0]? arg[0][7] : 0;
  a12=(a12-a11);
  a13=(a07*a12);
  a11=(a11+a13);
  a13=(a05*a11);
  a09=(a09+a13);
  if (res[0]!=0) res[0][1]=a09;
  a09=6.0987890695797331e+00;
  a01=(a09*a01);
  a04=(a00*a04);
  a01=(a01+a04);
  a06=(a09*a06);
  a01=(a01-a06);
  if (res[0]!=0) res[0][2]=a01;
  a02=(a09*a02);
  a10=(a00*a10);
  a02=(a02+a10);
  a11=(a09*a11);
  a02=(a02-a11);
  if (res[0]!=0) res[0][3]=a02;
  a02=arg[1]? arg[1][0] : 0;
  if (res[0]!=0) res[0][4]=a02;
  a02=arg[1]? arg[1][1] : 0;
  if (res[0]!=0) res[0][5]=a02;
  a02=arg[1]? arg[1][2] : 0;
  if (res[0]!=0) res[0][6]=a02;
  a02=arg[1]? arg[1][3] : 0;
  if (res[0]!=0) res[0][7]=a02;
  a02=(a05*a08);
  if (res[1]!=0) res[1][0]=a02;
  if (res[1]!=0) res[1][1]=a00;
  if (res[1]!=0) res[1][2]=a03;
  a02=1.;
  a11=(a02-a07);
  a10=(a05*a11);
  if (res[1]!=0) res[1][3]=a10;
  a01=(a05*a07);
  if (res[1]!=0) res[1][4]=a01;
  a05=(a05*a12);
  if (res[1]!=0) res[1][5]=a05;
  if (res[1]!=0) res[1][6]=a00;
  if (res[1]!=0) res[1][7]=a03;
  if (res[1]!=0) res[1][8]=a10;
  if (res[1]!=0) res[1][9]=a01;
  a08=(a09*a08);
  a08=(-a08);
  if (res[1]!=0) res[1][10]=a08;
  if (res[1]!=0) res[1][11]=a09;
  if (res[1]!=0) res[1][12]=a00;
  a11=(a09*a11);
  a11=(-a11);
  if (res[1]!=0) res[1][13]=a11;
  a07=(a09*a07);
  a07=(-a07);
  if (res[1]!=0) res[1][14]=a07;
  a12=(a09*a12);
  a12=(-a12);
  if (res[1]!=0) res[1][15]=a12;
  if (res[1]!=0) res[1][16]=a09;
  if (res[1]!=0) res[1][17]=a00;
  if (res[1]!=0) res[1][18]=a11;
  if (res[1]!=0) res[1][19]=a07;
  if (res[1]!=0) res[1][20]=a02;
  if (res[1]!=0) res[1][21]=a02;
  if (res[1]!=0) res[1][22]=a02;
  if (res[1]!=0) res[1][23]=a02;
  return 0;
}

CASADI_SYMBOL_EXPORT int lipm_step_dyn_disc_phi_fun_jac(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int lipm_step_dyn_disc_phi_fun_jac_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int lipm_step_dyn_disc_phi_fun_jac_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void lipm_step_dyn_disc_phi_fun_jac_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int lipm_step_dyn_disc_phi_fun_jac_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void lipm_step_dyn_disc_phi_fun_jac_release(int mem) {
}

CASADI_SYMBOL_EXPORT void lipm_step_dyn_disc_phi_fun_jac_incref(void) {
}

CASADI_SYMBOL_EXPORT void lipm_step_dyn_disc_phi_fun_jac_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int lipm_step_dyn_disc_phi_fun_jac_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int lipm_step_dyn_disc_phi_fun_jac_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real lipm_step_dyn_disc_phi_fun_jac_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* lipm_step_dyn_disc_phi_fun_jac_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* lipm_step_dyn_disc_phi_fun_jac_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* lipm_step_dyn_disc_phi_fun_jac_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* lipm_step_dyn_disc_phi_fun_jac_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int lipm_step_dyn_disc_phi_fun_jac_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int lipm_step_dyn_disc_phi_fun_jac_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
