/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) lipm_opti_pessi_cost_y_0_fun_jac_ut_xt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[3] = {22, 1, 1};
static const casadi_int casadi_s1[3] = {0, 1, 1};
static const casadi_int casadi_s2[3] = {0, 0, 1};
static const casadi_int casadi_s3[3] = {8, 1, 1};
static const casadi_int casadi_s4[3] = {38, 1, 1};
static const casadi_int casadi_s5[151] = 
  {44, 38, 0, 1, 2, 3, 4, 5,
  6, 7, 9, 11, 13, 15, 24, 33,
  42, 51, 52, 53, 54, 55, 56, 57,
  58, 59, 60, 61, 62, 64, 66, 68,
  70, 79, 88, 97, 106, 107, 108, 109,
  110, 22, 23, 24, 25, 26, 27, 32,
  0, 28, 1, 29, 2, 30, 3, 31,
  0, 4, 7, 22, 24, 25, 27, 28,
  30, 1, 4, 7, 23, 24, 26, 27,
  29, 31, 2, 4, 7, 22, 24, 25,
  27, 28, 30, 3, 4, 7, 23, 24,
  26, 27, 29, 31, 4, 5, 6, 7,
  33, 34, 35, 36, 37, 38, 43, 11,
  39, 12, 40, 13, 41, 14, 42, 11,
  15, 18, 33, 35, 36, 38, 39, 41,
  12, 15, 18, 34, 35, 37, 38, 40,
  42, 13, 15, 18, 33, 35, 36, 38,
  39, 41, 14, 15, 18, 34, 35, 37,
  38, 40, 42, 15, 16, 17, 18};
static const casadi_int casadi_s6[3] = {38, 0, 1};

/* lipm_opti_pessi_cost_y_0_fun_jac_ut_xt:(i0[22],i1[22],i2[0],i3[],i4[8])->(o0[38],o1[44x38,110nz],o2[38x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39, a40, a41, a42, a43, a44, a45, a46, a47;
  casadi_real a48;
  a00=arg[0]? arg[0][0] : 0;
  if (res[0]!=0) res[0][0]=a00;
  a01=arg[0]? arg[0][1] : 0;
  if (res[0]!=0) res[0][1]=a01;
  a02=arg[0]? arg[0][2] : 0;
  if (res[0]!=0) res[0][2]=a02;
  a03=arg[0]? arg[0][3] : 0;
  if (res[0]!=0) res[0][3]=a03;
  a04=arg[0]? arg[0][4] : 0;
  if (res[0]!=0) res[0][4]=a04;
  a05=arg[0]? arg[0][5] : 0;
  if (res[0]!=0) res[0][5]=a05;
  a06=arg[0]? arg[0][10] : 0;
  if (res[0]!=0) res[0][6]=a06;
  a06=arg[1]? arg[1][0] : 0;
  a07=arg[0]? arg[0][6] : 0;
  a08=(a06-a07);
  if (res[0]!=0) res[0][7]=a08;
  a08=arg[1]? arg[1][1] : 0;
  a09=arg[0]? arg[0][7] : 0;
  a10=(a08-a09);
  if (res[0]!=0) res[0][8]=a10;
  a10=arg[1]? arg[1][2] : 0;
  a11=arg[0]? arg[0][8] : 0;
  a12=(a10-a11);
  if (res[0]!=0) res[0][9]=a12;
  a12=arg[1]? arg[1][3] : 0;
  a13=arg[0]? arg[0][9] : 0;
  a14=(a12-a13);
  if (res[0]!=0) res[0][10]=a14;
  a14=5.0809240767486585e+00;
  a15=arg[1]? arg[1][7] : 0;
  a16=(a14*a15);
  a17=cosh(a16);
  a18=(a17*a00);
  a16=sinh(a16);
  a19=(a16/a14);
  a20=(a19*a03);
  a18=(a18+a20);
  a20=1.;
  a21=(a20-a17);
  a22=arg[1]? arg[1][4] : 0;
  a11=(a11-a07);
  a23=(a22*a11);
  a07=(a07+a23);
  a23=(a21*a07);
  a18=(a18+a23);
  a23=(a05*a15);
  a02=(a02+a23);
  a23=cos(a02);
  a24=arg[4]? arg[4][0] : 0;
  a25=(a23*a24);
  a02=sin(a02);
  a26=arg[4]? arg[4][1] : 0;
  a27=(a02*a26);
  a25=(a25-a27);
  a25=(a18+a25);
  a06=(a06-a25);
  if (res[0]!=0) res[0][11]=a06;
  a06=(a17*a01);
  a25=(a19*a04);
  a06=(a06+a25);
  a13=(a13-a09);
  a25=(a22*a13);
  a09=(a09+a25);
  a25=(a21*a09);
  a06=(a06+a25);
  a25=(a02*a24);
  a27=(a23*a26);
  a25=(a25+a27);
  a25=(a06+a25);
  a08=(a08-a25);
  if (res[0]!=0) res[0][12]=a08;
  a08=arg[4]? arg[4][2] : 0;
  a25=(a23*a08);
  a27=arg[4]? arg[4][3] : 0;
  a28=(a02*a27);
  a25=(a25-a28);
  a18=(a18+a25);
  a10=(a10-a18);
  if (res[0]!=0) res[0][13]=a10;
  a10=(a02*a08);
  a18=(a23*a27);
  a10=(a10+a18);
  a06=(a06+a10);
  a12=(a12-a06);
  if (res[0]!=0) res[0][14]=a12;
  a12=5.0000000000000000e-01;
  a06=(a22-a12);
  if (res[0]!=0) res[0][15]=a06;
  a06=arg[1]? arg[1][5] : 0;
  if (res[0]!=0) res[0][16]=a06;
  a06=arg[1]? arg[1][6] : 0;
  if (res[0]!=0) res[0][17]=a06;
  a06=6.8750000000000006e-02;
  a10=(a15-a06);
  if (res[0]!=0) res[0][18]=a10;
  a10=arg[0]? arg[0][11] : 0;
  if (res[0]!=0) res[0][19]=a10;
  a18=arg[0]? arg[0][12] : 0;
  if (res[0]!=0) res[0][20]=a18;
  a25=arg[0]? arg[0][13] : 0;
  if (res[0]!=0) res[0][21]=a25;
  a28=arg[0]? arg[0][14] : 0;
  if (res[0]!=0) res[0][22]=a28;
  a29=arg[0]? arg[0][15] : 0;
  if (res[0]!=0) res[0][23]=a29;
  a30=arg[0]? arg[0][16] : 0;
  if (res[0]!=0) res[0][24]=a30;
  a31=arg[0]? arg[0][21] : 0;
  if (res[0]!=0) res[0][25]=a31;
  a31=arg[1]? arg[1][11] : 0;
  a32=arg[0]? arg[0][17] : 0;
  a33=(a31-a32);
  if (res[0]!=0) res[0][26]=a33;
  a33=arg[1]? arg[1][12] : 0;
  a34=arg[0]? arg[0][18] : 0;
  a35=(a33-a34);
  if (res[0]!=0) res[0][27]=a35;
  a35=arg[1]? arg[1][13] : 0;
  a36=arg[0]? arg[0][19] : 0;
  a37=(a35-a36);
  if (res[0]!=0) res[0][28]=a37;
  a37=arg[1]? arg[1][14] : 0;
  a38=arg[0]? arg[0][20] : 0;
  a39=(a37-a38);
  if (res[0]!=0) res[0][29]=a39;
  a39=arg[1]? arg[1][18] : 0;
  a40=(a14*a39);
  a41=cosh(a40);
  a42=(a41*a10);
  a40=sinh(a40);
  a43=(a40/a14);
  a44=(a43*a28);
  a42=(a42+a44);
  a44=(a20-a41);
  a45=arg[1]? arg[1][15] : 0;
  a36=(a36-a32);
  a46=(a45*a36);
  a32=(a32+a46);
  a46=(a44*a32);
  a42=(a42+a46);
  a46=(a30*a39);
  a25=(a25+a46);
  a46=cos(a25);
  a47=(a46*a24);
  a25=sin(a25);
  a48=(a25*a26);
  a47=(a47-a48);
  a47=(a42+a47);
  a31=(a31-a47);
  if (res[0]!=0) res[0][30]=a31;
  a31=(a41*a18);
  a47=(a43*a29);
  a31=(a31+a47);
  a38=(a38-a34);
  a47=(a45*a38);
  a34=(a34+a47);
  a47=(a44*a34);
  a31=(a31+a47);
  a47=(a25*a24);
  a48=(a46*a26);
  a47=(a47+a48);
  a47=(a31+a47);
  a33=(a33-a47);
  if (res[0]!=0) res[0][31]=a33;
  a33=(a46*a08);
  a47=(a25*a27);
  a33=(a33-a47);
  a42=(a42+a33);
  a35=(a35-a42);
  if (res[0]!=0) res[0][32]=a35;
  a35=(a25*a08);
  a42=(a46*a27);
  a35=(a35+a42);
  a31=(a31+a35);
  a37=(a37-a31);
  if (res[0]!=0) res[0][33]=a37;
  a12=(a45-a12);
  if (res[0]!=0) res[0][34]=a12;
  a12=arg[1]? arg[1][16] : 0;
  if (res[0]!=0) res[0][35]=a12;
  a12=arg[1]? arg[1][17] : 0;
  if (res[0]!=0) res[0][36]=a12;
  a06=(a39-a06);
  if (res[0]!=0) res[0][37]=a06;
  if (res[1]!=0) res[1][0]=a20;
  if (res[1]!=0) res[1][1]=a20;
  if (res[1]!=0) res[1][2]=a20;
  if (res[1]!=0) res[1][3]=a20;
  if (res[1]!=0) res[1][4]=a20;
  if (res[1]!=0) res[1][5]=a20;
  if (res[1]!=0) res[1][6]=a20;
  if (res[1]!=0) res[1][7]=a20;
  a06=-1.;
  if (res[1]!=0) res[1][8]=a06;
  if (res[1]!=0) res[1][9]=a20;
  if (res[1]!=0) res[1][10]=a06;
  if (res[1]!=0) res[1][11]=a20;
  if (res[1]!=0) res[1][12]=a06;
  if (res[1]!=0) res[1][13]=a20;
  if (res[1]!=0) res[1][14]=a06;
  if (res[1]!=0) res[1][15]=a20;
  a11=(a21*a11);
  a11=(-a11);
  if (res[1]!=0) res[1][16]=a11;
  a16=(a14*a16);
  a00=(a00*a16);
  a03=(a03*a17);
  a00=(a00+a03);
  a07=(a07*a16);
  a00=(a00-a07);
  a07=(a02*a05);
  a03=(a24*a07);
  a05=(a23*a05);
  a12=(a26*a05);
  a03=(a03+a12);
  a03=(a00-a03);
  a03=(-a03);
  if (res[1]!=0) res[1][17]=a03;
  a03=(-a17);
  if (res[1]!=0) res[1][18]=a03;
  a12=(a24*a02);
  a37=(a26*a23);
  a12=(a12+a37);
  if (res[1]!=0) res[1][19]=a12;
  a19=(-a19);
  if (res[1]!=0) res[1][20]=a19;
  a12=(a02*a15);
  a37=(a24*a12);
  a15=(a23*a15);
  a31=(a26*a15);
  a37=(a37+a31);
  if (res[1]!=0) res[1][21]=a37;
  a37=(a20-a22);
  a37=(a21*a37);
  a37=(-a37);
  if (res[1]!=0) res[1][22]=a37;
  a22=(a21*a22);
  a22=(-a22);
  if (res[1]!=0) res[1][23]=a22;
  if (res[1]!=0) res[1][24]=a20;
  a21=(a21*a13);
  a21=(-a21);
  if (res[1]!=0) res[1][25]=a21;
  a01=(a01*a16);
  a04=(a04*a17);
  a01=(a01+a04);
  a09=(a09*a16);
  a01=(a01-a09);
  a09=(a24*a05);
  a16=(a26*a07);
  a09=(a09-a16);
  a09=(a01+a09);
  a09=(-a09);
  if (res[1]!=0) res[1][26]=a09;
  if (res[1]!=0) res[1][27]=a03;
  a09=(a24*a23);
  a16=(a26*a02);
  a09=(a09-a16);
  a09=(-a09);
  if (res[1]!=0) res[1][28]=a09;
  if (res[1]!=0) res[1][29]=a19;
  a09=(a24*a15);
  a16=(a26*a12);
  a09=(a09-a16);
  a09=(-a09);
  if (res[1]!=0) res[1][30]=a09;
  if (res[1]!=0) res[1][31]=a37;
  if (res[1]!=0) res[1][32]=a22;
  if (res[1]!=0) res[1][33]=a20;
  if (res[1]!=0) res[1][34]=a11;
  a11=(a08*a07);
  a09=(a27*a05);
  a11=(a11+a09);
  a00=(a00-a11);
  a00=(-a00);
  if (res[1]!=0) res[1][35]=a00;
  if (res[1]!=0) res[1][36]=a03;
  a00=(a08*a02);
  a11=(a27*a23);
  a00=(a00+a11);
  if (res[1]!=0) res[1][37]=a00;
  if (res[1]!=0) res[1][38]=a19;
  a00=(a08*a12);
  a11=(a27*a15);
  a00=(a00+a11);
  if (res[1]!=0) res[1][39]=a00;
  if (res[1]!=0) res[1][40]=a37;
  if (res[1]!=0) res[1][41]=a22;
  if (res[1]!=0) res[1][42]=a20;
  if (res[1]!=0) res[1][43]=a21;
  a05=(a08*a05);
  a07=(a27*a07);
  a05=(a05-a07);
  a01=(a01+a05);
  a01=(-a01);
  if (res[1]!=0) res[1][44]=a01;
  if (res[1]!=0) res[1][45]=a03;
  a23=(a08*a23);
  a02=(a27*a02);
  a23=(a23-a02);
  a23=(-a23);
  if (res[1]!=0) res[1][46]=a23;
  if (res[1]!=0) res[1][47]=a19;
  a15=(a08*a15);
  a12=(a27*a12);
  a15=(a15-a12);
  a15=(-a15);
  if (res[1]!=0) res[1][48]=a15;
  if (res[1]!=0) res[1][49]=a37;
  if (res[1]!=0) res[1][50]=a22;
  if (res[1]!=0) res[1][51]=a20;
  if (res[1]!=0) res[1][52]=a20;
  if (res[1]!=0) res[1][53]=a20;
  if (res[1]!=0) res[1][54]=a20;
  if (res[1]!=0) res[1][55]=a20;
  if (res[1]!=0) res[1][56]=a20;
  if (res[1]!=0) res[1][57]=a20;
  if (res[1]!=0) res[1][58]=a20;
  if (res[1]!=0) res[1][59]=a20;
  if (res[1]!=0) res[1][60]=a20;
  if (res[1]!=0) res[1][61]=a20;
  if (res[1]!=0) res[1][62]=a20;
  if (res[1]!=0) res[1][63]=a06;
  if (res[1]!=0) res[1][64]=a20;
  if (res[1]!=0) res[1][65]=a06;
  if (res[1]!=0) res[1][66]=a20;
  if (res[1]!=0) res[1][67]=a06;
  if (res[1]!=0) res[1][68]=a20;
  if (res[1]!=0) res[1][69]=a06;
  if (res[1]!=0) res[1][70]=a20;
  a36=(a44*a36);
  a36=(-a36);
  if (res[1]!=0) res[1][71]=a36;
  a14=(a14*a40);
  a10=(a10*a14);
  a28=(a28*a41);
  a10=(a10+a28);
  a32=(a32*a14);
  a10=(a10-a32);
  a32=(a25*a30);
  a28=(a24*a32);
  a30=(a46*a30);
  a40=(a26*a30);
  a28=(a28+a40);
  a28=(a10-a28);
  a28=(-a28);
  if (res[1]!=0) res[1][72]=a28;
  a28=(-a41);
  if (res[1]!=0) res[1][73]=a28;
  a40=(a24*a25);
  a06=(a26*a46);
  a40=(a40+a06);
  if (res[1]!=0) res[1][74]=a40;
  a43=(-a43);
  if (res[1]!=0) res[1][75]=a43;
  a40=(a25*a39);
  a06=(a24*a40);
  a39=(a46*a39);
  a22=(a26*a39);
  a06=(a06+a22);
  if (res[1]!=0) res[1][76]=a06;
  a06=(a20-a45);
  a06=(a44*a06);
  a06=(-a06);
  if (res[1]!=0) res[1][77]=a06;
  a45=(a44*a45);
  a45=(-a45);
  if (res[1]!=0) res[1][78]=a45;
  if (res[1]!=0) res[1][79]=a20;
  a44=(a44*a38);
  a44=(-a44);
  if (res[1]!=0) res[1][80]=a44;
  a18=(a18*a14);
  a29=(a29*a41);
  a18=(a18+a29);
  a34=(a34*a14);
  a18=(a18-a34);
  a34=(a24*a30);
  a14=(a26*a32);
  a34=(a34-a14);
  a34=(a18+a34);
  a34=(-a34);
  if (res[1]!=0) res[1][81]=a34;
  if (res[1]!=0) res[1][82]=a28;
  a34=(a24*a46);
  a14=(a26*a25);
  a34=(a34-a14);
  a34=(-a34);
  if (res[1]!=0) res[1][83]=a34;
  if (res[1]!=0) res[1][84]=a43;
  a24=(a24*a39);
  a26=(a26*a40);
  a24=(a24-a26);
  a24=(-a24);
  if (res[1]!=0) res[1][85]=a24;
  if (res[1]!=0) res[1][86]=a06;
  if (res[1]!=0) res[1][87]=a45;
  if (res[1]!=0) res[1][88]=a20;
  if (res[1]!=0) res[1][89]=a36;
  a36=(a08*a32);
  a24=(a27*a30);
  a36=(a36+a24);
  a10=(a10-a36);
  a10=(-a10);
  if (res[1]!=0) res[1][90]=a10;
  if (res[1]!=0) res[1][91]=a28;
  a10=(a08*a25);
  a36=(a27*a46);
  a10=(a10+a36);
  if (res[1]!=0) res[1][92]=a10;
  if (res[1]!=0) res[1][93]=a43;
  a10=(a08*a40);
  a36=(a27*a39);
  a10=(a10+a36);
  if (res[1]!=0) res[1][94]=a10;
  if (res[1]!=0) res[1][95]=a06;
  if (res[1]!=0) res[1][96]=a45;
  if (res[1]!=0) res[1][97]=a20;
  if (res[1]!=0) res[1][98]=a44;
  a30=(a08*a30);
  a32=(a27*a32);
  a30=(a30-a32);
  a18=(a18+a30);
  a18=(-a18);
  if (res[1]!=0) res[1][99]=a18;
  if (res[1]!=0) res[1][100]=a28;
  a46=(a08*a46);
  a25=(a27*a25);
  a46=(a46-a25);
  a46=(-a46);
  if (res[1]!=0) res[1][101]=a46;
  if (res[1]!=0) res[1][102]=a43;
  a08=(a08*a39);
  a27=(a27*a40);
  a08=(a08-a27);
  a08=(-a08);
  if (res[1]!=0) res[1][103]=a08;
  if (res[1]!=0) res[1][104]=a06;
  if (res[1]!=0) res[1][105]=a45;
  if (res[1]!=0) res[1][106]=a20;
  if (res[1]!=0) res[1][107]=a20;
  if (res[1]!=0) res[1][108]=a20;
  if (res[1]!=0) res[1][109]=a20;
  return 0;
}

CASADI_SYMBOL_EXPORT int lipm_opti_pessi_cost_y_0_fun_jac_ut_xt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int lipm_opti_pessi_cost_y_0_fun_jac_ut_xt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int lipm_opti_pessi_cost_y_0_fun_jac_ut_xt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void lipm_opti_pessi_cost_y_0_fun_jac_ut_xt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int lipm_opti_pessi_cost_y_0_fun_jac_ut_xt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void lipm_opti_pessi_cost_y_0_fun_jac_ut_xt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void lipm_opti_pessi_cost_y_0_fun_jac_ut_xt_incref(void) {
}

CASADI_SYMBOL_EXPORT void lipm_opti_pessi_cost_y_0_fun_jac_ut_xt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int lipm_opti_pessi_cost_y_0_fun_jac_ut_xt_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int lipm_opti_pessi_cost_y_0_fun_jac_ut_xt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real lipm_opti_pessi_cost_y_0_fun_jac_ut_xt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* lipm_opti_pessi_cost_y_0_fun_jac_ut_xt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* lipm_opti_pessi_cost_y_0_fun_jac_ut_xt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* lipm_opti_pessi_cost_y_0_fun_jac_ut_xt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    case 4: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* lipm_opti_pessi_cost_y_0_fun_jac_ut_xt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    case 2: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int lipm_opti_pessi_cost_y_0_fun_jac_ut_xt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int lipm_opti_pessi_cost_y_0_fun_jac_ut_xt_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
