/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) lipm_opti_pessi_cost_y_fun_jac_ut_xt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {22, 1, 1};
static const casadi_int casadi_s1[3] = {0, 1, 1};
static const casadi_int casadi_s2[3] = {0, 0, 1};
static const casadi_int casadi_s3[3] = {8, 1, 1};
static const casadi_int casadi_s4[3] = {40, 1, 1};
static const casadi_int casadi_s5[167] = 
  {44, 40, 0, 1, 2, 5, 6, 7,
  8, 9, 11, 13, 15, 17, 26, 35,
  44, 53, 54, 55, 56, 57, 62, 63,
  64, 67, 68, 69, 70, 71, 73, 75,
  77, 79, 88, 97, 106, 115, 116, 117,
  118, 119, 124, 22, 23, 22, 23, 24,
  25, 26, 27, 32, 0, 28, 1, 29,
  2, 30, 3, 31, 0, 4, 7, 22,
  24, 25, 27, 28, 30, 1, 4, 7,
  23, 24, 26, 27, 29, 31, 2, 4,
  7, 22, 24, 25, 27, 28, 30, 3,
  4, 7, 23, 24, 26, 27, 29, 31,
  4, 5, 6, 7, 22, 23, 24, 25,
  26, 33, 34, 33, 34, 35, 36, 37,
  38, 43, 11, 39, 12, 40, 13, 41,
  14, 42, 11, 15, 18, 33, 35, 36,
  38, 39, 41, 12, 15, 18, 34, 35,
  37, 38, 40, 42, 13, 15, 18, 33,
  35, 36, 38, 39, 41, 14, 15, 18,
  34, 35, 37, 38, 40, 42, 15, 16,
  17, 18, 33, 34, 35, 36, 37};
static const casadi_int casadi_s6[3] = {40, 0, 1};

/* lipm_opti_pessi_cost_y_fun_jac_ut_xt:(i0[22],i1[22],i2[0],i3[],i4[8])->(o0[40],o1[44x40,124nz],o2[40x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39, a40, a41, a42, a43, a44, a45, a46, a47;
  casadi_real a48, a49, a50, a51, a52, a53, a54, a55, a56, a57, a58, a59;
  casadi_real a60, a61, a62;
  a00=arg[0]? arg[0][0] : 0;
  if (res[0]!=0) res[0][0]=a00;
  a01=arg[0]? arg[0][1] : 0;
  if (res[0]!=0) res[0][1]=a01;
  a02=arg[0]? arg[0][2] : 0;
  a03=-4.3633231299858238e-01;
  a04=(a02-a03);
  a05=1.;
  a06=2.;
  a07=(a00-a06);
  a08=casadi_sq(a07);
  a09=(a01-a06);
  a10=casadi_sq(a09);
  a08=(a08+a10);
  a08=(a05+a08);
  a04=(a04/a08);
  if (res[0]!=0) res[0][2]=a04;
  a10=arg[0]? arg[0][3] : 0;
  if (res[0]!=0) res[0][3]=a10;
  a11=arg[0]? arg[0][4] : 0;
  if (res[0]!=0) res[0][4]=a11;
  a12=arg[0]? arg[0][5] : 0;
  if (res[0]!=0) res[0][5]=a12;
  a13=arg[0]? arg[0][10] : 0;
  if (res[0]!=0) res[0][6]=a13;
  a13=arg[1]? arg[1][0] : 0;
  a14=arg[0]? arg[0][6] : 0;
  a15=(a13-a14);
  if (res[0]!=0) res[0][7]=a15;
  a15=arg[1]? arg[1][1] : 0;
  a16=arg[0]? arg[0][7] : 0;
  a17=(a15-a16);
  if (res[0]!=0) res[0][8]=a17;
  a17=arg[1]? arg[1][2] : 0;
  a18=arg[0]? arg[0][8] : 0;
  a19=(a17-a18);
  if (res[0]!=0) res[0][9]=a19;
  a19=arg[1]? arg[1][3] : 0;
  a20=arg[0]? arg[0][9] : 0;
  a21=(a19-a20);
  if (res[0]!=0) res[0][10]=a21;
  a21=5.0809240767486585e+00;
  a22=arg[1]? arg[1][7] : 0;
  a23=(a21*a22);
  a24=cosh(a23);
  a25=(a24*a00);
  a23=sinh(a23);
  a26=(a23/a21);
  a27=(a26*a10);
  a25=(a25+a27);
  a27=(a05-a24);
  a28=arg[1]? arg[1][4] : 0;
  a18=(a18-a14);
  a29=(a28*a18);
  a14=(a14+a29);
  a29=(a27*a14);
  a25=(a25+a29);
  a29=(a12*a22);
  a29=(a02+a29);
  a30=cos(a29);
  a31=arg[4]? arg[4][0] : 0;
  a32=(a30*a31);
  a29=sin(a29);
  a33=arg[4]? arg[4][1] : 0;
  a34=(a29*a33);
  a32=(a32-a34);
  a32=(a25+a32);
  a13=(a13-a32);
  if (res[0]!=0) res[0][11]=a13;
  a13=(a24*a01);
  a32=(a26*a11);
  a13=(a13+a32);
  a20=(a20-a16);
  a32=(a28*a20);
  a16=(a16+a32);
  a32=(a27*a16);
  a13=(a13+a32);
  a32=(a29*a31);
  a34=(a30*a33);
  a32=(a32+a34);
  a32=(a13+a32);
  a15=(a15-a32);
  if (res[0]!=0) res[0][12]=a15;
  a15=arg[4]? arg[4][2] : 0;
  a32=(a30*a15);
  a34=arg[4]? arg[4][3] : 0;
  a35=(a29*a34);
  a32=(a32-a35);
  a25=(a25+a32);
  a17=(a17-a25);
  if (res[0]!=0) res[0][13]=a17;
  a17=(a29*a15);
  a25=(a30*a34);
  a17=(a17+a25);
  a13=(a13+a17);
  a19=(a19-a13);
  if (res[0]!=0) res[0][14]=a19;
  a19=5.0000000000000000e-01;
  a13=(a28-a19);
  if (res[0]!=0) res[0][15]=a13;
  a13=arg[1]? arg[1][5] : 0;
  if (res[0]!=0) res[0][16]=a13;
  a13=arg[1]? arg[1][6] : 0;
  if (res[0]!=0) res[0][17]=a13;
  a13=6.8750000000000006e-02;
  a17=(a22-a13);
  if (res[0]!=0) res[0][18]=a17;
  a17=(1./a08);
  a25=(a05-a17);
  a32=cos(a02);
  a35=(a11*a32);
  a02=sin(a02);
  a36=(a10*a02);
  a35=(a35-a36);
  a36=(a25*a35);
  if (res[0]!=0) res[0][19]=a36;
  a36=arg[0]? arg[0][11] : 0;
  if (res[0]!=0) res[0][20]=a36;
  a37=arg[0]? arg[0][12] : 0;
  if (res[0]!=0) res[0][21]=a37;
  a38=arg[0]? arg[0][13] : 0;
  a03=(a38-a03);
  a39=(a36-a06);
  a40=casadi_sq(a39);
  a06=(a37-a06);
  a41=casadi_sq(a06);
  a40=(a40+a41);
  a40=(a05+a40);
  a03=(a03/a40);
  if (res[0]!=0) res[0][22]=a03;
  a41=arg[0]? arg[0][14] : 0;
  if (res[0]!=0) res[0][23]=a41;
  a42=arg[0]? arg[0][15] : 0;
  if (res[0]!=0) res[0][24]=a42;
  a43=arg[0]? arg[0][16] : 0;
  if (res[0]!=0) res[0][25]=a43;
  a44=arg[0]? arg[0][21] : 0;
  if (res[0]!=0) res[0][26]=a44;
  a44=arg[1]? arg[1][11] : 0;
  a45=arg[0]? arg[0][17] : 0;
  a46=(a44-a45);
  if (res[0]!=0) res[0][27]=a46;
  a46=arg[1]? arg[1][12] : 0;
  a47=arg[0]? arg[0][18] : 0;
  a48=(a46-a47);
  if (res[0]!=0) res[0][28]=a48;
  a48=arg[1]? arg[1][13] : 0;
  a49=arg[0]? arg[0][19] : 0;
  a50=(a48-a49);
  if (res[0]!=0) res[0][29]=a50;
  a50=arg[1]? arg[1][14] : 0;
  a51=arg[0]? arg[0][20] : 0;
  a52=(a50-a51);
  if (res[0]!=0) res[0][30]=a52;
  a52=arg[1]? arg[1][18] : 0;
  a53=(a21*a52);
  a54=cosh(a53);
  a55=(a54*a36);
  a53=sinh(a53);
  a56=(a53/a21);
  a57=(a56*a41);
  a55=(a55+a57);
  a57=(a05-a54);
  a58=arg[1]? arg[1][15] : 0;
  a49=(a49-a45);
  a59=(a58*a49);
  a45=(a45+a59);
  a59=(a57*a45);
  a55=(a55+a59);
  a59=(a43*a52);
  a59=(a38+a59);
  a60=cos(a59);
  a61=(a60*a31);
  a59=sin(a59);
  a62=(a59*a33);
  a61=(a61-a62);
  a61=(a55+a61);
  a44=(a44-a61);
  if (res[0]!=0) res[0][31]=a44;
  a44=(a54*a37);
  a61=(a56*a42);
  a44=(a44+a61);
  a51=(a51-a47);
  a61=(a58*a51);
  a47=(a47+a61);
  a61=(a57*a47);
  a44=(a44+a61);
  a61=(a59*a31);
  a62=(a60*a33);
  a61=(a61+a62);
  a61=(a44+a61);
  a46=(a46-a61);
  if (res[0]!=0) res[0][32]=a46;
  a46=(a60*a15);
  a61=(a59*a34);
  a46=(a46-a61);
  a55=(a55+a46);
  a48=(a48-a55);
  if (res[0]!=0) res[0][33]=a48;
  a48=(a59*a15);
  a55=(a60*a34);
  a48=(a48+a55);
  a44=(a44+a48);
  a50=(a50-a44);
  if (res[0]!=0) res[0][34]=a50;
  a19=(a58-a19);
  if (res[0]!=0) res[0][35]=a19;
  a19=arg[1]? arg[1][16] : 0;
  if (res[0]!=0) res[0][36]=a19;
  a19=arg[1]? arg[1][17] : 0;
  if (res[0]!=0) res[0][37]=a19;
  a13=(a52-a13);
  if (res[0]!=0) res[0][38]=a13;
  a13=(1./a40);
  a19=(a05-a13);
  a50=cos(a38);
  a44=(a42*a50);
  a38=sin(a38);
  a48=(a41*a38);
  a44=(a44-a48);
  a48=(a19*a44);
  if (res[0]!=0) res[0][39]=a48;
  if (res[1]!=0) res[1][0]=a05;
  if (res[1]!=0) res[1][1]=a05;
  a04=(a04/a08);
  a07=(a07+a07);
  a48=(a04*a07);
  a48=(-a48);
  if (res[1]!=0) res[1][2]=a48;
  a09=(a09+a09);
  a04=(a04*a09);
  a04=(-a04);
  if (res[1]!=0) res[1][3]=a04;
  if (res[1]!=0) res[1][4]=a17;
  if (res[1]!=0) res[1][5]=a05;
  if (res[1]!=0) res[1][6]=a05;
  if (res[1]!=0) res[1][7]=a05;
  if (res[1]!=0) res[1][8]=a05;
  if (res[1]!=0) res[1][9]=a05;
  a04=-1.;
  if (res[1]!=0) res[1][10]=a04;
  if (res[1]!=0) res[1][11]=a05;
  if (res[1]!=0) res[1][12]=a04;
  if (res[1]!=0) res[1][13]=a05;
  if (res[1]!=0) res[1][14]=a04;
  if (res[1]!=0) res[1][15]=a05;
  if (res[1]!=0) res[1][16]=a04;
  if (res[1]!=0) res[1][17]=a05;
  a18=(a27*a18);
  a18=(-a18);
  if (res[1]!=0) res[1][18]=a18;
  a23=(a21*a23);
  a00=(a00*a23);
  a48=(a10*a24);
  a00=(a00+a48);
  a14=(a14*a23);
  a00=(a00-a14);
  a14=(a29*a12);
  a48=(a31*a14);
  a12=(a30*a12);
  a55=(a33*a12);
  a48=(a48+a55);
  a48=(a00-a48);
  a48=(-a48);
  if (res[1]!=0) res[1][19]=a48;
  a48=(-a24);
  if (res[1]!=0) res[1][20]=a48;
  a55=(a31*a29);
  a46=(a33*a30);
  a55=(a55+a46);
  if (res[1]!=0) res[1][21]=a55;
  a26=(-a26);
  if (res[1]!=0) res[1][22]=a26;
  a55=(a29*a22);
  a46=(a31*a55);
  a22=(a30*a22);
  a61=(a33*a22);
  a46=(a46+a61);
  if (res[1]!=0) res[1][23]=a46;
  a46=(a05-a28);
  a46=(a27*a46);
  a46=(-a46);
  if (res[1]!=0) res[1][24]=a46;
  a28=(a27*a28);
  a28=(-a28);
  if (res[1]!=0) res[1][25]=a28;
  if (res[1]!=0) res[1][26]=a05;
  a27=(a27*a20);
  a27=(-a27);
  if (res[1]!=0) res[1][27]=a27;
  a01=(a01*a23);
  a24=(a11*a24);
  a01=(a01+a24);
  a16=(a16*a23);
  a01=(a01-a16);
  a16=(a31*a12);
  a23=(a33*a14);
  a16=(a16-a23);
  a16=(a01+a16);
  a16=(-a16);
  if (res[1]!=0) res[1][28]=a16;
  if (res[1]!=0) res[1][29]=a48;
  a16=(a31*a30);
  a23=(a33*a29);
  a16=(a16-a23);
  a16=(-a16);
  if (res[1]!=0) res[1][30]=a16;
  if (res[1]!=0) res[1][31]=a26;
  a16=(a31*a22);
  a23=(a33*a55);
  a16=(a16-a23);
  a16=(-a16);
  if (res[1]!=0) res[1][32]=a16;
  if (res[1]!=0) res[1][33]=a46;
  if (res[1]!=0) res[1][34]=a28;
  if (res[1]!=0) res[1][35]=a05;
  if (res[1]!=0) res[1][36]=a18;
  a18=(a15*a14);
  a16=(a34*a12);
  a18=(a18+a16);
  a00=(a00-a18);
  a00=(-a00);
  if (res[1]!=0) res[1][37]=a00;
  if (res[1]!=0) res[1][38]=a48;
  a00=(a15*a29);
  a18=(a34*a30);
  a00=(a00+a18);
  if (res[1]!=0) res[1][39]=a00;
  if (res[1]!=0) res[1][40]=a26;
  a00=(a15*a55);
  a18=(a34*a22);
  a00=(a00+a18);
  if (res[1]!=0) res[1][41]=a00;
  if (res[1]!=0) res[1][42]=a46;
  if (res[1]!=0) res[1][43]=a28;
  if (res[1]!=0) res[1][44]=a05;
  if (res[1]!=0) res[1][45]=a27;
  a12=(a15*a12);
  a14=(a34*a14);
  a12=(a12-a14);
  a01=(a01+a12);
  a01=(-a01);
  if (res[1]!=0) res[1][46]=a01;
  if (res[1]!=0) res[1][47]=a48;
  a30=(a15*a30);
  a29=(a34*a29);
  a30=(a30-a29);
  a30=(-a30);
  if (res[1]!=0) res[1][48]=a30;
  if (res[1]!=0) res[1][49]=a26;
  a22=(a15*a22);
  a55=(a34*a55);
  a22=(a22-a55);
  a22=(-a22);
  if (res[1]!=0) res[1][50]=a22;
  if (res[1]!=0) res[1][51]=a46;
  if (res[1]!=0) res[1][52]=a28;
  if (res[1]!=0) res[1][53]=a05;
  if (res[1]!=0) res[1][54]=a05;
  if (res[1]!=0) res[1][55]=a05;
  if (res[1]!=0) res[1][56]=a05;
  a17=(a17/a08);
  a07=(a17*a07);
  a07=(a35*a07);
  if (res[1]!=0) res[1][57]=a07;
  a17=(a17*a09);
  a35=(a35*a17);
  if (res[1]!=0) res[1][58]=a35;
  a11=(a11*a02);
  a10=(a10*a32);
  a11=(a11+a10);
  a11=(a25*a11);
  a11=(-a11);
  if (res[1]!=0) res[1][59]=a11;
  a02=(a25*a02);
  a02=(-a02);
  if (res[1]!=0) res[1][60]=a02;
  a25=(a25*a32);
  if (res[1]!=0) res[1][61]=a25;
  if (res[1]!=0) res[1][62]=a05;
  if (res[1]!=0) res[1][63]=a05;
  a03=(a03/a40);
  a39=(a39+a39);
  a25=(a03*a39);
  a25=(-a25);
  if (res[1]!=0) res[1][64]=a25;
  a06=(a06+a06);
  a03=(a03*a06);
  a03=(-a03);
  if (res[1]!=0) res[1][65]=a03;
  if (res[1]!=0) res[1][66]=a13;
  if (res[1]!=0) res[1][67]=a05;
  if (res[1]!=0) res[1][68]=a05;
  if (res[1]!=0) res[1][69]=a05;
  if (res[1]!=0) res[1][70]=a05;
  if (res[1]!=0) res[1][71]=a05;
  if (res[1]!=0) res[1][72]=a04;
  if (res[1]!=0) res[1][73]=a05;
  if (res[1]!=0) res[1][74]=a04;
  if (res[1]!=0) res[1][75]=a05;
  if (res[1]!=0) res[1][76]=a04;
  if (res[1]!=0) res[1][77]=a05;
  if (res[1]!=0) res[1][78]=a04;
  if (res[1]!=0) res[1][79]=a05;
  a49=(a57*a49);
  a49=(-a49);
  if (res[1]!=0) res[1][80]=a49;
  a21=(a21*a53);
  a36=(a36*a21);
  a53=(a41*a54);
  a36=(a36+a53);
  a45=(a45*a21);
  a36=(a36-a45);
  a45=(a59*a43);
  a53=(a31*a45);
  a43=(a60*a43);
  a04=(a33*a43);
  a53=(a53+a04);
  a53=(a36-a53);
  a53=(-a53);
  if (res[1]!=0) res[1][81]=a53;
  a53=(-a54);
  if (res[1]!=0) res[1][82]=a53;
  a04=(a31*a59);
  a03=(a33*a60);
  a04=(a04+a03);
  if (res[1]!=0) res[1][83]=a04;
  a56=(-a56);
  if (res[1]!=0) res[1][84]=a56;
  a04=(a59*a52);
  a03=(a31*a04);
  a52=(a60*a52);
  a25=(a33*a52);
  a03=(a03+a25);
  if (res[1]!=0) res[1][85]=a03;
  a03=(a05-a58);
  a03=(a57*a03);
  a03=(-a03);
  if (res[1]!=0) res[1][86]=a03;
  a58=(a57*a58);
  a58=(-a58);
  if (res[1]!=0) res[1][87]=a58;
  if (res[1]!=0) res[1][88]=a05;
  a57=(a57*a51);
  a57=(-a57);
  if (res[1]!=0) res[1][89]=a57;
  a37=(a37*a21);
  a54=(a42*a54);
  a37=(a37+a54);
  a47=(a47*a21);
  a37=(a37-a47);
  a47=(a31*a43);
  a21=(a33*a45);
  a47=(a47-a21);
  a47=(a37+a47);
  a47=(-a47);
  if (res[1]!=0) res[1][90]=a47;
  if (res[1]!=0) res[1][91]=a53;
  a47=(a31*a60);
  a21=(a33*a59);
  a47=(a47-a21);
  a47=(-a47);
  if (res[1]!=0) res[1][92]=a47;
  if (res[1]!=0) res[1][93]=a56;
  a31=(a31*a52);
  a33=(a33*a04);
  a31=(a31-a33);
  a31=(-a31);
  if (res[1]!=0) res[1][94]=a31;
  if (res[1]!=0) res[1][95]=a03;
  if (res[1]!=0) res[1][96]=a58;
  if (res[1]!=0) res[1][97]=a05;
  if (res[1]!=0) res[1][98]=a49;
  a49=(a15*a45);
  a31=(a34*a43);
  a49=(a49+a31);
  a36=(a36-a49);
  a36=(-a36);
  if (res[1]!=0) res[1][99]=a36;
  if (res[1]!=0) res[1][100]=a53;
  a36=(a15*a59);
  a49=(a34*a60);
  a36=(a36+a49);
  if (res[1]!=0) res[1][101]=a36;
  if (res[1]!=0) res[1][102]=a56;
  a36=(a15*a04);
  a49=(a34*a52);
  a36=(a36+a49);
  if (res[1]!=0) res[1][103]=a36;
  if (res[1]!=0) res[1][104]=a03;
  if (res[1]!=0) res[1][105]=a58;
  if (res[1]!=0) res[1][106]=a05;
  if (res[1]!=0) res[1][107]=a57;
  a43=(a15*a43);
  a45=(a34*a45);
  a43=(a43-a45);
  a37=(a37+a43);
  a37=(-a37);
  if (res[1]!=0) res[1][108]=a37;
  if (res[1]!=0) res[1][109]=a53;
  a60=(a15*a60);
  a59=(a34*a59);
  a60=(a60-a59);
  a60=(-a60);
  if (res[1]!=0) res[1][110]=a60;
  if (res[1]!=0) res[1][111]=a56;
  a15=(a15*a52);
  a34=(a34*a04);
  a15=(a15-a34);
  a15=(-a15);
  if (res[1]!=0) res[1][112]=a15;
  if (res[1]!=0) res[1][113]=a03;
  if (res[1]!=0) res[1][114]=a58;
  if (res[1]!=0) res[1][115]=a05;
  if (res[1]!=0) res[1][116]=a05;
  if (res[1]!=0) res[1][117]=a05;
  if (res[1]!=0) res[1][118]=a05;
  a13=(a13/a40);
  a39=(a13*a39);
  a39=(a44*a39);
  if (res[1]!=0) res[1][119]=a39;
  a13=(a13*a06);
  a44=(a44*a13);
  if (res[1]!=0) res[1][120]=a44;
  a42=(a42*a38);
  a41=(a41*a50);
  a42=(a42+a41);
  a42=(a19*a42);
  a42=(-a42);
  if (res[1]!=0) res[1][121]=a42;
  a38=(a19*a38);
  a38=(-a38);
  if (res[1]!=0) res[1][122]=a38;
  a19=(a19*a50);
  if (res[1]!=0) res[1][123]=a19;
  return 0;
}

CASADI_SYMBOL_EXPORT int lipm_opti_pessi_cost_y_fun_jac_ut_xt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int lipm_opti_pessi_cost_y_fun_jac_ut_xt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int lipm_opti_pessi_cost_y_fun_jac_ut_xt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void lipm_opti_pessi_cost_y_fun_jac_ut_xt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int lipm_opti_pessi_cost_y_fun_jac_ut_xt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void lipm_opti_pessi_cost_y_fun_jac_ut_xt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void lipm_opti_pessi_cost_y_fun_jac_ut_xt_incref(void) {
}

CASADI_SYMBOL_EXPORT void lipm_opti_pessi_cost_y_fun_jac_ut_xt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int lipm_opti_pessi_cost_y_fun_jac_ut_xt_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int lipm_opti_pessi_cost_y_fun_jac_ut_xt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real lipm_opti_pessi_cost_y_fun_jac_ut_xt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* lipm_opti_pessi_cost_y_fun_jac_ut_xt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* lipm_opti_pessi_cost_y_fun_jac_ut_xt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* lipm_opti_pessi_cost_y_fun_jac_ut_xt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    case 4: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* lipm_opti_pessi_cost_y_fun_jac_ut_xt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    case 2: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int lipm_opti_pessi_cost_y_fun_jac_ut_xt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int lipm_opti_pessi_cost_y_fun_jac_ut_xt_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
