/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) lipm_opti_pessi_cost_y_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[3] = {22, 1, 1};
static const casadi_int casadi_s1[3] = {0, 1, 1};
static const casadi_int casadi_s2[3] = {38, 1, 1};
static const casadi_int casadi_s3[3] = {0, 0, 1};
static const casadi_int casadi_s4[3] = {8, 1, 1};
static const casadi_int casadi_s5[117] = 
  {44, 44, 0, 0, 0, 0, 0, 5,
  5, 5, 17, 17, 17, 17, 17, 17,
  17, 17, 22, 22, 22, 34, 34, 34,
  34, 35, 36, 39, 40, 41, 44, 46,
  48, 50, 52, 52, 53, 54, 57, 58,
  59, 62, 64, 66, 68, 70, 70, 7,
  28, 29, 30, 31, 4, 7, 22, 23,
  24, 25, 26, 27, 28, 29, 30, 31,
  18, 39, 40, 41, 42, 15, 18, 33,
  34, 35, 36, 37, 38, 39, 40, 41,
  42, 7, 7, 7, 24, 27, 7, 7,
  7, 24, 27, 4, 7, 4, 7, 4,
  7, 4, 7, 18, 18, 18, 35, 38,
  18, 18, 18, 35, 38, 15, 18, 15,
  18, 15, 18, 15, 18};

/* lipm_opti_pessi_cost_y_hess:(i0[22],i1[22],i2[0],i3[38],i4[],i5[8])->(o0[44x44,70nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39, a40, a41, a42, a43, a44, a45, a46, a47;
  casadi_real a48, a49, a50, a51, a52;
  a00=arg[0]? arg[0][9] : 0;
  a01=arg[0]? arg[0][7] : 0;
  a00=(a00-a01);
  a02=arg[3]? arg[3][14] : 0;
  a03=arg[3]? arg[3][12] : 0;
  a04=(a02+a03);
  a05=5.0809240767486585e+00;
  a06=arg[1]? arg[1][7] : 0;
  a07=(a05*a06);
  a08=sinh(a07);
  a08=(a05*a08);
  a09=(a04*a08);
  a10=(a00*a09);
  a11=arg[0]? arg[0][8] : 0;
  a12=arg[0]? arg[0][6] : 0;
  a11=(a11-a12);
  a13=arg[3]? arg[3][13] : 0;
  a14=arg[3]? arg[3][11] : 0;
  a15=(a13+a14);
  a16=(a15*a08);
  a17=(a11*a16);
  a10=(a10+a17);
  if (res[0]!=0) res[0][0]=a10;
  a17=1.;
  a07=cosh(a07);
  a18=(a17-a07);
  a19=(a18*a15);
  if (res[0]!=0) res[0][1]=a19;
  a18=(a18*a04);
  if (res[0]!=0) res[0][2]=a18;
  a20=(-a19);
  if (res[0]!=0) res[0][3]=a20;
  a21=(-a18);
  if (res[0]!=0) res[0][4]=a21;
  if (res[0]!=0) res[0][5]=a10;
  a10=arg[0]? arg[0][5] : 0;
  a22=arg[5]? arg[5][3] : 0;
  a23=(a22*a02);
  a24=arg[5]? arg[5][1] : 0;
  a25=(a24*a03);
  a23=(a23+a25);
  a25=arg[0]? arg[0][2] : 0;
  a26=(a10*a06);
  a25=(a25+a26);
  a26=cos(a25);
  a27=(a26*a10);
  a28=(a23*a27);
  a29=arg[5]? arg[5][2] : 0;
  a02=(a29*a02);
  a30=arg[5]? arg[5][0] : 0;
  a03=(a30*a03);
  a02=(a02+a03);
  a25=sin(a25);
  a03=(a25*a10);
  a31=(a02*a03);
  a28=(a28+a31);
  a31=(a22*a13);
  a32=(a24*a14);
  a31=(a31+a32);
  a03=(a31*a03);
  a28=(a28-a03);
  a13=(a29*a13);
  a14=(a30*a14);
  a13=(a13+a14);
  a27=(a13*a27);
  a28=(a28+a27);
  a10=(a10*a28);
  a27=1.9681459216763408e-01;
  a14=arg[0]? arg[0][4] : 0;
  a14=(a14*a04);
  a03=arg[0]? arg[0][3] : 0;
  a03=(a03*a15);
  a14=(a14+a03);
  a14=(a27*a14);
  a14=(a14*a08);
  a14=(a05*a14);
  a10=(a10-a14);
  a14=arg[1]? arg[1][4] : 0;
  a00=(a14*a00);
  a01=(a01+a00);
  a01=(a01*a04);
  a11=(a14*a11);
  a12=(a12+a11);
  a12=(a12*a15);
  a01=(a01+a12);
  a12=arg[0]? arg[0][1] : 0;
  a12=(a12*a04);
  a01=(a01-a12);
  a12=arg[0]? arg[0][0] : 0;
  a12=(a12*a15);
  a01=(a01-a12);
  a12=(a05*a07);
  a01=(a01*a12);
  a01=(a05*a01);
  a10=(a10+a01);
  if (res[0]!=0) res[0][6]=a10;
  a10=(-a16);
  if (res[0]!=0) res[0][7]=a10;
  a01=(-a09);
  if (res[0]!=0) res[0][8]=a01;
  if (res[0]!=0) res[0][9]=a28;
  a15=(a15*a07);
  a15=(-a15);
  if (res[0]!=0) res[0][10]=a15;
  a04=(a04*a07);
  a04=(-a04);
  if (res[0]!=0) res[0][11]=a04;
  a07=(a25*a23);
  a12=(a26*a02);
  a07=(a07-a12);
  a12=(a26*a31);
  a07=(a07+a12);
  a12=(a25*a13);
  a07=(a07+a12);
  a12=(a06*a28);
  a07=(a07+a12);
  if (res[0]!=0) res[0][12]=a07;
  a12=(a14*a16);
  a16=(a16-a12);
  if (res[0]!=0) res[0][13]=a16;
  a14=(a14*a09);
  a09=(a09-a14);
  if (res[0]!=0) res[0][14]=a09;
  if (res[0]!=0) res[0][15]=a12;
  if (res[0]!=0) res[0][16]=a14;
  a11=arg[0]? arg[0][20] : 0;
  a00=arg[0]? arg[0][18] : 0;
  a11=(a11-a00);
  a08=arg[3]? arg[3][33] : 0;
  a03=arg[3]? arg[3][31] : 0;
  a32=(a08+a03);
  a33=arg[1]? arg[1][18] : 0;
  a34=(a05*a33);
  a35=sinh(a34);
  a35=(a05*a35);
  a36=(a32*a35);
  a37=(a11*a36);
  a38=arg[0]? arg[0][19] : 0;
  a39=arg[0]? arg[0][17] : 0;
  a38=(a38-a39);
  a40=arg[3]? arg[3][32] : 0;
  a41=arg[3]? arg[3][30] : 0;
  a42=(a40+a41);
  a43=(a42*a35);
  a44=(a38*a43);
  a37=(a37+a44);
  if (res[0]!=0) res[0][17]=a37;
  a34=cosh(a34);
  a17=(a17-a34);
  a44=(a17*a42);
  if (res[0]!=0) res[0][18]=a44;
  a17=(a17*a32);
  if (res[0]!=0) res[0][19]=a17;
  a45=(-a44);
  if (res[0]!=0) res[0][20]=a45;
  a46=(-a17);
  if (res[0]!=0) res[0][21]=a46;
  if (res[0]!=0) res[0][22]=a37;
  a37=arg[0]? arg[0][16] : 0;
  a47=(a22*a08);
  a48=(a24*a03);
  a47=(a47+a48);
  a48=arg[0]? arg[0][13] : 0;
  a49=(a37*a33);
  a48=(a48+a49);
  a49=cos(a48);
  a50=(a49*a37);
  a51=(a47*a50);
  a08=(a29*a08);
  a03=(a30*a03);
  a08=(a08+a03);
  a48=sin(a48);
  a03=(a48*a37);
  a52=(a08*a03);
  a51=(a51+a52);
  a22=(a22*a40);
  a24=(a24*a41);
  a22=(a22+a24);
  a03=(a22*a03);
  a51=(a51-a03);
  a29=(a29*a40);
  a30=(a30*a41);
  a29=(a29+a30);
  a50=(a29*a50);
  a51=(a51+a50);
  a37=(a37*a51);
  a50=arg[0]? arg[0][15] : 0;
  a50=(a50*a32);
  a30=arg[0]? arg[0][14] : 0;
  a30=(a30*a42);
  a50=(a50+a30);
  a27=(a27*a50);
  a27=(a27*a35);
  a27=(a05*a27);
  a37=(a37-a27);
  a27=arg[1]? arg[1][15] : 0;
  a11=(a27*a11);
  a00=(a00+a11);
  a00=(a00*a32);
  a38=(a27*a38);
  a39=(a39+a38);
  a39=(a39*a42);
  a00=(a00+a39);
  a39=arg[0]? arg[0][12] : 0;
  a39=(a39*a32);
  a00=(a00-a39);
  a39=arg[0]? arg[0][11] : 0;
  a39=(a39*a42);
  a00=(a00-a39);
  a39=(a05*a34);
  a00=(a00*a39);
  a05=(a05*a00);
  a37=(a37+a05);
  if (res[0]!=0) res[0][23]=a37;
  a37=(-a43);
  if (res[0]!=0) res[0][24]=a37;
  a05=(-a36);
  if (res[0]!=0) res[0][25]=a05;
  if (res[0]!=0) res[0][26]=a51;
  a42=(a42*a34);
  a42=(-a42);
  if (res[0]!=0) res[0][27]=a42;
  a32=(a32*a34);
  a32=(-a32);
  if (res[0]!=0) res[0][28]=a32;
  a34=(a48*a47);
  a00=(a49*a08);
  a34=(a34-a00);
  a00=(a49*a22);
  a34=(a34+a00);
  a00=(a48*a29);
  a34=(a34+a00);
  a00=(a33*a51);
  a34=(a34+a00);
  if (res[0]!=0) res[0][29]=a34;
  a00=(a27*a43);
  a43=(a43-a00);
  if (res[0]!=0) res[0][30]=a43;
  a27=(a27*a36);
  a36=(a36-a27);
  if (res[0]!=0) res[0][31]=a36;
  if (res[0]!=0) res[0][32]=a00;
  if (res[0]!=0) res[0][33]=a27;
  if (res[0]!=0) res[0][34]=a10;
  if (res[0]!=0) res[0][35]=a01;
  if (res[0]!=0) res[0][36]=a28;
  a28=(a23*a26);
  a01=(a02*a25);
  a28=(a28+a01);
  a01=(a31*a25);
  a28=(a28-a01);
  a01=(a13*a26);
  a28=(a28+a01);
  if (res[0]!=0) res[0][37]=a28;
  a26=(a26*a06);
  a23=(a23*a26);
  a25=(a25*a06);
  a02=(a02*a25);
  a23=(a23+a02);
  a31=(a31*a25);
  a23=(a23-a31);
  a13=(a13*a26);
  a23=(a23+a13);
  if (res[0]!=0) res[0][38]=a23;
  if (res[0]!=0) res[0][39]=a15;
  if (res[0]!=0) res[0][40]=a04;
  if (res[0]!=0) res[0][41]=a07;
  if (res[0]!=0) res[0][42]=a23;
  a06=(a06*a23);
  if (res[0]!=0) res[0][43]=a06;
  if (res[0]!=0) res[0][44]=a19;
  if (res[0]!=0) res[0][45]=a16;
  if (res[0]!=0) res[0][46]=a18;
  if (res[0]!=0) res[0][47]=a09;
  if (res[0]!=0) res[0][48]=a20;
  if (res[0]!=0) res[0][49]=a12;
  if (res[0]!=0) res[0][50]=a21;
  if (res[0]!=0) res[0][51]=a14;
  if (res[0]!=0) res[0][52]=a37;
  if (res[0]!=0) res[0][53]=a05;
  if (res[0]!=0) res[0][54]=a51;
  a51=(a47*a49);
  a05=(a08*a48);
  a51=(a51+a05);
  a05=(a22*a48);
  a51=(a51-a05);
  a05=(a29*a49);
  a51=(a51+a05);
  if (res[0]!=0) res[0][55]=a51;
  a49=(a49*a33);
  a47=(a47*a49);
  a48=(a48*a33);
  a08=(a08*a48);
  a47=(a47+a08);
  a22=(a22*a48);
  a47=(a47-a22);
  a29=(a29*a49);
  a47=(a47+a29);
  if (res[0]!=0) res[0][56]=a47;
  if (res[0]!=0) res[0][57]=a42;
  if (res[0]!=0) res[0][58]=a32;
  if (res[0]!=0) res[0][59]=a34;
  if (res[0]!=0) res[0][60]=a47;
  a33=(a33*a47);
  if (res[0]!=0) res[0][61]=a33;
  if (res[0]!=0) res[0][62]=a44;
  if (res[0]!=0) res[0][63]=a43;
  if (res[0]!=0) res[0][64]=a17;
  if (res[0]!=0) res[0][65]=a36;
  if (res[0]!=0) res[0][66]=a45;
  if (res[0]!=0) res[0][67]=a00;
  if (res[0]!=0) res[0][68]=a46;
  if (res[0]!=0) res[0][69]=a27;
  return 0;
}

CASADI_SYMBOL_EXPORT int lipm_opti_pessi_cost_y_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int lipm_opti_pessi_cost_y_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int lipm_opti_pessi_cost_y_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void lipm_opti_pessi_cost_y_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int lipm_opti_pessi_cost_y_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void lipm_opti_pessi_cost_y_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void lipm_opti_pessi_cost_y_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void lipm_opti_pessi_cost_y_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int lipm_opti_pessi_cost_y_hess_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int lipm_opti_pessi_cost_y_hess_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real lipm_opti_pessi_cost_y_hess_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* lipm_opti_pessi_cost_y_hess_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* lipm_opti_pessi_cost_y_hess_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* lipm_opti_pessi_cost_y_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    case 4: return casadi_s3;
    case 5: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* lipm_opti_pessi_cost_y_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int lipm_opti_pessi_cost_y_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int lipm_opti_pessi_cost_y_hess_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
